### ISSUE TITLE
Consider adding warnings for unused option items

### ISSUE THREAD

**Issue by upsuper** [rust-lang/rust-bindgen#1055]
It is easy to find that you need to whitelist, blacklist, opaque, etc. something but you forget to, but it is much harder to catch when you forget to remove something from the list.

I think it would be helpful to display some warning information when an item doesn't match anything, so that users are aware that they can remove them.

This may need support from `regex` crate, I guess. On the API side, I think we can add a new function to `Bindings` to get that information.

**Comment by pvdrz** [comment]
Fixed via #1469
