### ISSUE TITLE
macOS continuous integration

### ISSUE THREAD

**Issue by pepyakin** [rust-lang/rust-bindgen#1072]
The last two issues ([1](https://github.com/rust-lang-nursery/rust-bindgen/issues/1004), [2](https://github.com/rust-lang-nursery/rust-bindgen/issues/1067)) with macOS build made it clear that we need macOS CI.

@fitzgen noted that once upon a time there was macOS builds on Travis CI, but since they took very long time they were disabled.

Maybe it is worth to run the "full suite" asynchroniously after the merge?

**Comment by pepyakin** [comment]
Also, these failures made me to explore the ways running the tests on linux on my macOS machine.

So I came up with this [`Dockerfile`](https://gist.github.com/pepyakin/6ce7c9cbb5abdd1add82f4fd52f7767f). I'm wondering is it worth to check it in?

**Comment by fitzgen** [comment]
It wasn't that the tests themselves took a long time, it was that Travis CI doesn't have very many macos builders, and so the wait time was something like 2-4 hours.
