### ISSUE TITLE
Generate code doesn't compile

### ISSUE THREAD

**Issue by hfiguiere** [rust-lang/rust-bindgen#1110]
It was ok with 0.30.0.

With 0.31.0 I get this errror when building:
```
error: expected `(`, found `1`
  --> /home/hub/source/niepce/target/debug/build/niepce_rust-a6b45114914113bd/out/bindings.rs:47:43
   |
47 |  pub fn __shared_count___shared_count<_Lp>1 ( this : * mut u8 , __r : * mut u8 , ) ; 
   |                                           ^

error: Could not compile `niepce_rust`.
```

My project is at:
https://github.com/hfiguiere/niepce/tree/bindgen-bug

bindgen is called by the `build.rs` (`cargo build`)

**Comment by pepyakin** [comment]
Hello @hfiguiere !

Can you paste the header file which exposes this problem?

**Comment by MTRNord** [comment]
I have the same problem (I wanted to try if I get a nodejs binding. So the header is a little big to post.) It should be https://github.com/nodejs/node/blob/master/src/node.h for me.

Error with this on windows is: 

```
$ cargo build
   Compiling nodejs-binding v0.1.0 (file:///C:/Users/marce/Desktop/nodejs_madness/nodejs-binding)
error: expected `(`, found `1`
    --> C:\Users\marce\Desktop\nodejs_madness\nodejs-binding\target\debug\build\nodejs-binding-8568950a2904e59d\out/bindings.rs:7883:54
     |
7883 |             pub fn __shared_count___shared_count<_Lp>1(this: *mut u8,
     | 
```

**Comment by hfiguiere** [comment]
It is in the git repository I linked https://github.com/hfiguiere/niepce/blob/bindgen-bug/src/engine/db/bindings.hpp

It includes other headers that are in the tree.

**Comment by fitzgen** [comment]
Hi @hfiguiere, thanks for filing an issue!

The best way you can help us investigate and resolve this bug is by providing a standalone, reduced test case via `creduce`: https://github.com/rust-lang-nursery/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases

Thanks again!

**Comment by hfiguiere** [comment]
With the source tree mentionned above
```
~/.cargo/bin/bindgen ./src/fwk/utils/files.hpp -- -DRUST_BINDGEN=1 --std=c++11 > test.rs && rustc ./test.rs
```

the guilty type is `fwk::FileList` (on of the four types I whitelist)

**Comment by hfiguiere** [comment]
My environment is Fedora 27 that has gcc 7.1.2 (since that's the headers it uses)

**Comment by fitzgen** [comment]
> My environment is Fedora 27 that has gcc 7.1.2 (since that's the headers it uses)

If you follow the instructions I linked, which is the best way you can help get this bug fixed, then you will end up with a standalone test case that doesn't depend on any system headers.

**Comment by hfiguiere** [comment]
Still happening in 0.33.1.

And using `creduce` doesn't help as the output end up being a single byte file with the content `}`

**Comment by hfiguiere** [comment]
Here is the .ii file (sorry I had to rename it .txt for github to allow it):

[isolated-test-case.hpp.txt](https://github.com/rust-lang-nursery/rust-bindgen/files/1740081/isolated-test-case.hpp.txt)

````
bindgen isolated-test-case.hpp -- --std=c++11  > test.rs && rustc --crate-type=lib ./test.rs
````

**Comment by hfiguiere** [comment]
Still happening in 0.36.0 FWIW.

I'd remove the label about the need for a reduced test case since it is provided above, but I can't.

**Comment by emilio** [comment]
I'd argue that the test-case can be reduced further. But anyway, thank you for attaching it, it's really helpful. I haven't had the time to investigate yet, chances are that we're just getting a bogus name with those brackets out of libclang.

**Comment by emilio** [comment]
I'll try to run creduce on it when I have a working setup

**Comment by hfiguiere** [comment]
As of 0.37.0, I can no longer reproduce. Sadly I wish I could say I could build, but that will be a different issue.

**Comment by hfiguiere** [comment]
Unlike I said, still happening on 0.37.0 with that reduced test case.

**Comment by pvdrz** [comment]
I ran bindgen 0.65.1 with this input and the rustc errors are the same as https://github.com/rust-lang/rust-bindgen/issues/1914 so I'm closing this as a duplicate.
