### ISSUE TITLE
Unable to build rust torch bindings https://github.com/posix4e/rust-torch

### ISSUE THREAD

**Issue by posix4e** [rust-lang/rust-bindgen#1154]
### Input C/C++ Header

```C++
#include "TH/TH.h"
```

We actually generate it.

```
bindgen --no-derive-debug --builtins tmp/expanded.h -o "$output"
```

### Actual Results

```
Error { repr: Custom(Custom { kind: Other, error: StringError("Cannot find binary path") }) }
```

```rust
http://termbin.com/lgfd
```

```
http://termbin.com/d39u
```

### Expected Results
I expected it to compile

**Comment by posix4e** [comment]
I tried it with an older version of bindgen and I didn't get an error when compiling but i still get an error when building
```
posi@posi:~/src/rust-torch$ cargo build
   Compiling torch v0.1.0 (file:///home/posi/src/rust-torch)
error: const fn is unstable (see issue #24111)
   --> src/lib.rs:420:5
    |
420 | /     pub const fn new_bitfield_1(__w_termsig: ::std::os::raw::c_uint,
421 | |                                 __w_coredump: ::std::os::raw::c_uint,
422 | |                                 __w_retcode: ::std::os::raw::c_uint) -> u32 {
423 | |         let bitfield_unit_val =
...   |
441 | |         bitfield_unit_val | __w_retcode
442 | |     }
    | |_____^

error: const fn is unstable (see issue #24111)
   --> src/lib.rs:498:5
    |
498 | /     pub const fn new_bitfield_1(__w_stopval: ::std::os::raw::c_uint,
499 | |                                 __w_stopsig: ::std::os::raw::c_uint) -> u32 {
500 | |         let bitfield_unit_val =
501 | |             {
...   |
511 | |         bitfield_unit_val | __w_stopsig
512 | |     }
    | |_____^

error: aborting due to previous error(s)

error: Could not compile `torch`.
```

**Comment by posix4e** [comment]
Apparently with this old version of bindgen it works if i tell it not to generate unstable rust code. Should I leave this open?

**Comment by fitzgen** [comment]
Hi @posix4e, thanks for filing a bug. Can you provide a standalone version of the input header file? https://github.com/rust-lang-nursery/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases

Without that, unfortunately, this this issue is not very actionable. Thanks!

**Comment by posix4e** [comment]
@fitzgen the one line h file generated http://termbin.com/lgfd

**Comment by fitzgen** [comment]
> @fitzgen the one line h file generated http://termbin.com/lgfd

The "one line h file" is an include of another header, which includes an unknown further number of headers, each of which include ... etc.

In order for this issue to be actionable, we need at minimum the header *after the preprocessor runs* and preferrably after running `creduce` as well. You can find instructions for producing these things in the link I gave above.

Thanks!

**Comment by XVilka** [comment]
@fitzgen I have the same error and ran a creduce on it, sadly it returns exactly the same file after a whole night of trying to reduce it. The file is https://github.com/radare/radare2/blob/master/libr/include/r_core.h This is my creduce predicate script:
```bash
CMD="bindgen --verbose /home/user/data/tmp/r_core.h -o /home/user/data/tmp/r2-api/r_core.rs -- -I/usr/local/include/libr"
OUT=$($CMD 3>&1 1>&2 2>&3)
EXPECT="Error { repr: Custom(Custom { kind: Other, error: StringError(\"Cannot find binary path\") }) }"

if [ "$OUT" == "$EXPECT" ]; then
	exit 0
else
	exit 1
fi
```

**Comment by XVilka** [comment]
@fitzgen should I open a separate bug for this radare2 case? Or it's fine here? Also creduce failed on this testcase, I sent them bugreport, they will check it.
