### ISSUE TITLE
Radare2 bindings - Error { repr: Custom(Custom { kind: Other, error: StringError(\"Cannot find binary path\") }) }

### ISSUE THREAD

**Issue by XVilka** [rust-lang/rust-bindgen#1205]
The file is https://github.com/radare/radare2/blob/master/libr/include/r_core.h This is my creduce predicate script:
```bash
CMD="bindgen --verbose /home/user/data/tmp/r_core.h -o /home/user/data/tmp/r2-api/r_core.rs -- -I/usr/local/include/libr"
OUT=$($CMD 3>&1 1>&2 2>&3)
EXPECT="Error { repr: Custom(Custom { kind: Other, error: StringError(\"Cannot find binary path\") }) }"

if [ "$OUT" == "$EXPECT" ]; then
	exit 0
else
	exit 1
fi
```
Here is the preprocessed file 
[__bindgen.i.gz](https://github.com/rust-lang-nursery/rust-bindgen/files/1570175/__bindgen.i.gz)

Sadly creduce cannot reduce this test because of the bug in the creduce itself - I sent them a report, they are checking it.

See also https://github.com/rust-lang-nursery/rust-bindgen/issues/1154

**Comment by emilio** [comment]
That error comes from the `which` crate, and should be non-fatal.

**Comment by XVilka** [comment]
Well, it prevents from the generating the full bindings for this file.

**Comment by emilio** [comment]
Hmm, it definitely should not.

We write the (unformatted) bindings right after printing the error in:

https://github.com/rust-lang-nursery/rust-bindgen/blob/ac523232d317373aec9c638f6b0451c78f11f892/src/lib.rs#L1693

Does it happen on master? I think you're getting bit by what I fixed in #1112.

**Comment by XVilka** [comment]
@emilio aha, now it writes the file, but not sure, it looks bad. Ultralong lines without splitting.

**Comment by XVilka** [comment]
@emilio aha, seems that `which` crate returned an error because of missing `rustfmt` binary. Fixed it with `cargo install rustfmt`. Imho the error should clarify which binary is exactly missing. Now have a problem inside rustfmt it seems:
```
Error { repr: Custom(Custom { kind: Other, error: StringError("Internal rustfmt error") }) }
```

**Comment by fschutt** [comment]
Ran into this myself. Could you add this to the README or the book, that in order to use the CLI, you need to install `rustfmt-nightly` (not the regular `rustfmt`)? A more descriptive error would be appreciated as well. Thanks.

**Comment by emilio** [comment]
Sorry for missing this one, yeah, this should be added to the docs... I can't do it right now but I'll put it in the queue. PRs welcome if you manage to get to it earlier of course. Sorry!
