### ISSUE TITLE
typedef struct X * X generates invalid Rust code

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/rust-bindgen#1252]
### Input C/C++ Header

```c
struct X {
  int x;
};
typedef struct X * X;
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct X {
    pub x: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_X() {
    assert_eq!(
        ::std::mem::size_of::<X>(),
        4usize,
        concat!("Size of: ", stringify!(X))
    );
    assert_eq!(
        ::std::mem::align_of::<X>(),
        4usize,
        concat!("Alignment of ", stringify!(X))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<X>())).x as *const _ as usize },
        0usize,
        concat!("Offset of field: ", stringify!(X), "::", stringify!(x))
    );
}
pub type X = *mut X;
```

### Expected Results

I'm not sure what exact output is correct, but I think `struct X { ... } X;` is equivalent to `struct X { ... }; typedef struct X * X;`, so probably right thing to do is:

```diff
-pub type X = *mut X;
+extern "C" {
+    #[link_name = "\u{1}X"]
+    pub static mut X: X;
+}
```

**Comment by ignatenkobrain** [comment]
Or, probably, it should rename original structure.. I'm not really sure what's the right thing to do here.

**Comment by emilio** [comment]
Yeah, I think renaming it is the right thing, though it's slightly annoying... We may want to support a "C" naming mode, where structs become `struct_X`, enums become `enum_X`, etc...

**Comment by emilio** [comment]
For now the best solution would be to blacklist it, preventing it from getting generated, but that's annoying.

**Comment by ignatenkobrain** [comment]
@emilio is there some workaround I can use meanwhile? I really need that poptOption because bindings I generate have it as argument to some functions.

**Comment by tony-iqlusion** [comment]
@ignatenkobrain FWIW I too just had to deal with bindgen and `popt.h`.

My "solution" was to have bindgen produce a C++ binding instead of a C one, which triggers some `#ifdef __cplusplus` gating inside of `popt.h` which disables these typedefs.
