### ISSUE TITLE
typedef type names collide with rust builtin type names

### ISSUE THREAD

**Issue by buntpfotenkatze** [rust-lang/rust-bindgen#1257]
When running `/usr/include/pci/pci.h` through bindgen, it produces a cyclic reference in the type definition:

### Input C/C++ Header

```C
typedef unsigned char __uint8_t;
typedef __uint8_t uint8_t;
typedef uint8_t u8;
```

### Bindgen Invocation

```
$ bindgen types.h
```

### Actual Results

```rust
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type u8 = u8;
```

`rustc` fails with the error message:
```
error[E0391]: unsupported cyclic reference between types/traits detected
 --> <anon>:2:15
  |
2 | pub type u8 = u8;
  |               ^^ cyclic reference
  |
note: the cycle begins when processing `u8`...
 --> <anon>:2:1
  |
2 | pub type u8 = u8;
  | ^^^^^^^^^^^^^^^^^
  = note: ...which then again requires processing `u8`, completing the cycle.

error: aborting due to previous error
```

### Expected Results

bindgen should scramble the new type name `u8`.

**Comment by emilio** [comment]
For this case where the types actually match I think you can just blacklist it.

I'm not sure Rust will emit an error for the cases the definition is not recursive, but in that case we'd need to mangle the type somehow.

**Comment by jdm** [comment]
This was fixed by https://github.com/rust-lang/rust-bindgen/pull/1798, right?

**Comment by emilio** [comment]
Yes, thanks @jdm!
