### ISSUE TITLE
ObjectiveC generics are not type erased properly

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust-bindgen#1259]
### Input C/C++ Header

```C++
@interface Base
@end

@interface NSArray<ObjectType> : Base
-(ObjectType)getit;
@end
```

### Bindgen Invocation
```
bindgen --objc-extern-crate generics.m -- -x objective-c
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

#[macro_use]
extern crate objc;
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
pub trait Base {}
impl Base for id {}
pub trait Bar {
    unsafe fn getit(self) -> *mut ObjectType;
}
impl Bar for id {
    unsafe fn getit(self) -> *mut ObjectType {
        msg_send!(self, getit)
    }
}
```

### Expected Results

At a minimum we should erase the generics. Even better we could convert them to rust generics.

Proper support for this is needed for running bindgen on the mac system headers.

**Comment by emilio** [comment]
Objc support is known-WIP. But type-erasing this or generating the generics should be easy, it'd be just a matter of figuring out how clang exposes them on the AST and hooking them up to the rest of template parameter infrastructure we have in `src/ir/analysis`.
