### ISSUE TITLE
Ability to see the actual clang command that is getting run

### ISSUE THREAD

**Issue by michaeleiselsc** [rust-lang/rust-bindgen#1280]
Hi, I would like to see the actual clang command that is getting run in order to debug an issue. Is there some flag to do this? If not, +1 for this feature

**Comment by emilio** [comment]
We have `command_line_flags`, but we don't run clang under the hood, we just invoke libclang. The flags passed there are effectively the clang_args that command_line_flags would return, plus the effective target if not passed explicitly.

**Comment by pvdrz** [comment]
`clang_args` and all the other options are shown at a debug log entry: https://github.com/rust-lang/rust-bindgen/blob/9677e412c49e303e078e37ee30105cc635bb0ff8/src/lib.rs#L2436
