### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by tmfink** [rust-lang/rust-bindgen#1283]
The [CHANGELOG.md](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/CHANGELOG.md) is:

- [ ] missing releases:
    - 0.33.2
    - 0.32.2
    - 0.31.3
    - 0.31.2
- [ ] The 0.33.0 entry is filled with "TODO"

**Comment by kellda** [comment]
Seems that the changelog is up to date now
