### ISSUE TITLE
bindgen manual doesn't mention need for build-dependencies

### ISSUE THREAD

**Issue by spease** [rust-lang/rust-bindgen#1296]
https://github.com/rust-lang-nursery/rust-bindgen/blob/master/book/src/tutorial-3.md

Small issue. It'd been awhile since I'd written a buildscript, so I had to look it up again.

**Comment by ydirson** [comment]
As of today it is in https://rust-lang.github.io/rust-bindgen/tutorial-1.html

**Comment by pvdrz** [comment]
Thanks for the catch!
