### ISSUE TITLE
Unclear error message if header file is missing

### ISSUE THREAD

**Issue by spease** [rust-lang/rust-bindgen#1298]
If the header file specified doesn't exist, bindgen just reports:

```
Unable to generate bindings: ()
```

It'd be nice if it explicitly told you it couldn't find the header

**Comment by ekse** [comment]
The code on master prints `error: header 'invalid_filename.h' does not exist.` on the line before.

**Comment by pvdrz** [comment]
currently master prints: 
```thread 'main' panicked at 'Unable to generate bindings: NotExist("invalid_filename.h")```
