### ISSUE TITLE
Allow specifying derive name

### ISSUE THREAD

**Issue by spease** [rust-lang/rust-bindgen#1301]
There's probably some overlap with this and other issues, but rather than having a derive() function for each derive, I'd just either let somebody specify it (`derive("PartialOrd")`) or specify multiple ones somehow (`derive("Clone,Copy")`). This reduces the API size and increases functionality.

There are some special cases where derivations automatically trigger other derivations, I'd either just make derive() a straight specification of exactly what you want to appear (this might allow for other things besides just names down the road, if that ever gets supported). Or go ahead and parse the list and automatically derive those things.

**Comment by emilio** [comment]
The issue with this is that different derive(..) stuff have different requirements. Those requirements are encoded in `src/ir/analysis/derive_*`. Not sure how feasible would it be to make that logic work for generic derive, I guess someone would have to try.

**Comment by spease** [comment]
I was suggesting hardcoding the the requirements for the default derives. Presumably user libraries are not going to replace them, or at least not commonly.

**Comment by pvdrz** [comment]
you can use the custom derive API for this nowadays

**Comment by Plegeus** [comment]
> you can use the custom derive API for this nowadays

Dear Pvdrz, 
Could you give me a pointer to this api? 
I have been looking for this four an hour now, all I see is the specific function (`derive_copy`, `derive_debug`, etc.) on the `Builder` struct.
Thank you.

**Comment by pvdrz** [comment]
https://docs.rs/bindgen/latest/bindgen/callbacks/trait.ParseCallbacks.html#method.add_derives
