### ISSUE TITLE
Large bitfield structs don't meet `__BindgenBitfieldUnit` parameter bounds

### ISSUE THREAD

**Issue by ranweiler** [rust-lang/rust-bindgen#1325]
**Summary:**
For large structs with bitfields, Bindgen will generate bindings whose underlying types do not meet the trait bounds of the `Storage` parameter of `__BindgenBitfieldUnit`.

**Cause:**
The `Storage` param of `__BindgenBitfieldUnit` must satisfy the bound `AsRef<[u8]> + AsMut<[u8]>`. But, the `AsRef<[u8]>` and `AsMut<[u8]>` traits only have impls for arrays `[u8; N]` for `N <= 32`. If a struct uses bitfields in a way that causes usage of a `Storage` type parameter of `__BindgenBitfieldUnit` with greater `N`, then the generated code will not compile.

These large arrays also cause `Copy` derivation to fail for these types, but that can at least be disabled using `builder.derive_copy(false)`.

### Input C/C++ Header

I've included two example headers, minimal in different ways. 

Here is a short header `foo.h` that triggers the bug a bit coarsely:

```c
struct GoodA {
  uint64_t f0 : 64;
  uint64_t f1 : 64;
  uint64_t f2 : 64;
  uint64_t f3 : 64;
};

struct BadA {
  // These fields are the same as `GoodA`.
  uint64_t f0 : 64;
  uint64_t f1 : 64;
  uint64_t f2 : 64;
  uint64_t f3 : 64;

  // Causes `storage` to have type `[u8; 40]`, but 40 > 32, so we are missing impls.
  uint8_t bad : 1;
};
```

`bar.h` contains longer structs, with a `BadB` struct whose generated `storage` array _just_ exceeds the automatic trait derivation boundary:

<details><summary>Expand <code>bar.h</code></summary>

```c
#include <stdint.h>

struct GoodB {
  uint8_t f0 : 8;
  uint8_t f1 : 8;
  uint8_t f2 : 8;
  uint8_t f3 : 8;
  uint8_t f4 : 8;
  uint8_t f5 : 8;
  uint8_t f6 : 8;
  uint8_t f7 : 8;
  uint8_t f8 : 8;
  uint8_t f9 : 8;
  uint8_t f10 : 8;
  uint8_t f11 : 8;
  uint8_t f12 : 8;
  uint8_t f13 : 8;
  uint8_t f14 : 8;
  uint8_t f15 : 8;
  uint8_t f16 : 8;
  uint8_t f17 : 8;
  uint8_t f18 : 8;
  uint8_t f19 : 8;
  uint8_t f20 : 8;
  uint8_t f21 : 8;
  uint8_t f22 : 8;
  uint8_t f23 : 8;
  uint8_t f24 : 8;
  uint8_t f25 : 8;
  uint8_t f26 : 8;
  uint8_t f27 : 8;
  uint8_t f28 : 8;
  uint8_t f29 : 8;
  uint8_t f30 : 8;
  uint8_t f31 : 8;
};

struct BadB {
  uint8_t f0 : 8;
  uint8_t f1 : 8;
  uint8_t f2 : 8;
  uint8_t f3 : 8;
  uint8_t f4 : 8;
  uint8_t f5 : 8;
  uint8_t f6 : 8;
  uint8_t f7 : 8;
  uint8_t f8 : 8;
  uint8_t f9 : 8;
  uint8_t f10 : 8;
  uint8_t f11 : 8;
  uint8_t f12 : 8;
  uint8_t f13 : 8;
  uint8_t f14 : 8;
  uint8_t f15 : 8;
  uint8_t f16 : 8;
  uint8_t f17 : 8;
  uint8_t f18 : 8;
  uint8_t f19 : 8;
  uint8_t f20 : 8;
  uint8_t f21 : 8;
  uint8_t f22 : 8;
  uint8_t f23 : 8;
  uint8_t f24 : 8;
  uint8_t f25 : 8;
  uint8_t f26 : 8;
  uint8_t f27 : 8;
  uint8_t f28 : 8;
  uint8_t f29 : 8;
  uint8_t f30 : 8;
  uint8_t f31 : 8;

  // Causes `storage` to have type `[u8; 33]`.
  uint8_t bad : 1;
};
```
</details>

### Bindgen Invocation

```rust
extern crate bindgen;

fn main() {
    let bindings = bindgen::Builder::default()
        .header("./foo.h")  // Or `bar.h`
        .derive_copy(false) // ! Needed; related to bug
        .generate()
        .expect("Failed generate bindings");

    bindings
        .write_to_file("src/foo.rs")
        .expect("Failed to write bindings");
}

```

### Actual Results

Binding generation succeeds, but compilation fails. 

<details><summary>Compilation errors for <code>bar.h</code>:</summary>

```
error[E0277]: the trait bound `[u8; 33]: std::convert::AsRef<[u8]>` is not satisfied
   --> src/foo.rs:711:5
    |
711 |     pub _bitfield_1: __BindgenBitfieldUnit<[u8; 33usize], u8>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::AsRef<[u8]>` is not implemented for `[u8; 33]`
    |
    = help: the following implementations were found:
              <[T; 21] as std::convert::AsRef<[T]>>
              <[T; 8] as std::convert::AsRef<[T]>>
              <[T; 2] as std::convert::AsRef<[T]>>
              <[T; 26] as std::convert::AsRef<[T]>>
            and 30 others
note: required by `foo::__BindgenBitfieldUnit`
   --> src/foo.rs:5:1
    |
5   | / pub struct __BindgenBitfieldUnit<Storage, Align>
6   | | where
7   | |     Storage: AsRef<[u8]> + AsMut<[u8]>,
8   | | {
9   | |     storage: Storage,
10  | |     align: [Align; 0],
11  | | }
    | |_^

error[E0277]: the trait bound `[u8; 33]: std::convert::AsMut<[u8]>` is not satisfied
   --> src/foo.rs:711:5
    |
711 |     pub _bitfield_1: __BindgenBitfieldUnit<[u8; 33usize], u8>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::AsMut<[u8]>` is not implemented for `[u8; 33]`
    |
    = help: the following implementations were found:
              <[T; 7] as std::convert::AsMut<[T]>>
              <[T; 32] as std::convert::AsMut<[T]>>
              <[T; 17] as std::convert::AsMut<[T]>>
              <[T; 20] as std::convert::AsMut<[T]>>
            and 30 others
note: required by `foo::__BindgenBitfieldUnit`
   --> src/foo.rs:5:1
    |
5   | / pub struct __BindgenBitfieldUnit<Storage, Align>
6   | | where
7   | |     Storage: AsRef<[u8]> + AsMut<[u8]>,
8   | | {
9   | |     storage: Storage,
10  | |     align: [Align; 0],
11  | | }
    | |_^

error[E0277]: the trait bound `[u8; 33]: std::convert::AsRef<[u8]>` is not satisfied
    --> src/foo.rs:1091:5
     |
1091 | /     pub fn new_bitfield_1(
1092 | |         f0: u8,
1093 | |         f1: u8,
1094 | |         f2: u8,
...    |
1260 | |         __bindgen_bitfield_unit
1261 | |     }
     | |_____^ the trait `std::convert::AsRef<[u8]>` is not implemented for `[u8; 33]`
     |
     = help: the following implementations were found:
               <[T; 21] as std::convert::AsRef<[T]>>
               <[T; 8] as std::convert::AsRef<[T]>>
               <[T; 2] as std::convert::AsRef<[T]>>
               <[T; 26] as std::convert::AsRef<[T]>>
             and 30 others
note: required by `foo::__BindgenBitfieldUnit`
    --> src/foo.rs:5:1
     |
5    | / pub struct __BindgenBitfieldUnit<Storage, Align>
6    | | where
7    | |     Storage: AsRef<[u8]> + AsMut<[u8]>,
8    | | {
9    | |     storage: Storage,
10   | |     align: [Align; 0],
11   | | }
     | |_^

error[E0277]: the trait bound `[u8; 33]: std::convert::AsMut<[u8]>` is not satisfied
    --> src/foo.rs:1091:5
     |
1091 | /     pub fn new_bitfield_1(
1092 | |         f0: u8,
1093 | |         f1: u8,
1094 | |         f2: u8,
...    |
1260 | |         __bindgen_bitfield_unit
1261 | |     }
     | |_____^ the trait `std::convert::AsMut<[u8]>` is not implemented for `[u8; 33]`
     |
     = help: the following implementations were found:
               <[T; 7] as std::convert::AsMut<[T]>>
               <[T; 32] as std::convert::AsMut<[T]>>
               <[T; 17] as std::convert::AsMut<[T]>>
               <[T; 20] as std::convert::AsMut<[T]>>
             and 30 others
note: required by `foo::__BindgenBitfieldUnit`
    --> src/foo.rs:5:1
     |
5    | / pub struct __BindgenBitfieldUnit<Storage, Align>
6    | | where
7    | |     Storage: AsRef<[u8]> + AsMut<[u8]>,
8    | | {
9    | |     storage: Storage,
10   | |     align: [Align; 0],
11   | | }
     | |_^

error: aborting due to 4 previous errors
```
</details>

### Expected Results

I think this will just be solved when const generics land. In the meantime, it would be great to have one of the following:
1. Binding generation could fail informatively, rather than generate code that fails to compile.
1. Avoid explicitly using `AsRef` and `AsMut` in the implementation.
1. bindgen could generate its own internal traits that proxy `AsRef<[u8]>`/`AsMut<[u8]>` but _also_ allow us to generate any "just-in-time" concrete impl for `[u8; N]` for a given `N`.
1. Some other internal workaround or change to the impl of `__BindgenBitfieldUnit`?

Thanks!

**Comment by db48x** [comment]
https://github.com/rust-lang-nursery/rust-bindgen/blob/master/src/ir/comp.rs#L616

Looks like it never adds multiple `BitfieldUnits` because it only calls `flush_allocation_unit` if `is_ms_struct` is true, which it never is.

**Comment by emilio** [comment]
is_ms_struct is MSVC-specific, fwiw.

**Comment by emilio** [comment]
(is supposed to be, that is)

**Comment by db48x** [comment]
Sure, but it's never set to true, which means that bindgen never takes the first branch there and thus never calls `flush_allocation_unit` until the very end, after all the fields have been examined. There should be a call to `flush_allocation_unit` on the other branch.

**Comment by db48x** [comment]
Either that, or this whole clause https://github.com/rust-lang-nursery/rust-bindgen/blob/master/src/ir/comp.rs#L609-L628 should happen outside the is_ms_struct check. I don't know how they should differ, if they should differ at all.

**Comment by db48x** [comment]
but not if `bitfield_width > unfilled_bits_in_unit`. If the current bitfield is too large to fit within the remaining bits in this unit, then we need a second unit.

Also, I just realized that the getter and setter for this bitfield will have to get some of the bits from the first unit and some from the second, which is annoying.

**Comment by emilio** [comment]
Not really, that's the point of it, the unit is just extended: https://github.com/llvm-mirror/clang/blob/d255642ff40bc63a1174e2332347ad46243fe3fc/lib/AST/RecordLayoutBuilder.cpp#L1600

**Comment by emilio** [comment]
I mean, you _can_ probably implement it as separate units, somehow, but then you got that problem, plus that alignment changes in the following units may affect previous units.

**Comment by db48x** [comment]
Oh, I see. The code this was copied from is using u32 fields (or something similar) when is_ms_struct, otherwise it just uses a single contiguous block of bits. Which doesn't quite work here.

**Comment by db48x** [comment]
ranweiler's option 3 sounds better and better

**Comment by dbeckwith** [comment]
Has there been any progress on this issue? I'm running into this now.

**Comment by emilio** [comment]
I don't think this is too hard to fix. We could use something like:

```css
unsafe { slice::from_raw_parts(&self.storage as *const u8, size_of::<Storage>()) }
```

Instead of `AsRef` (and making `BitfieldUnit::new` unsafe so it is clear that you cannot create them with random types, documenting it.

Somebody wants to submit such a patch? Otherwise I can try to get to it sometime next week or so :)

**Comment by pvdrz** [comment]
I'm closing this issue as I ran this example using rustc 1.57 (the minimum stable rust version for `bindgen`) and it runs.
