### ISSUE TITLE
Better warnings for types with the same name as rust types

### ISSUE THREAD

**Issue by akshayknarayan** [rust-lang/rust-bindgen#1382]
### Input C/C++ Header
See invocation below

### Bindgen Invocation

```Rust
    bindgen::builder()
        .header_contents("bug.h", "#include <stdint.h>\ntypedef uint64_t u64;")
        .generate()
        .unwrap()
```

### Actual Results

```
   Compiling bindgen-typedef-primitive v0.1.0 (file:///home/jon/dev/tmp/bindgen-typedef-primitive)
error[E0391]: cycle detected when processing `u64`
   --> /home/jon/dev/tmp/cargo-target/debug/build/bindgen-typedef-primitive-177200f3c53a8948/out/bindings.rs:193:16
    |
193 | pub type u64 = u64;
    |                ^^^
    |
    = note: ...which again requires processing `u64`, completing the cycle

error: aborting due to previous error
```

### Expected Results

This error message is rather confusing, especially when the header file for which bindings are being generated is large.
Rather, it would be nice if generating bindings for types which have the same name as rust types failed.

cc @jonhoo

**Comment by emilio** [comment]
We should probably just handle those types in `rust_mangle`, and ideally have a way to not have to list them there...

https://github.com/rust-lang-nursery/rust-bindgen/blob/8f8703f0122abef7be5fba33cbba629ddd1655c1/src/ir/context.rs#L841

Wanna submit a patch? :)

**Comment by aaaaeoglnr** [comment]
Hi, highfive, I would like to try and help with this.  @highfive: assign me , please.

**Comment by kellda** [comment]
Just thinking: could this be fixed by generating `core::primitive::u64` instead of just `u64` ?
