### ISSUE TITLE
Generate #[must_use] on functions annotated with __attribute__((warn_unused_result))

### ISSUE THREAD

**Issue by flowbish** [rust-lang/rust-bindgen#1450]
As annotating `#[must_use]` on functions was stabilized in 1.27, it should be possible to automatically carry the `__attribute__((warn_unused_result))` attribute from C/C++ into rust with `#[must_use]`. This will then require a `--rust-target` option of 1.27 to allow generation of this code.

### Input C/C++ Header

```C++
__attribute__((warn_unused_result))
int foo(int);

```

### Actual Results

```rust
extern "C" {
    pub fn foo(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
```

### Expected Results

```rust
extern "C" {
    #[must_use]
    pub fn foo(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
```

**Comment by emilio** [comment]
Fixed by #1451, thanks a lot @flowbish!
