### ISSUE TITLE
`#define S "...\n"` inconsistent with `static const char S[] = "...\n"`

### ISSUE THREAD

**Issue by reitermarkus** [rust-lang/rust-bindgen#1468]
I noticed that when converting a “string macro” containing an escaped newline, the output contains an escaped backslash instead of an escaped newline.

### Input C/C++ Header

```C
#define HELLO_WORLD_1 "Hello, world!\n"
static const char HELLO_WORLD_2[] = "Hello, world!\n";
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
pub const HELLO_WORLD_1: &'static [u8; 16usize] = b"Hello, world!\\n\0";
pub const HELLO_WORLD_2: &'static [u8; 15usize] = b"Hello, world!\n\0";
```

### Expected Results

```rust
pub const HELLO_WORLD_1: &'static [u8; 15usize] = b"Hello, world!\n\0";
pub const HELLO_WORLD_2: &'static [u8; 15usize] = b"Hello, world!\n\0";
```

**Comment by emilio** [comment]
Really sorry for the lag here, and thanks a lot for the report and the test-case.

Do you know if this is a regression?

**Comment by jethrogb** [comment]
> @jethrogb, I think cexpr is not unescaping C escape codes from the returned string, is that expected?

There is logic in cexpr's literal handling to deal with escaped characters, so I think this is a bug in cexpr.

**Comment by emilio** [comment]
Ok, let's close this. I opened https://github.com/jethrogb/rust-cexpr/issues/12 for this.

**Comment by jethrogb** [comment]
Should be fixed after a `cargo update -p cexpr`
