### ISSUE TITLE
Clippy does not like generated code

### ISSUE THREAD

**Issue by gmilleramilar** [rust-lang/rust-bindgen#1470]
I think its probably no surprise to anyone that clippy can generate a lot of warnings for bindgen-ed code.  I'm getting a lot of "Constants have by default a `'static` lifetime", and "long literal lacking separators".

Some of these are possibly changes to be made in the code generator, however I guess I have two questions:

1) Is there a policy on whether generated code should be clippy-lint free?  If not, now that clippy is available with the stable toolchain, maybe there should be.
2) In the meantine, is there a recommended setup to ignore clippy warnings in generated code?  The bindgen user guide recommends that you put something like `include!(concat!(env!("OUT_DIR"), "/bindings.rs"));` in your lib.rs.  The most straightforward approach would seem to be to simply add `#![allow(clippy::all)]` to lib.rs as well, but this has the unfortunate side effect of preventing clippy from linting any other code that is in lib.rs.

**Comment by Manishearth** [comment]
There should not be a policy about these things being lint free.

It may be worth outputting module level `allow(clippy::foo)` for known false positives though! That works without needing to `cfg_attr` now . We can also clean up stuff like the lifetime ones.

**Comment by emilio** [comment]
Ok, let's close this for now. Specific enhancements to the generated code are welcome of course :)

**Comment by jonvaldes** [comment]
I just ran into this issue from auto-generated code from the ispc crate, and I confirm this solution does indeed work to keep clippy quiet:

> ```rust
> #[allow(clippy::all)]
> mod bindings {
>     include!(..);
> }
> pub use bindings::*;
> ```
