### ISSUE TITLE
src/ir/analysis/*.rs not included in the cargo.toml

### ISSUE THREAD

**Issue by 22shubh22** [rust-lang/rust-bindgen#1487]
`[package]
include = [
  "LICENSE",
  "README.md",
  "Cargo.toml",
  "build.rs",
  "src/*.rs",
  "src/**/*.rs",
]`

The code contained in the analysis directory is not included in the crate. Maybe this could help resolve #1285.

**Comment by emilio** [comment]
How is this related to #1285?

**Comment by 22shubh22** [comment]
Sorry, I have made an assumption here since #1285 talks about derives, and so the code in the directory.

**Comment by emilio** [comment]
Also, the files are definitely included, in the `src/**/*.rs` line (the double asterisk means both directories and subdirectories).

Otherwise you wouldn't be able to build with `cargo install bindgen`.

So I think this issue is invalid.
