### ISSUE TITLE
Split codegen portion into separate crate?

### ISSUE THREAD

**Issue by estk** [rust-lang/rust-bindgen#1497]
Hi bindgen peeps,
I've been working on a project that requires a bit of code generation and was wondering why the code-generation portion of this project has not been split off into its own crate. There are only a few code generation crates at the moment and they have a much smaller userbase than bindgen, so I'm inclined to trust them less.
Thanks!

**Comment by emilio** [comment]
What kind of code generation you need? Bindgen basically just forwards to [`quote`](https://docs.rs/quote/) all the hard work of emitting rust code. It mostly translates an internal representation of the C structs into Rust.

**Comment by estk** [comment]
@emilio thanks for the lightning fast response! I'm working on code generation for IDL like things, xml schema, json schema, avro, etc. It would be nice to have a builder style api layer between the schema layer and actually generating rust code. Maybe thats something that is just near trivial to build? I'm not sure as I haven't explored the space much yet.

**Comment by estk** [comment]
Oh wow, that is so cool to see how bindgen was with the builder method.

I really appreciate the nudge in the right direction, saved me many hours of frustration. After a second look at `quote` and how bindgen uses it, I think I'm all set. I'll give you a holler if I have another question but feel free to close this, its been massively helpful.

**Comment by emilio** [comment]
Alright, sounds good! Let me know if I can help more :)
