### ISSUE TITLE
Bindgen gets bindings for function pointer as return-type wrong.

### ISSUE THREAD

**Issue by bobbobbio** [rust-lang/rust-bindgen#1500]
### Input C Header

```C
int (^my_function(void))(int, int);
```

### Bindgen Invocation

$ bindgen foo.h

### Actual Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    pub fn my_function() -> ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>;
}

```

### Expected Results

Bindgen gets the arguments to the function pointer incorrect. I expect it to get it correct. This problems also extends to clang-block, perhaps unsurprisingly. Weirdly, if I put the return-type behind a typedef, the problem seems to go away.

**Comment by emilio** [comment]
Fixed by #1508. Thanks @flowbish!
