### ISSUE TITLE
Bindgen outputs warnings in generated bindings file

### ISSUE THREAD

**Issue by ennis** [rust-lang/rust-bindgen#1502]
### Input C/C++ Header

```C++
// empty
```

### Bindgen Invocation

```
$ RUST_LOG="xxx=xxx" bindgen -o bindings.rs .\test.h
```

### Command-line output

```
warning: invalid logging spec 'xxx', ignoring it
```

### Generated bindings 

```rust
/* automatically generated by rust-bindgen */

warning: invalid logging spec 'xxx', ignoring it
```

### Expected Results
The warnings emitted by the logging system (log or env_logger?) should not appear in the generated rust bindings.

### Notes
The bug happens on windows. I could not test it under linux or others.
The same issue happens when generating bindings to the standard output, or within build.rs

**Comment by emilio** [comment]
Thanks, I can repro this. This seems to be a problem with rustfmt or our rustfmt integration, as I cannot repro with `--no-rustfmt-bindings`.

**Comment by emilio** [comment]
Actually it seems to be specific to the logger warning.... If I do something like:

```
diff --git a/src/lib.rs b/src/lib.rs
index c24af26c..4d16048e 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1866,6 +1866,9 @@ impl Bindings {
             }
         };
 
+        println!("Foo bar");
+        eprintln!("Foo bar baz");
+
         let mut cmd = Command::new(&*rustfmt);
 
         cmd
```

They don't appear on the output of rustfmt. So I'm really confused now I think rustfmt is messing up somehow.

**Comment by emilio** [comment]
Yeah, this belongs in rustfmt.

```
$ export RUST_LOG="xxx=xxx"
$ echo "fn main () { }" | rustfmt > out
$ cat out
warning: invalid logging spec 'xxx', ignoring it
fn main() {}
```

**Comment by emilio** [comment]
I chased this down to https://github.com/sebasmagri/env_logger/pull/126. Closing as not a bindgen bug.
