### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by wellorange** [rust-lang/rust-bindgen#1510]
hello.I am using leveleb to test this project, I have encountered such a problem, I can do it in g++ environment.

--- stdout
cargo:rustc-link-lib=/home/orange/work/rust/material/main/cpprust/libleveldb.a

--- stderr
/usr/include/leveldb/slice.h:21:10: fatal error: 'string' file not found
/usr/include/leveldb/slice.h:21:10: fatal error: 'string' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by wellorange** [comment]
Yes, I added x, I have a question.

For (https://github.com/rust-lang/rust-bindgen/blob/master/bindgen-integration/build.rs)
I compiled Test.cc into a static library in advance, and then changed it to something like this.

     // use std::fs;
     // let v = vec!["cpp/Test.cc"];
     // let mut iter = v.into_iter();
     // cc::Build::new()
     // .cpp(true)
     // .files(iter)
     // .compile("libtest.a");
   
     Println!("cargo:rustc-link-search=native={}","/home/orange/work/rust/material/main/cpp/cpp");
    
     Let library_test = "test";
     Println!("cargo:rustc-link-lib=static={}", library_test);

thank you very much

**Comment by wellorange** [comment]
I use  rocksdb test: 
  println!("cargo:rustc-link-search=native={}/dependences",current_dir_name);
    println!("cargo:rustc-link-lib=static=rocksdb");
    println!("cargo:rustc-link-lib=stdc++");
    println!("cargo:rustc-link-lib=pthread"); 
    println!("cargo:rustc-link-lib=snappy"); 
    println!("cargo:rustc-link-lib=rt"); 
    println!("cargo:rustc-link-lib=gflags"); 
    println!("cargo:rustc-link-lib=z"); 
    println!("cargo:rustc-link-lib=bz2"); 
    println!("cargo:rustc-link-lib=lz4"); 
    println!("cargo:rustc-link-lib=zstd"); 
    
    let bindings = bindgen::Builder::default()
        .header("dependences/wrapper.h")
        .clang_args(&["-x"])
        .generate()
        .expect("Unable to generate bindings");

let out_path = PathBuf::from("src");
  bindings
    .write_to_file(out_path.join("bindings.rs"))
    .expect("Couldn't write bindings!");



wraper.h
  #include "rocksdb/db.h"
  #include "rocksdb/slice.h"
  #include "rocksdb/options.h"

**Comment by emilio** [comment]
That sounds like #1464, see there for workarounds.

**Comment by emilio** [comment]
I think  this should be working now since #1464 is fixed, let me know otherwise.
