### ISSUE TITLE
Generated code for inner class of template-class doesn't use type-parameter

### ISSUE THREAD

**Issue by karroffel** [rust-lang/rust-bindgen#1514]
While trying to generate bindings for a bigger file I encountered a Rust-compile error when compiling the binding code.

The generated code generally looks good, the only problem is that a type parameter for a generated struct is not applied.

Inside a template class I defined two inner-classes. Since the template parameters applies to inner items as well, the inner classes are not explicitly parameterized.

The problem occurs when one inner class inherits the other (which makes use of the template arg).

### Input C/C++ Header

```C++
template<typename T>
struct Thing {
    struct Inner {
        T *ptr;
    };

    struct AnotherInner : Inner {
    };
};
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("test.hpp")
    .generate()
    .unwrap()
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Thing {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Thing_Inner<T> {
    pub ptr: *mut T,
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Thing_AnotherInner<T> {
    pub _base: Thing_Inner,
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
}
```

Compile error:

```
error[E0107]: wrong number of type arguments: expected 1, found 0
  --> ...project/target/debug/build/the-project-8f7347729392ec63/out/bindings.rs:17:16
   |
17 |     pub _base: Thing_Inner,
   |                ^^^^^^^^^^^ expected 1 type argument

error: aborting due to previous error
```

### Expected Results

The field `_base` of the `Thing_AnotherInner` should have the type parameter applied.

When manually changing line 17 to `pub _base: Thing_Inner<T>,` it compiles fine.

**Comment by emilio** [comment]
Ah, nice catch, this should be easy enough to fix :)

**Comment by emilio** [comment]
Also, thanks so much for the reduced test-case!
