### ISSUE TITLE
#[must_use] is not applied to functions when __attribute((warn_unused_result)) is used through a macro defined in an included file.

### ISSUE THREAD

**Issue by flowbish** [rust-lang/rust-bindgen#1518]
### Input C/C++ Header
warn_unused_result.h:

```C++
#define a_warn_unused_result __attribute__((warn_unused_result))
```

input.h:

```C++
#include "warn_unused_result.h"

int
must_be_used(void)
    a_warn_unused_result;
```

### Bindgen Invocation

```
$ bindgen input.h --rust-target 1.27 --enable-function-attribute-detection
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    pub fn must_be_used() -> ::std::os::raw::c_int;
}
```

### Expected Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    #[must_use]
    pub fn must_be_used() -> ::std::os::raw::c_int;
}
```

Curiously, if that macro definition exists in the same file, the function is generated correctly.

**Comment by emilio** [comment]
This is quite tricky actually... I would've expected clang to expose the same AST, is that not the case?

**Comment by emilio** [comment]
I submitted https://reviews.llvm.org/D58570 to properly detect the attribute instead of hackily doing so.

**Comment by elichai** [comment]
Any news?

**Comment by emilio** [comment]
I think libclang 9 + bindgen trunk should work.

**Comment by Wallacoloo** [comment]
This seems to be working with bindgen-0.52.0 and clang-9.0.0 :-)

**Comment by emilio** [comment]
Thanks for checking!
