### ISSUE TITLE
not clear how to produce debug output

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust-bindgen#1522]
`RUST_LOG=all cargo test some_bindgen_test -- --nocapture` does not dump debug output. I can't find in the readme or the user guide or the issue template how to enable logging for bindgen. 

How to enable debug output should be documented somewhere, or ideally it should "just work" for tests.

**Comment by emilio** [comment]
Generally I just run the test manually with `./target/debug/bindgen` if I want debug output. I'm not sure if you can add some sort of hook before running all tests, but if you can fixing this should be a matter of calling `env_logger::init()` there or something.

**Comment by cbourjau** [comment]
Might this be related to this issue: https://github.com/rust-lang/rust/issues/40298 ?

**Comment by emilio** [comment]
@jethrogb enabled logging in the test-suite in #1540.
