### ISSUE TITLE
error: 'asm goto' constructs are not 

### ISSUE THREAD

**Issue by flip111** [rust-lang/rust-bindgen#1534]
I'm getting the following errors

```
/usr/include/php/20180731/Zend/zend_operators.h:486:10: error: 'asm goto' constructs are not supported yet
/usr/include/php/20180731/Zend/zend_operators.h:536:10: error: 'asm goto' constructs are not supported yet
/usr/include/php/20180731/Zend/zend_operators.h:593:10: error: 'asm goto' constructs are not supported yet
/usr/include/php/20180731/Zend/zend_operators.h:683:10: error: 'asm goto' constructs are not supported yet
/usr/include/php/20180731/Zend/zend_operators.h:486:10: error: 'asm goto' constructs are not supported yet, err: true
/usr/include/php/20180731/Zend/zend_operators.h:536:10: error: 'asm goto' constructs are not supported yet, err: true
/usr/include/php/20180731/Zend/zend_operators.h:593:10: error: 'asm goto' constructs are not supported yet, err: true
/usr/include/php/20180731/Zend/zend_operators.h:683:10: error: 'asm goto' constructs are not supported yet, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:997:5
```

This points to https://github.com/php/php-src/blob/PHP-7.3.3/Zend/zend_operators.h#L486

Is there any way to workaround this issue?

**Comment by emilio** [comment]
Yes, looks like your clang version doesn't support those, but you're trying to generate bindings for a PHP build built (presumably) with GCC?

You can maybe hack around it by using `clang_flags("-UHAVE_ASM_GOTO")`, if you need to. Another probably cleaner approach is just configure PHP with clang so that it doesn't have that flag defined to begin with.

**Comment by emilio** [comment]
I don't think we can do much here given bindgen's dependence on libclang and the fact that clang doesn't support `asm goto`.

Let me know if for some reason any of the above suggestions do not work, and if you provide some STR I'm happy to take a look at this.

**Comment by SOF3** [comment]
> You can maybe hack around it by using clang_flags("-UHAVE_ASM_GOTO"), if you need to.

What does this mean? Does this mean calling `.clang_arg("-UHAVE_ASM_GOTO")` on the bindgen::Builder? I am still getting this error even after passing the argument.

**Comment by wizzwizz4** [comment]
@emilio The above suggestion did not work for me, though it was the "obvious" solution; I had the following already in my code:

    bindgen::Builder::default()
        .clang_args(php_include_flags)
        .clang_arg("-UHAVE_ASM_GOTO")
        .header("wrapper.h")

Using Clang 9 should solve this problem, but that'll involve installing stuff from outside my distro.
