### ISSUE TITLE
When --target is specified in clang flags, things can fail badly

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust-bindgen#1542]
The bindgen code contains the following comment:
```
        // If --target is specified, assume caller knows what they're doing and
        // don't mess with
        // include paths for them
```
and the code acts accordingly.

Well, unfortunately, there are perfectly fine combinations of clang flags with --target that work with clang, but that bindgen fails with.

One recent occurrence I got make Firefox build fail with:
```
builds/worker/workspace/build/src/obj-firefox/dist/include/mozilla/Compiler.h:49:12: fatal error: 'cstddef' file not found
```

I'm suspecting cases I've had in the past where bindgen would pick the wrong intrin.h on Windows could be related to this too (it would pick msvc's instead of clang's like clang would do with the same flags).

For the `cstddef` issue above, the value of `clang_args` in `BindgenContext` is:
```
["-x", "c++", "-std=gnu++14", "-fno-sized-deallocation", "-DRUST_BINDGEN", "-I../..", "-x", "c++", "-fno-sized-deallocation", "-DTRACING=1", "-DIMPL_LIBXUL", "-DMOZILLA_INTERNAL_API", "-DRUST_BINDGEN", "-DOS_POSIX=1", "-DOS_MACOSX=1", "-stdlib=libc++", "--target=x86_64-darwin11", "-isysroot", "/builds/worker/workspace/build/src/MacOSX10.11.sdk", "-I/builds/worker/workspace/build/src/obj-firefox/dist/include/nspr", "baldrapi.h"]
```

And if I remove the `if !has_target_arg` in `lib.rs`, the value is:
```
["-x", "c++", "-std=gnu++14", "-fno-sized-deallocation", "-DRUST_BINDGEN", "-I../..", "-x", "c++", "-fno-sized-deallocation", "-DTRACING=1", "-DIMPL_LIBXUL", "-DMOZILLA_INTERNAL_API", "-DRUST_BINDGEN", "-DOS_POSIX=1", "-DOS_MACOSX=1", "-stdlib=libc++", "--target=x86_64-darwin11", "-isysroot", "/builds/worker/workspace/build/src/MacOSX10.11.sdk", "-I/builds/worker/workspace/build/src/obj-firefox/dist/include/nspr", "-isystem", "/builds/worker/workspace/build/src/clang/bin/../include/c++/v1", "-isystem", "/builds/worker/workspace/build/src/clang/lib/clang/8.0.0/include", "-isystem", "/builds/worker/workspace/build/src/MacOSX10.11.sdk/usr/include", "-isystem", "/builds/worker/workspace/build/src/MacOSX10.11.sdk/System/Library/Frameworks", "baldrapi.h"]
```

Needless to say, I should have to add those `-isystem` manually.

**Comment by glandium** [comment]
Another case I had recently is described in the commit message of https://hg.mozilla.org/integration/autoland/rev/649fc91aa4d3 .

**Comment by emilio** [comment]
I can add an option to do the include path changes regardless of the `--target` argument. IIRC this was added because people were having a lot of trouble cross-compiling, but if it's causing more pain than not then...
