### ISSUE TITLE
The default settings for a `Builder` are very unclear

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-bindgen#1550]
You can find out what the default for each setting is if you go source diving through the project, but just looking at the main parts of docs.rs it's very unclear what the defaults are.

**Comment by emilio** [comment]
Agreed, I wish I could have more time to write docs. If you (or anybody else) helped to improve them I'd be really grateful.

**Comment by kellda** [comment]
I found that default settings are here in source code: https://github.com/rust-lang/rust-bindgen/blob/master/src/lib.rs#L1886-L1957. However I'm not sure where to include this in the docs...

**Comment by pvdrz** [comment]
This PR https://github.com/rust-lang/rust-bindgen/pull/2473 should ease this in some way as the fields, default values and methods are kept in the same block of code. Which means it is more evident if you forget to document the default value of an option.
