### ISSUE TITLE
bindgen generates union with u128 member for alignment which is UB for FFI

### ISSUE THREAD

**Issue by benpye** [rust-lang/rust-bindgen#1560]
### Input C/C++ Header

```C
typedef union __declspec(align(16)) TestUnion
{
    unsigned long Longs[2];
    unsigned int  Ints[4];
} TestUnion;
```

### Bindgen Invocation

```
bindgen .\test.h -o test.rs
```

### Actual Results

```rust
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union TestUnion {
    pub Longs: [::std::os::raw::c_ulong; 2usize],
    pub Ints: [::std::os::raw::c_uint; 4usize],
    _bindgen_union_align: u128,
}
```

### Expected Results

I believe the `u128` member of the union is unnessecary and actually triggers a warning (improper_ctypes) as `u128`s are not stable across the FFI boundary. My understanding here is that `#[repr(align(16))]` is sufficient to ensure the correct alignment for this union.

**Comment by emilio** [comment]
You're right. This should be trivial to fix. Relevant code is:

https://github.com/rust-lang/rust-bindgen/blob/b7e5d8d4d511066d0363ef72dbee2c66615b8dd4/src/codegen/mod.rs#L1601

**Comment by unterkontrolle** [comment]
@emilio Would this be the desired behavior?

*  **If the Rust version is => 1.25:** always use #[repr(align(n))]
*  **If the Rust version is < 1.25:** align up the struct size by adding fields to it, as long as these are stable across FFI boundaries.

**Comment by emilio** [comment]
Yes, that's right, though it's even simpler, given support for repr(align) predates support for u128 / i128. So we should just not generate that alignment field if repr(align) is supported, and add a test.

**Comment by unterkontrolle** [comment]
Some tests _could_ break after implementing this, but I think that's ok because those tests cases would not be 100% correct in the first place anyway. I guess the right thing would be to just update the tests.

**Comment by randomairborne** [comment]
it seems this still isn't fixed, is there a workaround for now

**Comment by pvdrz** [comment]
I'm fixing this
