### ISSUE TITLE
repr(align(0)) for std::basic_string causing build error

### ISSUE THREAD

**Issue by bengl** [rust-lang/rust-bindgen#1565]
### Input C/C++ Header

```C++
#include <string>
using namespace std;
basic_string<char> simple(basic_string<char> str);
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("simple.hpp")
    .clang_arg("-x")
    .clang_arg("c++")
    .opaque_type("std::.*")
    .whitelist_function("simple")
    .generate()
    .unwrap()
```

### Actual Results

Generating the binding.rs works fine, but when compiling....
```
cargo build
  Compiling simple-bindgen v0.1.0 (simple-bindgen)
error[E0589]: invalid `repr(align)` attribute: not a power of two
 --> simple-bindgen/target/debug/build/simple-bindgen-0af4d98c1d10abb2/out/bindings.rs:73:8
  |
73 | #[repr(align(0))]
  |        ^^^^^^^^

error[E0589]: invalid `repr(align)` attribute: not a power of two
 --> simple-bindgen/target/debug/build/simple-bindgen-0af4d98c1d10abb2/out/bindings.rs:90:8
  |
90 | #[repr(align(0))]
  |        ^^^^^^^^
```
The offending lines in the binding.rs look like:

```rust
#[repr(C)]
#[repr(align(0))]
pub union std_basic_string___ulx {
    pub _bindgen_opaque_blob: [u8; 0usize],
}
```

and

```rust
#[repr(C)]
#[repr(align(0))]
pub union std_basic_string___rep__bindgen_ty_1 {
    pub _bindgen_opaque_blob: [u8; 0usize],
}
```

### Expected Results

While this works just fine on our linux machines, on our Macs, we get the error provided. Here's a sample `uname -a` from one of our Macs:

```
Darwin computer.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

**Comment by emilio** [comment]
Is there any chance to [provide a test-case](https://github.com/rust-lang/rust-bindgen/blob/master/CONTRIBUTING.md#isolating-your-test-case)? Presumably we should be just `min(align, 1)` or such, but I'd rather land the fix with a test that reproduces the issue.

**Comment by bengl** [comment]
Here's a `__bindgen.ii` file (zipped to appease github).
[__bindgen.ii.zip](https://github.com/rust-lang/rust-bindgen/files/3204080/__bindgen.ii.zip)

**Comment by pmarks** [comment]
Bump. I'm also hitting this on Mac for a library that refers to std::string. Would a smaller test case help?

**Comment by emilio** [comment]
Yes, for sure. creducing this would be awesome.

**Comment by emilio** [comment]
This is not fixed per https://github.com/rust-lang/rust-bindgen/pull/1593, which has a more complex test-case.
