### ISSUE TITLE
Bindgen fails on Travis CI: unknown type name 'size_t'

### ISSUE THREAD

**Issue by Wenzel** [rust-lang/rust-bindgen#1577]
Hi,

I'm facing an issue while generating bindings for xenstore.h for Xen hypervisor, on Ubuntu 16.04, on Travis CI:
https://travis-ci.org/Wenzel/xenstore-sys/jobs/544869966#L325

It works fine on my local environment, Fedora 30.

### Input C/C++ Header

see [Gist](https://gist.github.com/Wenzel/134fbf1b604a9e7478039c034fa78961)

### Bindgen Invocation

I built a Dockerfile to reproduce the bug:
~~~Dockerfile
FROM ubuntu:xenial

RUN apt-get update && apt-get install -y clang-6.0 libxen-dev cargo
RUN cargo install bindgen
CMD ["/root/.cargo/bin/bindgen", "/usr/include/xenstore.h"]
~~~

```
/root/.cargo/bin/bindgen /usr/include/xenstore.h
```

### Actual Results

```
root@caa4ce0c071a:~/xenstore-sys# /root/.cargo/bin/bindgen /usr/include/xenstore.h --dump-preprocessed-input
/usr/include/xenstore_lib.h:64:38: error: unknown type name 'size_t'
/usr/include/xenstore_lib.h:64:38: error: unknown type name 'size_t', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: bindgen::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
  17: __libc_start_main
  18: _start
```

### Expected Results

I don't understand the error message, on Travis it says that `size_t` is unknown.

Thanks !

**Comment by emilio** [comment]
It seems like xenstore_sys may be relying on a header that it's not included by default in every distro.

Does it work if you `#include <stddef.h>` in your wrapper.h?

**Comment by Wenzel** [comment]
@emilio I just included `stddef.h` above `xenstore.h`, and compiled in my Docker container, it works.

What does this mean ?

**Comment by emilio** [comment]
It means that `xenstore.h` is missing an include (i.e., it's using `size_t` without including the header that defines it).

It's an issue with the C library, not with bindgen :)
