### ISSUE TITLE
Generated bindings are not formatted: Failed to run rustfmt

### ISSUE THREAD

**Issue by Wenzel** [rust-lang/rust-bindgen#1586]
# Input C/C++ Header

[xencltr_bindgen.i](https://gist.github.com/Wenzel/43c412549b0fddbb4878905eccb3f7df)

### Bindgen Invocation

![Screenshot_20190629_154628](https://user-images.githubusercontent.com/964610/60385034-14b14300-9a85-11e9-8620-af036a169c54.png)

### Actual Results

Rustfmt failed with a non-fatal error, but the bindings are not formatted.

### Expected Results

Even though Rustfmt failed, the error was non-fatal, so the bindings should have been formatted with minor errors.

But the generated bindings are on one line, unreadable:
![Screenshot_20190629_154818](https://user-images.githubusercontent.com/964610/60385045-5e019280-9a85-11e9-9c17-449c38519fa0.png)

I looked at the command line, and `rustfmt` is now the default behavior, so something is wrong here.
![Screenshot_20190629_154220](https://user-images.githubusercontent.com/964610/60385061-75d91680-9a85-11e9-8960-f9a83cde7943.png)

Note: using `bindgen  v0.49.3`

Thanks for your help !

**Comment by emilio** [comment]
Here rustfmt failed with a fatal error (probably, unless rustfmt changed status codes or added new codes). That error message is printed by bindgen, not rustfmt.

I'd be curious about what happened though. You're hitting this code path:

https://github.com/rust-lang/rust-bindgen/blob/dbe5bab3e8aec87051b91537c71f47f8bcbccb78/src/lib.rs#L1976

Is there any chance you could build bindgen with an extra println! there or what not to figure out what did rustfmt output, and why did it fail?

**Comment by emilio** [comment]
A PR to change that error message to something that makes clear that it is `bindgen` what's continuing even though we failed to run rustfmt, would also be amazing :)

**Comment by Wenzel** [comment]
Hi @emilio,

> Is there any chance you could build bindgen with an extra println! there or what not to figure out what did rustfmt output, and why did it fail?

I can report errors when I use bindgen, but i would rather getting involved in bindgen development.
I just don't have time for this.

I can give you a Dockerfile to reproduce the bug though.
If you are on Ubuntu, just install `libxen-dev` and the header will be at `/usr/include/xenctrl.h`

Thanks !

**Comment by emilio** [comment]
Sure, the issue in this case is unfortunately not distro or header-dependent, but rather rustfmt-setup-dependent.

Does bindgen rustfmt stuff correctly when ran on a simpler header?

**Comment by emilio** [comment]
And that's fair, I appreciate people taking time to report issues ^.^

**Comment by Wenzel** [comment]
> Does bindgen rustfmt stuff correctly when ran on a simpler header?

I don't know what a simple header is, but I tested a couple of them, and the format failure is still there
![Screenshot_20190703_205414](https://user-images.githubusercontent.com/964610/60617802-cbd6f280-9dd4-11e9-93a5-07d56807b34d.png)

Thanks @emilio !

**Comment by emilio** [comment]
I meant something like:

```
echo "struct Foo { int bar; };" > test.h
bindgen test.h
```

If that still shows the error, it's a failure in your setup, do you have rustfmt installed? Does running `rustup component add rustfmt-preview` help?

**Comment by Wenzel** [comment]
Regarding the small test
![Screenshot_20190707_123741](https://user-images.githubusercontent.com/964610/60767189-83f5eb00-a0b4-11e9-9fbc-7066a0619ada.png)

I'm not using `rustup`, but Fedora packages.
But even with that, it says that my version of `rustfmt` is deprecrated:
![Screenshot_20190707_124100](https://user-images.githubusercontent.com/964610/60767201-996b1500-a0b4-11e9-9523-27771e546b33.png)

But i have `1.35` installed, isn't it recent enough ?? :thinking: 

Thanks @emilio

**Comment by emilio** [comment]
Ah, ok. I suspect no, it's not rececent enough. I don't remember the details on the `rustfmt` versioning shenanigans... but it seems this is an issue to report to the Fedora packagers, or maybe to ping a rustfmt maintainer about to get some clarity.

I'm still happy to help should I be able to. Closing the issue as not a bindgen bug but let me know / reopen if you disagree.
