### ISSUE TITLE
bindgen should use the RUSTFMT environment variable if it wasn't set with with_rustfmt

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust-bindgen#1601]
It seems absurd that every single build script that depends on bindgen and doesn't disable rustfmt has to handle getting the environment variable and use with_rustfmt on its own. The net result is that in Firefox, only stylo uses the RUSTFMT environment variable, and baldrdash, coreaudio-sys and js all ignore it.

**Comment by emilio** [comment]
Sure, that's fair. Should be a pretty easy change.
