### ISSUE TITLE
Support for DECLSPEC_ALIGN in Windows headers

### ISSUE THREAD

**Issue by Wenzel** [rust-lang/rust-bindgen#1604]
# Input C/C++ Header

```C++
#if !defined(_HVGDK_)
#define _HVGDK_

#include <emmintrin.h>  

#if _MSC_VER > 1000
#pragma once
#endif

#if _MSC_VER >= 1200
#pragma warning(push)
#endif

#pragma warning(disable:4200) // zero length array
#pragma warning(disable:4201) // nameless struct/union
#pragma warning(disable:4214) // bit field types other than int
#pragma warning(disable:4324) // structure was padded due to __declspec(align())


//
// Define a 128bit type.
//
typedef struct DECLSPEC_ALIGN(16) _HV_UINT128 {

    UINT64  Low64;
    UINT64  High64;

} HV_UINT128, *PHV_UINT128;
```

### Bindgen Invocation

![Screenshot_20190728_132713](https://user-images.githubusercontent.com/964610/62006009-6cea6c00-b13b-11e9-81c9-f7eb8311fcd0.png)

### Actual Results

```
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
```

### Expected Results

Bindgen shouldn't have emited warnings for this declaration.

Do you know more about this `DECLSPEC_ALIGN` ?
https://docs.microsoft.com/fr-fr/cpp/cpp/align-cpp?view=vs-2019

I would like to generate bindings for `Hyper-V`.

You can find the full header [here](https://github.com/gerhart01/LiveCloudKd/blob/master/LiveCloudKdSdk/public/HyperV/hvgdk.h)

Thanks @emilio !

**Comment by emilio** [comment]
This works if invoked using the right clang flags.

Header:

```c
//
// Define a 128bit type.
//
typedef struct __declspec(align(16)) _HV_UINT128 {
    long int Low64;
    long int High64;
} HV_UINT128, *PHV_UINT128;
```

Output:

```rust
$ ./target/debug/bindgen t.c -- --target=i686-pc-windows-msvc                                                                                                                                                                              
Warning: Unknown configuration option `where_trailing_comma`
Warning: can't set `normalize_comments = false`, unstable features are only available in nightly channel.
Warning: can't set `struct_lit_single_line = false`, unstable features are only available in nightly channel.
Warning: can't set `brace_style = SameLineWhere`, unstable features are only available in nightly channel.
/* automatically generated by rust-bindgen */

#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct _HV_UINT128 {
    pub Low64: ::std::os::raw::c_long,
    pub High64: ::std::os::raw::c_long,
    pub __bindgen_padding_0: [u32; 2usize],
}
#[test]
fn bindgen_test_layout__HV_UINT128() {
    assert_eq!(
        ::std::mem::size_of::<_HV_UINT128>(),
        16usize,
        concat!("Size of: ", stringify!(_HV_UINT128))
    );
    assert_eq!(
        ::std::mem::align_of::<_HV_UINT128>(),
        16usize,
        concat!("Alignment of ", stringify!(_HV_UINT128))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_HV_UINT128>())).Low64 as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_HV_UINT128),
            "::",
            stringify!(Low64)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_HV_UINT128>())).High64 as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_HV_UINT128),
            "::",
            stringify!(High64)
        )
    );
}
pub type HV_UINT128 = _HV_UINT128;
pub type PHV_UINT128 = *mut _HV_UINT128;
```

So it seems you need to pass the right clang target that you're using to compile your C code. Does fixing that work?

**Comment by Wenzel** [comment]
Hi @emilio and thanks for the quick feedback.

I did some experimentations with the `target` argument, and curiously, it works when I run it on Linux:
![Screenshot_20190730_000519](https://user-images.githubusercontent.com/964610/62086217-ed08f280-b25d-11e9-8f59-a95eda0f3f3d.png)

But it doesn't work anymore when I try the same command on Windows:
![Sans titre](https://user-images.githubusercontent.com/964610/62086244-0611a380-b25e-11e9-8ce5-955acff43a35.png)

I looked at your documentation and updated my `build.rs` to include this clang argument:
https://github.com/Wenzel/hyper-v-sys/blob/master/build.rs#L19

~~~Rust
        // The input header we would like to generate
        // bindings for.
        .header("src/wrapper.h")
        // specify Clang target
        .clang_arg("--target=x86_64-pc-windows-msvc")
        // Finish the builder and generate the bindings.
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");
~~~

I don't understand what's happening here, i should ask on the clang mailing list maybe ?
I'm running `LLVM 7.1.0` on Windows:
https://github.com/llvm/llvm-project/releases/download/llvmorg-7.1.0/LLVM-7.1.0-win64.exe

And `LLVM 8.0.0` on Linux.

Thanks, we are getting closer to solve this issue.

**Comment by emilio** [comment]
Well, both of those don't seem to work. You're missing cross-compilation headers on Linux, and it seems there are missing headers on Windows as well.

You need to understand how the C code is supposed to be compiled, and ensure you pass the same flags to bindgen. It seems like https://github.com/gerhart01/LiveCloudKd/blob/master/LiveCloudKdSdk/public/HyperV/hvgdk.h is a msvc-specific header (due to the `#pragma`s)...

**Comment by Wenzel** [comment]
> This works if invoked using the right clang flags.

Apparently you modified the source too to make it work with Clang:
~~~C
typedef struct __declspec(align(16)) _HV_UINT128 {
~~~

So should I asumme that `DECLSPEC_ALIGN` isn't supported by Clang yet ?
Should discuss this on the mailing list ?

In the meantime, I replaced the `DECLSPEC_ALIGN` declarations by `__declspec(align())`, and the bindings are generated.

But they are not formatted, event though I explicitely specified `.rustfmt_bindings(true)` in `build.rs` ... ? :thinking: 

Thanks.

**Comment by emilio** [comment]
Seems like that macro is just defined to be something like this:

https://github.com/Alexpux/mingw-w64/blob/d0d7f784833bbb0b2d279310ddc6afb52fe47a46/mingw-w64-tools/widl/include/winnt.h#L68

So either the header that defines it is not included, or it comes pre-defined by msvc, which would be a bit weird. Adding the definition before including that header would fix that.

Glad you solved your issue, I'll close this since I think there's no bindgen change needed here, but please reopen if I got it wrong :)

**Comment by Wenzel** [comment]
Good catch !
> Adding the definition before including that header would fix t

Will do :)

Thanks for your help :+1:
