### ISSUE TITLE
How bindgen controls the order of generation

### ISSUE THREAD

**Issue by hunterlxt** [rust-lang/rust-bindgen#1605]
### Bindgen Invocation

```Rust
fn bindgen_grpc(mut config: bindgen::Builder, file_path: &PathBuf) {
    // Search header files with API interface
    for result in WalkDir::new(Path::new("./grpc/include")) {
        let dent = result.expect("Error happened when search headers");
        if !dent.file_type().is_file() {
            continue;
        }
        let mut file = fs::File::open(dent.path()).expect("couldn't open headers");
        let mut buf = String::new();
        file.read_to_string(&mut buf)
            .expect("Coundn't read header content");
        if buf.contains("GRPCAPI") || buf.contains("GPRAPI") {
            config = config.header(dent.path().to_str().unwrap());
        }
    }

    config
        .header("grpc_wrap.cc")
        .clang_arg("-xc++")
        .clang_arg("-I./grpc/include")
        .clang_arg("-std=c++11")
        .whitelist_function(r"\bgrpc_.*")
        .whitelist_function(r"\bgpr_.*")
        .whitelist_function(r"\bgrpcwrap_.*")
        .whitelist_var(r"\bGRPC_.*")
        .default_enum_style(bindgen::EnumVariation::Rust {
            non_exhaustive: false,
        })
        .constified_enum_module(r"grpc_status_code")
        .no_copy("grpc_slice")
        .generate()
        .expect("Unable to generate grpc bindings")
        .write_to_file(file_path)
        .expect("Couldn't write bindings!");
}
```

### Actual Results

Inconsistent file order generated by different machines. But the total number of lines is the same.

### Expected Results

I want to execute a build script on Travis to make sure the committer does generate the bindings before committing the PR. The actual situation is that although the files are roughly the same, the order is inconsistent.

**Comment by emilio** [comment]
Huh, interesting... For the exact same input, the output should be always the same.

Probably system headers are at fault somehow here... If you call `builder.dump_preprocessed_input()` and take the generated `.ii` file, do you have the same input? If not, how does it differ?

**Comment by hunterlxt** [comment]
I have found that the problem is in the `walkdir` not in `bindgen`. If I sort the headers, the order will be the same. Thanks for giving help.

**Comment by emilio** [comment]
Cool, thanks! Yeah, having deterministic output is important for bindgen, for the build.rs case, so if that wouldn't be working I'd be surprised / I'd love to dig more.
