### ISSUE TITLE
Clippy and const and &'static references

### ISSUE THREAD

**Issue by martinthomson** [rust-lang/rust-bindgen#1612]
### Input C/C++ Header

```C++
#define X "string"
```

### Bindgen Invocation

I don't think that I've tweaked anything here.

### Actual Results

```rust
pub const X: &'static [u8; 2usize] = b"string\0";
```

This results in warnings from clippy when compiled with `#![deny(warnings)]`.  The use of `&'static` trips `clippy::redundant_static_lifetimes`.

### Expected Results

As explained in the lint, the use of `&'static` is redundant and can be removed.

**Comment by Lokathor** [comment]
I was just about to open this issue myself <3

**Comment by emilio** [comment]
Is it redundant in all the rust versions that bindgen supports? I'm not sure we intentionally keep our generated code clippy-warning-free, but improvements are welcome of course.

**Comment by Lokathor** [comment]
Clearly the generated module should simply insert

```rust
#![allow(clippy::redundant_static_lifetimes)]
```

If you're targeting a rust version that allows tool attributes :P

But more seriously, the `'static` can probably be skipped if the target rust version is new enough.

looking through the releases file, seems like 1.17 made the change here https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1170-2017-04-27

**Comment by emilio** [comment]
Ok, we could add a [`rust-target`](https://searchfox.org/mozilla-central/rev/e8f334670ddf4879a80be7af79651c06592e1c3e/third_party/rust/bindgen/src/features.rs#92) for 1.17 and just not emit the `&'static` if the rust target version is greater than that.

**Comment by wucke13** [comment]
I was about to open this issue and then found it already here. Is this still considered a TODO?
