### ISSUE TITLE
consider replace fxhash with rust-lang/rustc-hash

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust-bindgen#1616]
As user of bindgen, I am worry about two functionality duplicates in my dep tree:

https://github.com/rust-lang/rustc-hash
https://github.com/cbreeden/fxhash

May be you consider usage of rustc-hash instead of fxhash?

Advantages:

1. fxhash looks like "dead" repository
2. rustc-hash belong the same orgranization (rust-lang ) as bindgen

**Comment by emilio** [comment]
>  fxhash looks like "dead" repository

What makes you think that?

> May be you consider usage of rustc-hash instead of fxhash?

Seems like the same hash, so sounds good, I'd be happy to merge a PR doing that switch :)
