### ISSUE TITLE
rustfmt the codebase

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust-bindgen#1618]
From GH-1615:

> @emilio I have `rustfmt` enabled by default on save in my editor and there was quite a lot of diff to ignore to make this PR minimal. Can we either `rustfmt` bindgen and add a step to CI to enforce code is formatted or add a `rustfmt.toml` so the formatting is preserved?

**Comment by emilio** [comment]
Yeah, we used to do it, but had to disable because https://github.com/rust-lang/rustfmt/issues/1376. We can re-enable it now, I'll put up a patch.

**Comment by emilio** [comment]
Opened https://github.com/rust-lang/rust-bindgen/pull/1621 for this.
