### ISSUE TITLE
Turning off default features of regex

### ISSUE THREAD

**Issue by est31** [rust-lang/rust-bindgen#1622]
It would be cool, from a dependency reduction POV, to turn off some of the default features of regex, at least the performance one. IDK about the unicode feature.

**Comment by emilio** [comment]
Sounds fair. Wanna submit a patch?

**Comment by est31** [comment]
> Wanna submit a patch

Thanks but I'll pass. I'd prefer someone else to submit it. It's quite trivial anyway.

**Comment by emilio** [comment]
Sure, I can do that if I remember, I'm away from my laptop atm. Thanks for filing!

**Comment by kulp** [comment]
This was closed by #1643 but without the Github auto-resolution [magic words](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
