### ISSUE TITLE
Add `.with_rustfmt("rustfmt")` if the `which-rustfmt` feature is disabled?

### ISSUE THREAD

**Issue by heidezomp** [rust-lang/rust-bindgen#1628]
I was very pleased to see that #1615 reduces the number of dependencies used by bindgen. However, now my bindings don't get formatted unless I add `.with_rustfmt("rustfmt")` to the builder options. Since the `which` dependency resolves a relative path to an absolute path, and adding the `.with_rustfmt("rustfmt")` option has the same effect but with the shell doing the resolving, would this be a reasonable fallback to add in case the `which-rustfmt` feature is disabled?

**Comment by emilio** [comment]
Perhaps, that would make sense to me.

**Comment by heidezomp** [comment]
Thanks for the quick reply and merge! :heart:
