### ISSUE TITLE
Emit rerun-if-changed of used and included files

### ISSUE THREAD

**Issue by chrysn** [rust-lang/rust-bindgen#1635]
When bindgen is used in `build.rs`, no `cargo:rerun-if-changed` lines are emitted that'd cause the build process to be rerun if any source file changed.

On projects where the C source and crates using the -sys crate are actively being developed, this leads to confusing error situations, and users that `rm -rf target` out of frustration.

I suggest adding an option to generate rerun-if-changed lines for all included files. If there is a danger to lead to long checking times due to lots of system libraries in practice, adding a filter function on the emitted header files could be an option. (That's inspired by gcc's distinction between `-MD` and `MMD`, where the latter ignores system header files).

**Comment by emilio** [comment]
Yeah, I agree that'd be nice. What Gecko does is not all that great either: https://searchfox.org/mozilla-central/rev/01d1011ca4a460f751da030d455d35c267c3e210/servo/components/style/build_gecko.rs#55

I think libclang exposes includes in the AST, so adding a ParseCallback for this would be the easiest, that way you can do whatever with them, not just printing them.

**Comment by emilio** [comment]
Well I guess this is not E-easy as in trivial, but I don't expect it'd be all that hard.

**Comment by emilio** [comment]
In particular we'd need to poke at the `InclusionDirective` cursors. [This code](https://github.com/rust-lang/rust-bindgen/blob/d6b25ed432136ce89217fc475ba63c95f292fb5d/src/ir/item.rs#L1360) ignores them, there's probably a better place to poke at them, but maybe just calling a function from there would do the trick... All cursors should go through there.

**Comment by chrysn** [comment]
Thanks, I'll try to work from there.

@highfive: assign me

**Comment by emilio** [comment]
Awesome, thanks!
