### ISSUE TITLE
Constants like `UINT_MAX` not recognized

### ISSUE THREAD

**Issue by chrysn** [rust-lang/rust-bindgen#1636]
### Input C/C++ Header

```C
#include <limits.h>

#define A 42
#define B UINT_MAX

static const unsigned int C = UINT_MAX;
```

### Bindgen Invocation

Both `bindgen defines.h` and a minimal `builder().header("defines.h").generate()?.write_to_file(…)` create the observed behavior.

### Actual Results

```rust
pub const A: u32 = 42;
extern "C" {
    #[link_name = "\u{1}C"]
    pub static mut C: ::std::os::raw::c_uint;
}
```

The `__bindgen.i` output from `bindgen --dump-preprocessed-output ./defines.h` contains a line

```
static const unsigned int C = (2147483647 *2U +1U);
```

which shows that to Clang, UINT_MAX is, with limits.h in place, valid.

### Expected Results

B should be recognized as a compiler constant and expanded.

---

I did not manage to follow Clang's reasoning to the end, but when I looked through the `( kind = macro_definition` debug output, not only did the `B` macro show up as invalid, but there was also a

```
(
 kind = macro definition
 spelling = "UINT_MAX"
 location = /usr/lib/llvm-8/lib/clang/8.0.1/include/limits.h:72:9
 is-definition? false
 is-declaration? false
 is-inlined-function? false
 usr = "c:@macro@UINT_MAX"

 type.kind = Invalid
)
```

section, following which I found `UINT_MAX` defined as `(__INT_MAX__  *2U +1U)`, where there is no macro for `__INT_MAX__` visible in the debug output -- so that's probably a compiler built-in constant. One way to resolve that might be to inject the compiler constants into the constant expression evaluation process that makes values out of nested defines. (Which otherwise work: a `#define TWICE_A (A * 2)` expands to 84 in bindgen).

**Comment by emilio** [comment]
Sorry for the delay here. We could probably define a few standard macros in BindgenContext::parsed_macros, if we wanted to fix this.

**Comment by reitermarkus** [comment]
I just hit the same problem on macOS with `limits.h`:

Minimal input:

```c
#include <limits.h>

const unsigned long VAR = ULONG_MAX;
```

Command:

```
bindgen minimal.h --allowlist-var ULONG_MAX --allowlist-var VAR
```

Output:

```
/* automatically generated by rust-bindgen 0.60.1 */

pub const ULONG_MAX: i32 = -1;
extern "C" {
    pub static VAR: ::std::os::raw::c_ulong;
}
```

**Comment by xbjfk** [comment]
Just ran into this issue, consider this C header:
```c
#define TEST0 0x7fffffffffffffff
#define TEST1 0x8fffffffffffffff
#define TEST2 0xefffffffffffffff
#define TEST3 0xfffffffffffffff0
#define TEST4 0xffffffffffffffff
```
leads to this seemingly random output:
```rust
pub const TEST0: u64 = 9223372036854775807;
pub const TEST1: i64 = -8070450532247928833;
pub const TEST2: i64 = -1152921504606846977;
pub const TEST3: i32 = -16;
pub const TEST4: i32 = -1;
```

**Comment by ojeda** [comment]
See as well https://github.com/rust-lang/rust-bindgen/issues/2120 and https://github.com/rust-lang/rust-bindgen/issues/1594.

**Comment by pvdrz** [comment]
This has been fixed by using the `--clang-macro-fallback` feature.
