### ISSUE TITLE
Request: flag to make c_void *always* come from core::ffi if rust is 1.30 or higher

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-bindgen#1644]
As of `rustc` 1.30 the `core::ffi::c_void` type became a stable part of core.

I know that the marker says "stable since 1.1", that's a mild lie. It was added to `std` in 1.1, and then added to `core` in 1.30
* [Absent in 1.29](https://doc.rust-lang.org/1.29.0/core/ffi/enum.c_void.html)
* [Added in 1.30](https://doc.rust-lang.org/1.30.0/core/ffi/enum.c_void.html)

What I would like is if, assuming that the `bindgen::RustTarget` setting is 1.30 or higher, I could set _all `c_void` values_ to use `core::ffi::c_void` regardless of wherever else the rest of the ctypes are coming from (eg: libc, or winapi or elsewhere).

**Comment by emilio** [comment]
So you want to tweak https://github.com/rust-lang/rust-bindgen/pull/1634 to:

 * Change the rust version check to 1.30 rather than 1.1 (we should do that regardless before releasing a new bindgen version).
 * Move the check so that it looks like:

```
if use_core && available {
  core::ffi::c_void
} else if let Some(prefix) = ctypes_prefix {
  #prefix::c_void
} else {
  std::os::raw::c_void
}
```

That seems reasonable to me.

**Comment by Lokathor** [comment]
I just realized when checking the Builder flags that there is unfortunately no way to specify code edition :/

**Comment by emilio** [comment]
Why does that matter? You mean to remove the ugly `::` prefix? yeah...

**Comment by Lokathor** [comment]
If you knew that the code was going to be 2018 edition you could simply _always_ inject `core::ffi::c_void`, without worrying about anything else at all. Or perhaps you still respect the `ctypes_prefix` if it's set.

But basically everyone in the Rust world 1.30 and on should unify on `core::ffi::c_void`, and the fact that `winapi` doesn't right now is because the current min version for that is 1.6

(also c_void from libc and std are both just re-exports of the one in core)

**Comment by Lokathor** [comment]
Actually even in 2015 you can still just use `extern crate core;` and then use `::core::ffi::c_void`, which is what you should probably heavily consider, because having different types of `c_void` in the Rust universe is a bug, not a feature.

**Comment by pvdrz** [comment]
I think this is already fixed as we use `core::ffi::c_void` when available
