### ISSUE TITLE
Tutorial broken on latest versions

### ISSUE THREAD

**Issue by rendaw** [rust-lang/rust-bindgen#1647]
### Bindgen Invocation

```Rust
bindgen::Builder::default()
        // The input header we would like to generate
        // bindings for.
        .header("wrapper.h")
        // Tell cargo to invalidate the built crate whenever any of the
        // included header files changed.
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        // Finish the builder and generate the bindings.
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");
```

### Actual Results

When building:

```
error[E0425]: cannot find function `CargoCallbacks` in module `bindgen::callbacks`
  --> libfido2/build.rs:23:55
   |
23 |         .parse_callbacks(Box::new(bindgen::callbacks::CargoCallbacks()))
   |                                                       ^^^^^^^^^^^^^^ not found in `bindgen::callbacks`
```

### Expected Results

The above code is copied more or less verbatim from the tutorial (reformatted for github).

It seems like CargoCallbacks was removed sometime before or at 0.50.1 - the tutorial suggests setting the dep as 0.50 and cargo installed 0.50.1.  Updating as recommended to 0.51.1 didn't fix the issue of course.

I'm entirely new to bindgen so I'm not sure what I should do instead - manually print the cargo directives or just remove it.

**Comment by emilio** [comment]
It's actually the other way around, CargoCallbacks was just added in #1637, and it's not released.

I should do a release soonish, probably, which will address this. Sorry for the hassle. The guide didn't use to have that line, which it is probably ok-ish if you don't touch the C++ code.

Sorry for the hassle :)

**Comment by viniciusd** [comment]
Is it gonna be on `0.52`? Just found this issue because of the guide page.

**Comment by viniciusd** [comment]
Is it gonna be on `0.52` @emilio ? Just found this issue because of the guide page.

**Comment by emilio** [comment]
Yeah, it will be on 0.52. It's a bit of an issue the fact that we have the guide representing `master` and not the latest release.

**Comment by nixomose** [comment]
" It's a bit of an issue the fact that we have the guide representing master and not the latest release."

Agreed. As a newbie trying to learn rust, I run into things like this at every step of the way.

**Comment by aloknnikhil** [comment]
> " It's a bit of an issue the fact that we have the guide representing master and not the latest release."
> 
> Agreed. As a newbie trying to learn rust, I run into things like this at every step of the way.
> As such, I'm still not sure how to fix it.

Change the Cargo.toml to use bindgen 0.52 

```
[build-dependencies]
bindgen = "0.52"
```

**Comment by nixomose** [comment]
okay thanks.
while I've got you :-) is the rustfmt thing supposed to work?
I call
.rustfmt_bindings(true)
and I have rustfmt installed, but it still ends up all on one line.
