### ISSUE TITLE
Docs: The `bindgen::RustTarget` doesn't explain the significance of each bind level

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-bindgen#1650]
There's many bindings levels on offer, but none of the levels explain what they add (in terms of generated bindings) over the previous levels.

**Comment by emilio** [comment]
That is a good point. I thought we also generated docs for `RustFeatures`, but I guess it's not public so it's not in docs.rs.

This is the map: https://searchfox.org/mozilla-central/rev/55aa17110091deef24b913d033ccaf58f9c6d337/third_party/rust/bindgen/src/features.rs#168

Adding docs for this should be trivial... Would you like to do that? Or alternatively I can do it, either way :)

**Comment by Lokathor** [comment]
I'll let you do it since it should be a simple copy and paste job, and I wouldn't be able to do it for at least the next 8 hours.

**Comment by emilio** [comment]
79b2b1042069ca6673afc706fca2207d715f6894
