### ISSUE TITLE
Use c2rust for cleaning up produced bindings

### ISSUE THREAD

**Issue by XVilka** [rust-lang/rust-bindgen#1652]
There is an issue to [use c2rust for tranlating inline functions](https://github.com/rust-lang/rust-bindgen/issues/1344), but if you check the output of bindgen, you can spot some patterns that c2rust also normally works with, so they created an amazing [refactoring tool](https://github.com/immunant/c2rust/tree/master/c2rust-refactor). And it can be scripted with Lua, so some bindgen-specific automation can be easily added without much changes from c2rust side - see [their manual for refactoring tool](https://c2rust.com/manual/c2rust-refactor/index.html). Sorry if idea is irrelevant, just thought it might be handy.

cc @thedataking @rinon @ahomescu @TheDan64

**Comment by emilio** [comment]
I think it's interesting, but what kind of refactoring do you want to apply to the generated bindings?

In general bindgen doesn't produce a lot of stuff other than declarations, typedefs, etc, so it's not clear to me what you can or cannot cleanup from them...

Do you have concrete examples or ideas?

**Comment by rinon** [comment]
I'm not sure refactoring is really needed for the auto-generated bindings. If there's particularly ugly codegen the generator could be fixed, but I'm not sure that's needed. When I've used bindgen I generally never look at the generated code, instead using the C header as API docs.

That said, I'd be happy to look into any particular refactoring that could be useful, if there are any.

**Comment by XVilka** [comment]
It was just a wild idea, you can close if you think it is useless. Sorry for disturbance.

**Comment by emilio** [comment]
No, no worries at all, it's appreciated :)

Closing as this is not actionable as-is, but feel free to reopen if there's anything concrete that could be done here.
