### ISSUE TITLE
Support for offsetof constants

### ISSUE THREAD

**Issue by dcoles** [rust-lang/rust-bindgen#1659]
A number of C libraries make use of `offsetof` as a primitive form of reflection. Often this will be exposed as a `get_object_foo` helpers or used to define `_OFFSET` constants which are used as part of the API. It would be useful if bindgen could evaluate these expressions and expand them into `usize` constants.

As you probably are aware, [Rust does not currently provide a built-in `offset_of` macro](https://internals.rust-lang.org/t/pre-rfc-add-a-new-offset-of-macro-to-core-mem/9273/88) which makes it difficult to reproduce this functionality on the Rust side.

### Input C/C++ Header

```C++
#define offsetof(type, member) __builtin_offsetof(type, member)

#define FOO_X_OFFSET offsetof(struct Foo, x)

struct Foo {
        int x;
};
```

### Bindgen Invocation

```
$ bindgen offset.h --blacklist-type Foo
```

### Actual Results

No constant is generated:

```rust
/* automatically generated by rust-bindgen */

```

### Expected Results

A `usize` typed constant with the offset of the member `x` in `struct Foo`:

```rust
/* automatically generated by rust-bindgen */

pub const FOO_X_OFFSET: usize = 0;
```

**Comment by emilio** [comment]
Hi, thanks for filing :)

This works already if you do:

```c
const unsigned FOO_X_OFFSET = offsetof(struct Foo, x);
```

as far as I can tell. Evaluating offsetof in macros is generally impossible, as macros are context-dependent. Of course you can do somewhat of a best-effort guess, but I wouldn't be in favor of that, plus it'd generally be pretty hacky.

More general macro improvements should be probably directed to the rust-cexpr, though I think realistically this is out of scope for that crate. Stuff like #316 and such should totally be feasible though.

**Comment by dcoles** [comment]
Oh! Wonderful. Thank you. :)
Didn't even think to try a constant. I can certainly work with that.
