### ISSUE TITLE
use MaybeUninit<T> instead of ::core::mem::uninitialized

### ISSUE THREAD

**Issue by ctaggart** [rust-lang/rust-bindgen#1660]
When using rust-bindgen from `master` in combination with Rust 1.39, I get a massive number of warnings because `::core::mem::uninitialized` is deprecated.

Function core::mem::uninitialized is deprecated in 1.39
https://doc.rust-lang.org/core/mem/fn.uninitialized.html
https://doc.rust-lang.org/core/mem/union.MaybeUninit.html

```
7523 |             let mut __bindgen_tmp = ::core::mem::uninitialized();
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |                                     |
     |                                     this code causes undefined behavior when executed
     |                                     help: use `MaybeUninit<T>` instead
```

**Comment by elichai** [comment]
Can be closed now that https://github.com/rust-lang/rust-bindgen/pull/1666 is merged.

**Comment by emilio** [comment]
Thanks @elichai!
