### ISSUE TITLE
convert ifdef to #[cfg]

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust-bindgen#1665]
### Input C/C++ Header

```C++
# ifdef __i386__
#  define BITS 32
# elif defined(__ILP32__)
#  define BITS 322
# else
#  define BITS 64
# endif
```

### Bindgen Invocation
`$ bindgen test.h`
### Actual Results

```
Insert panic message and backtrace (set the `RUST_BACKTRACE=1` env var) here.

```rust
/* automatically generated by rust-bindgen */

pub const BITS: u32 = 64;
```

### Expected Results
Something more of these lines:
```
#[cfg(target_arch = "i386")]
pub const BITS: u32 = 32;

#[cfg(all(not(target_arch = "i386"), target_pointer_width = "32"))]
pub const BITS: u32 = 322;

#[cfg(all(not(target_arch = "i386"), not(target_pointer_width = "32")))]
pub const BITS: u32 = 64;
```

And if `bindgen` uses `if-cfg` then:
```
cfg_if! {
    if #[cfg(target_arch = "i386")] {
        pub const BITS: u32 = 32;
    } else if #[cfg(target_pointer_width = "32")] {
        pub const BITS: u32 = 322;
    } else {
        pub const BITS: u32 = 64;
    }
}
```

**Comment by auscompgeek** [comment]
Part of the problem here is that, AFAIU, clang gives us an AST for the code after preprocessing.

**Comment by emilio** [comment]
Right, not only that, but bindgen uses current target information already for alignment purposes or what not.

So the right way to do this is running bindgen on the different targets (or at build time), and `#[cfg(target_arch)]` the bindings module or what not.

**Comment by elichai** [comment]
@emilio hmm but if I want to publish a `-sys` crate that binds to C code with a lot of ifdef's,
maybe looping per target is interesting, but that will create *a lot* of duplicate code.

**Comment by emilio** [comment]
I think the only sane alternative there is running bindgen at build-time.

**Comment by elichai** [comment]
hmmm idk, I really prefer to see code and it's changes, but I guess you're right. i'll give it a shot.

**Comment by pvdrz** [comment]
There's not much we can do from the bindgen side here. Feel free to reopen it though
