### ISSUE TITLE
Generate enums as newtypes with associated constants

### ISSUE THREAD

**Issue by auscompgeek** [rust-lang/rust-bindgen#1669]
Idea: Add an enum style which outputs newtypes with associated constants.

This would make it possible to implement methods for enums without the potential footgun of UB if unknown bit patterns are returned via FFI.

Example input:

```c++
#include <stdint.h>
enum ErrorCode : uint32_t {
  OK = 0,
  INVALID_INPUT = 1,
  DEVICE_MISSING = 2,
};
```

Example output:

```rust
#[repr(transparent)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct ErrorCode(pub u32);
impl ErrorCode {
  pub const OK: Self = Self(0);
  pub const INVALID_INPUT: Self = Self(1);
  pub const DEVICE_MISSING: Self = Self(2);
}
```

**Comment by emilio** [comment]
This looks a lot like the "bitfield" enum style, except without the operator implementations?

https://github.com/rust-lang/rust-bindgen/blob/3a6864cf9a76916c002c41a8ae813d9f8bd9853e/tests/expectations/tests/bitfield-enum-basic.rs#L50

**Comment by auscompgeek** [comment]
Heh, seems so. I thought that would use the bitflags crate.

**Comment by emilio** [comment]
Do you still want a new tweak to avoid the operators? Or is using `bitfield` enough and we should close this? I agree `bitfield` could be seen as a bit of a misnomer :)

**Comment by auscompgeek** [comment]
Yeah, the bitwise operators don't really make that much sense where I'd want to use it. Should be easy enough.

**Comment by emilio** [comment]
Ok, this should be pretty easy to add, let me know if you give it a shot and need any help with it :)

**Comment by auscompgeek** [comment]
Should we add a new `codegen::EnumVariation` or rename `EnumVariation::Bitfield` and make it a struct with an `is_bitfield` field?

**Comment by emilio** [comment]
Either way, the second looks slightly nicer to work with, even if they're exposed as two different names to the CLI.
