### ISSUE TITLE
bindgen 0.49.* derives `Copy` for types containing _IncompleteArrayField

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust-bindgen#1674]
### Input C/C++ Header

```C++
typedef struct {
 unsigned int magic;
 unsigned char data[];
} pk;
```

### Bindgen Invocation

```
    bindgen::Builder::default()
        .header("wrapper.h")
        .no_copy("(?i)mutex")
        .blacklist_type("_bindgen_ty_1")
        .opaque_type("max_align_t")
        .clang_args(nix_cflags.split(" "))
```

### Actual Results

```
error[E0204]: the trait `Copy` may not be implemented for this type
     --> somewhere deep in the file
      |
69596 | #[derive(Debug, Copy, Clone)]
      |                 ^^^^
...
69599 |     pub data: __IncompleteArrayField<::std::os::raw::c_uchar>,
      |     --------------------------------------------------------- this field does not implement `Copy`
```

### Expected Results

Successful compilation, which is what happened a couple of versions ago…

**Comment by emilio** [comment]
Hmmm... Is this with rust 1.39, and goes away with 1.38 by chance? If so, this is an issue that was fixed in #1627.

**Comment by emilio** [comment]
I can publish a 0.49 minor version if needed with that PR.

**Comment by nagisa** [comment]
This started occurring after a nightly bump so plausible that it could be a
38 to 39 change.

**Comment by emilio** [comment]
Yeah, I'm ~sure the only explanation for this is https://github.com/rust-lang/rust-bindgen/pull/1627, which was triggered by a rust change, see there.

If you can't update to 0.50 or 0.51 I'm happy to publish a minor version of 0.49 with that fixed, just lmk.
