### ISSUE TITLE
Examples to use bindgen generated __IncompleteArrayField<u8>

### ISSUE THREAD

**Issue by thefallentree** [rust-lang/rust-bindgen#1680]
Hi,

So I'm writing an Rust FFI library, and I need to return an FAM to C, using RVO like this

```c
struct CValue {
usize len;
uint8_t data[];
}
```

I used bindgen to generate definition for CValue, the type of CValue.data is an __IncompleteArrayField<u8>,

But, how do I allocate something and return it?  I can do __IncompleteArrayField::new() , but looks that just construct it with an empty slice, I can't even copy data into that

so what should I do?

```rust
pub extern "C" fn something() -> CValue {
  let buf = vec![1,2,3,4];
  CValue {
    ....
  }
}
```

**Comment by emilio** [comment]
You can't construct a `CValue` on the stack (you can't do that in C either), as moving it will copy only the length.

You need to do something like:

```rust
extern "C" fn something() -> *mut CValue {
    let count = 3; // Or something
    let layout = alloc::from_size_align(
        mem::size_of::<usize>() + count * mem::size_of::<u8>(),
        cmp::max(mem::align_of::<usize>(), mem::align_of::<u8>())
    ).unwrap();
    let value = alloc(layout) as *mut CValue;
    // write length and data.
    value
}
```

**Comment by thefallentree** [comment]
@emilio Thanks!  couple more questions:

1. In your example, do I still need std::mem:forget(value) ? otherwise rust will free the memory when Value is out of scope, right?

2. What if I just want to return . 
```c
struct CValue {
char stuff[32];
};
```
This translate by bindgen
```
struct CValue {
stuff [int; 32];
}
```
I found out if I just do 
```rust
pub fn extern "C" stuff() - >CValue {
 let buf . = [0; 32];
buf.copy_from_slice(vec![1,2,3,4].as_slice())
 return CValue {
      stuff:  buf
 }
}
```

I am still suffering from memory corruption issue, it looks like in this case rust doesn't copy arrays correctly either?

**Comment by thefallentree** [comment]
> You can't construct a `CValue` on the stack (you can't do that in C either), as moving it will copy only the length.
> 
> You need to do something like:
> 
> ```rust
> extern "C" fn something() -> *mut CValue {
>     let count = 3; // Or something
>     let layout = alloc::from_size_align(
>         mem::size_of::<usize>() + count * mem::size_of::<u8>(),
>         cmp::max(mem::align_of::<usize>(), mem::align_of::<u8>())
>     ).unwrap();
>     let value = alloc(layout) as *mut CValue;
>     // write length and data.
>     value
> }
> ```

Also, your example actually changed the extern signature, what if the C definition is really 
```struct CValue rust_fn(void);``` How to return an FAM with that?

Thanks

**Comment by emilio** [comment]
> In your example, do I still need std::mem:forget(value) ? otherwise rust will free the memory when Value is out of scope, right?

No, as it allocates on the heap. You need to free it later of course.

> Also, your example actually changed the extern signature, what if the C definition is really
struct CValue rust_fn(void); How to return an struct with FAM as this in rust?

You cannot, how would that work? That doesn't work in C either, afaict.

> Would this work correctly?

Yeah, that should work.

**Comment by emilio** [comment]
Let me know if I can help more here. Adding some docs for this would be great, though I don't have the time to do it myself atm.

**Comment by thefallentree** [comment]
@emilio Thanks for the response! I endsup choose to return C struct (client allocated on stack) with fixed length array, it seems to be the easiest way to avoid having to call free afterwards. and it seems to be working fine.

I can write an short doc talking about recommending this if you can point me the location I should send PR to

**Comment by emilio** [comment]
Adding some sort of section for this on [the bindgen book](https://github.com/rust-lang/rust-bindgen/tree/master/book) would be amazing.
