### ISSUE TITLE
bindgen does not emit functions for wasm/emscripten

### ISSUE THREAD

**Issue by tangmi** [rust-lang/rust-bindgen#1681]
It seems like `bindgen` doesn't produce bindings for functions when building with `cargo-web` for `wasm32-unknown-emscripten`.

### Input C/C++ Header

```C++
#pragma once

int add(int a, int b) {
    return a + b;
}
```

### Bindgen Invocation

```
PS> E:\bin\emsdk\emsdk_env.ps1;
Adding directories to PATH:
PATH += E:\bin\emsdk
PATH += E:\bin\emsdk\clang\e1.38.16_64bit
PATH += E:\bin\emsdk\node\8.9.1_64bit\bin
PATH += E:\bin\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64
PATH += E:\bin\emsdk\java\8.152_64bit\bin
PATH += E:\bin\emsdk\emscripten\1.38.16

Setting environment variables:
EMSDK = E:/bin/emsdk

PS> bindgen input.h -o bindings.rs -- --target=wasm32-unknown-emscripten
...
```

### Actual Results

Output of `bindings.rs`:

```rust
/* automatically generated by rust-bindgen */



```

Output of `RUST_LOG=bindgen`: (note it's finding my system clang, but using the emsdk one?)

```
[2019-11-18T20:23:45Z INFO  bindgen] Clang Version: clang version 8.0.1 (tags/RELEASE_801/final)
[2019-11-18T20:23:45Z WARN  bindgen] Using clang (8, 0), expected (3, 9)
[2019-11-18T20:23:45Z DEBUG bindgen] Generating bindings, libclang at C:\Program Files\LLVM\bin\libclang.dll
[2019-11-18T20:23:45Z DEBUG bindgen] Trying to find clang with flags: ["--target=wasm32"]
[2019-11-18T20:23:45Z DEBUG bindgen] Found clang: Clang { path: "E:\\bin\\emsdk\\clang\\e1.38.16_64bit\\clang.exe", version: Some(CXVersion { Major: 6, Minor: 0, Subminor: 1 }), c_search_paths: None, cpp_search_paths: None }
...
```

Output of `clang --version`

```
PS> clang --version
clang version 6.0.1  (emscripten 1.38.16 : 1.38.16)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: E:\bin\emsdk\clang\e1.38.16_64bit
```

### Expected Results

Something similar to the non-wasm build, however it seems the `link_name` is different across msvc and emscripten... 

```rust
extern "C" {
    #[link_name = "_Z3addii"] // Note: I found this by poking around the clang-compiled `.o` file targetting wasm32.
    pub fn add(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
```

I've also tried some of the things in the discussion after #730 was closed:
- The `asmjs` target results in a libclang panic
- I am running the `emsdk_env` script beforehand, but am still not getting the function bindings.
- I also tried @emilio's suggestion in https://github.com/rust-lang/rust-bindgen/issues/751#issuecomment-308721232 to comment out this: https://github.com/rust-lang/rust-bindgen/blob/5f4dc4f458f0fd14beafbacb8bb20a5a4d139cd5/src/ir/function.rs#L565-L568, so perhaps it's the same issue?

Thanks for your time!

**Comment by emilio** [comment]
Yeah this is https://github.com/rust-lang/rust-bindgen/issues/751. But poking at it I found a fix, will comment there.
