### ISSUE TITLE
Tests have incorrect sizes when cross-compiling

### ISSUE THREAD

**Issue by NickeZ** [rust-lang/rust-bindgen#1684]
Hi,

I'm generating bindings using the flag `-fshort-enums` (see  #711) flag and building for a 32bit target (cortex-m4).

When I run `cargo test` it claims that the struct sizes are wrong.

I guess this is because when the code is compiled for testing it will be compiled for x86_64 so pointer sizes are larger and enums are always 4 bytes. It seems like the size expected by the test is correct and the size given by `size_of` is wrong.

Are there any way to actually test this, or should I simply avoid the below snippet when I compile for testing?

```
        .clang_args(&[
            "--target=thumbv7em-none-eabi",
            "-mcpu=cortex-m4",
            "-mthumb",
            "-mfloat-abi=soft",
            "-fshort-enums",
        ]);
```

Removing those lines fixes the tests, but then I'm actually not testing that the sizes match on the *real* architecture.

**Comment by emilio** [comment]
Well, you should run the tests for the architecture the bindings were generated for, otherwise there is no guarantee that they'll pass indeed.

So you should `cargo test --target=xxx` or copy the test binaries to the device.

**Comment by NickeZ** [comment]
OK, thanks, I don't think I have the resources to test on virtual machines or real machines right now.
