### ISSUE TITLE
Long path names won't compile on Windows

### ISSUE THREAD

**Issue by TomzBench** [rust-lang/rust-bindgen#1689]
I was testing my project on Windows and I find some projects work in certain directories and not in other directories. The initial error that CMAKE reports is that the C compiler was not found. However when reading the cmake error logs I found this:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(175,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "Debug\CompilerIdCXX.tlog\ParallelCustomBuild.command.1.tlog". Path: Debug\CompilerIdCXX.tlog\ParallelCustomBuild.command.1.tlog **### exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.**

This might be a cargo issue (It's clearly a Windows issue). But I am wondering if there is some solution to working with this restriction. I am already in a short directory path. The long names are being generated by the build tools, not me.

**Comment by emilio** [comment]
Can you elaborate / put an example that's erroring? I have never seen that error... But it seems somewhat independent of bindgen?

**Comment by TomzBench** [comment]
Yes it is not at all a bindgen issue.  It is a Windows Build issue (MSBuild.exe referenced here: https://github.com/microsoft/msbuild/issues/53).  MSBuild will throw an error if it detects a file string longer than 260 chars. And because cargo generates long path names, cargo sometimes fails to build on Windows. I can't reproduce with a repository because it depends on where you clone the repository and your local file structure. But if you try to run cargo build with a MSBuild compiled component starting from a root path at around 260 chars you'll probably see the error.

I posted the issue here to look for potential work-arounds (besides moving your repository to a shorter folder name).

**Comment by emilio** [comment]
Ah, ok, no problem :-)
