### ISSUE TITLE
Syntactically incorrect Rust produced when struct is largest member of union

### ISSUE THREAD

**Issue by mbarbar** [rust-lang/rust-bindgen#1690]
For this example, I installed bindgen by invoking `cargo install bindgen`.

### Input C/C++ Header

```C++
union {
  struct {
    char a;
    char b;
  };
  char c;
};
```
I deduced this from [origuruma.h](https://github.com/kkos/oniguruma/blob/master/src/oniguruma.h). From a little mucking about, it seems this problem occurs when a struct is the largest member of a union.

### Bindgen Invocation

```
$ bindgen min.c
```

### Actual Results

The fifth line contains the problem.

```rust
min.c:2:1: warning: declaration does not declare anything [-Wmissing-declarations], err: false
/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Copy, Clone)]; 2usize ] , }#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _bindgen_ty_1__bindgen_ty_1 {
    pub a: ::std::os::raw::c_char,
    pub b: ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout__bindgen_ty_1__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<_bindgen_ty_1__bindgen_ty_1>(),
        2usize,
        concat!("Size of: ", stringify!(_bindgen_ty_1__bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<_bindgen_ty_1__bindgen_ty_1>(),
        1usize,
        concat!("Alignment of ", stringify!(_bindgen_ty_1__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_bindgen_ty_1__bindgen_ty_1>())).a as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_bindgen_ty_1__bindgen_ty_1),
            "::",
            stringify!(a)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_bindgen_ty_1__bindgen_ty_1>())).b as *const _ as usize },
        1usize,
        concat!(
            "Offset of field: ",
            stringify!(_bindgen_ty_1__bindgen_ty_1),
            "::",
            stringify!(b)
        )
    );
}
#[test]
fn bindgen_test_layout__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<_bindgen_ty_1>(),
        2usize,
        concat!("Size of: ", stringify!(_bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<_bindgen_ty_1>(),
        1usize,
        concat!("Alignment of ", stringify!(_bindgen_ty_1))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_bindgen_ty_1>())).c as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_bindgen_ty_1),
            "::",
            stringify!(c)
        )
    );
}
```

Here's the compilation error I get when trying to compile [bat](https://github.com/sharkdp/bat) which requires [onig](https://github.com/rust-onig/rust-onig).

```
rror: unexpected close delimiter: `]`
    --> /home/mbarbar/clone/bat/target/debug/build/onig_sys-bca06a96ab80abfa/out/bindings.rs:1389:32
     |
1389 | #[derive(Copy, Clone)]; 2usize ] , }#[repr(C)]
     |                                ^ unexpected close delimiter

error: aborting due to previous error

```

### Expected Results

The generated result is not syntactically correct. I'm quite new to Rust so I'm not sure what exactly was *supposed* to be produced, just that rustc expects something else. By looking at what is produced when the struct is smaller than some other field (I put a `long long` in), I get
```
#[repr(C)]
#[derive(Copy, Clone)]pub union _bindgen_ty_1 { pub __bindgen_anon_1 : _bindgen_ty_1__bindgen_ty_1 , pub l : :: std :: os :: raw :: c_longlong , _bindgen_union_align : u64 , }#[repr(C)]
```
So I suppose in the example the union being cut off is the problem.

It was [reported](https://github.com/rust-onig/rust-onig/issues/120) a couple months ago by a user  also trying to build `bat` but he seemed to fix it. The maintainer of `rust-onig` couldn't reproduce the issue. Regardless, the minimal example, unless I'm using `bindgen` wrong, produces the same issue.

**Comment by emilio** [comment]
This looks like you have a very old rustfmt version that is misformatting the rust code. You could verify it with `--no-rustfmt-bindings`. We've had various reports like this (https://github.com/rust-lang/rust-bindgen/issues/1174 / https://github.com/rust-lang/rust-bindgen/issues/1156 / ...).

Let me know if it is not that and we can reopen and investigate more, but I couldn't reproduce this and it looks a lot like those reports.

**Comment by mbarbar** [comment]
Ahh! Thank you! The rustfmt I had installed through my distro's package manager was 0.9.0-nightly. I have now installed rust and its tools through rustup and all is great. This is also why the other reporter was not able to reproduce the error anymore it seems.
