### ISSUE TITLE
Suggestion for a different constified enum

### ISSUE THREAD

**Issue by estchd** [rust-lang/rust-bindgen#1700]
I am suggesting a new type of constified enum.

### C/C++ Type
I am referencing a C/C++ enum like this:
````
typedef enum _ENUM 
{
    VARIANT1 = 0,
    VARIANT2,
    VARIANT3,
} ENUM
```` 

### Current Rust Type
Currently, said C/C++ enum is translated to Rust Code like this:
````
pub type _ENUM = u32;
pub const VARIANT1 : _ENUM = 0;
pub const VARIANT2 : _ENUM = 1;
pub const VARIANT3 : _ENUM = 2;
pub type ENUM = _ENUM;
````

### Suggested Rust Type
I suggest changing this to a Type based on a Tuple Struct like this:
````
#[repr(C)] 
#[derive(PartialEq, Eq)] 
pub struct ENUM(u32);

impl ENUM
{
    pub const VARIANT1: ENUM = ENUM(0);
    pub const VARIANT2: ENUM = ENUM(1);
    pub const VARIANT3: ENUM = ENUM(2);
}
````

### Reason / Differences
The main reasons i am suggesting this are:
1. With this Variant, you have to access the Enum Variants through the Type instead of putting them all in the Module directly as before.
    Before:
    ````
    let variant: ENUM = VARIANT1;
    ````
    After:
    ````
    let variant: ENUM = ENUM::VARIANT1;
    ````
2. With this Variant, you cannot assign any type to the ENUM type, except aliased types of ENUM.
    Especially other enum types and u32.
    Before:
    ````
    let variant: ENUM = 2u32; //this is valid
    let number: u32 = VARIANT1; //this is valid too
    ````
    After:
    ````
    let variant: ENUM = 2u32; //this is no longer valid
    let number: u32 = ENUM::VARIANT1; //this is no longer valid

    pub struct ENUM2(u32); // let this be another enum

    let variant2: ENUM2 = ENUM::VARIANT1; //this is also not valid
    ````

### Tests of Equality
I have tested my enum type with a FFI function that normally accepts u32 parameters and havent noticed anything working differently than with regular constified enums.
I have also looked at the assembly code generated by some test functions and it seems to produce the same or equivalent instructions

### Open Questions
- I am unsure, if the struct member has to be public as to enable access to it for matching, like this:
    ````
    pub struct ENUM(pub u32);
    ````
- I am also unsure, if this is the right way / format for this suggestion

**Comment by emilio** [comment]
```
#[repr(C)] 
#[derive(PartialEq, Eq)] 
pub struct ENUM(u32);
```

This needs to be `#[repr(transparent)]` to be sound. But otherwise it's ok. But it seems what the `newtype` enum style already does? (#1677).

See https://github.com/rust-lang/rust-bindgen/pull/1677/files#diff-5d01499bbb4b204972f6b97f29da8ab5 for an example.

Let me know/reopen if I'm missing something though.
