### ISSUE TITLE
Publish 0.52.1

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust-bindgen#1701]
https://github.com/rust-lang/rust-bindgen/commit/7d61f36a5bfcfe2ea533f5edcae8bb6991683432 fixed error that prevents the docs.rs docs from being generated: https://docs.rs/crate/bindgen/0.52.0/builds . It would be nice to have a working docs link again.

**Comment by kulp** [comment]
@jdm, given that 0.53 and 0.54 have been released, is it fine to close this issue now ?

**Comment by jdm** [comment]
Yep.
