### ISSUE TITLE
generate bindings for c program with pthread

### ISSUE THREAD

**Issue by VirosaLi** [rust-lang/rust-bindgen#1708]
I'm trying to generate bindings for a small C program with pthread. How do I add the "-pthread" flag in the build.rs script?

Thanks!

**Comment by emilio** [comment]
I'm confused, bindgen doesn't build anything itself. You'd need to build the C program separately like [this](https://github.com/rust-lang/rust-bindgen/blob/ba409edf5d3a1acc6ac4dcb32d1e168cc3a2a41b/bindgen-integration/build.rs#L75).

How does your build script look like?

**Comment by VirosaLi** [comment]
Thank you very much!
