### ISSUE TITLE
Packed bitfield struct produces incorrect size struct (and maybe alignment?)

### ISSUE THREAD

**Issue by TheDan64** [rust-lang/rust-bindgen#1716]
Based on discussion [from here](https://www.reddit.com/r/rust/comments/euxy49/bitfields_forever_why_we_need_a_ccompatible_rust/ffsx68p). Seen in Linux.

### Input C/C++ Header

```C
struct Date {
    unsigned char day: 5;
    unsigned char month: 4;
    signed short year: 15;
} __attribute__((packed));
```

### Bindgen Invocation

```Rust
let bindings = bindgen::Builder::default()
    .header("date.h")
    .parse_callbacks(Box::new(bindgen::CargoCallbacks))
    .generate()
    .expect("Unable to generate bindings");

let out_path = PathBuf::from(env::var("PWD").unwrap());
bindings
    .write_to_file(out_path.join("bindings.rs"))
    .expect("Couldn't write bindings!");
```

### Actual Results

```rust
#[repr(C)]
pub struct __BindgenBitfieldUnit<Storage, Align> {
    storage: Storage,
    align: [Align; 0],
}

// ...

#[repr(C, packed)]
pub struct Date {
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize], u16>,
}
```

### Expected Results

```bash
clang -Xclang -fdump-record-layouts date.c
```

outputs:

```C
*** Dumping AST Record Layout
     0 | struct Date
 0:0-4 |   unsigned char day
 0:5-8 |   unsigned char month
1:1-15 |   signed short year
       | [sizeof=3, align=1]
```

but the array passed to `__BindgenBitfieldUnit` is four bytes large, not three. Furthermore, not sure if this part matters because the align array is zero-len, but shouldn't the align type be a `u8` not `u16` since it has an alignment of 1?

**Comment by emilio** [comment]
The alignment shouldn't matter as the struct is packed (so the layout test should still pass once we fix the other issue).

The issue about the size is totally correct. We're probably not accounting for packing when computing bitfield sizes..
