### ISSUE TITLE
BINDGEN_EXTRA_CLANG_ARGS for command line mode

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust-bindgen#1723]
when option dump-preprocessed-input is used, BINDGEN_EXTRA_CLANG_ARGS is evaluated AFTER handling dump-preprocessed-input which result errors like "head files not found" etc in cross-compiling.

**Comment by BaoshanPang** [comment]
Actually BINDGEN_EXTRA_CLANG_ARGS is supported in command line mode.
The problem is when option dump-preprocessed-input is used, BINDGEN_EXTRA_CLANG_ARGS is evaluated before handling dump-preprocessed-input.

**Comment by emilio** [comment]
Ah, this should be relatively straight-forward to fix. Probably most of `Bindings::generate` should move to a common function that `dump_preprocessed_input` could reuse. We should make sure we only run it once though.

**Comment by smurfd** [comment]
Hi, have looked at this abit and was wondering. 

Would it be something like in `impl Bindings {` create a 
```
fn generate_common(options: &mut BindgenOptions) {
// context from these lines : 
https://github.com/rust-lang/rust-bindgen/blob/b424c17608206166b98db0e1b7da752a1e560f54/src/lib.rs#L1884-L1956
}
```
then at : https://github.com/rust-lang/rust-bindgen/blob/b424c17608206166b98db0e1b7da752a1e560f54/src/lib.rs#L1957 
we call `Bindings::generate_common(&mut options);`

Im abit fuzzy on where in `dump_preprocessed_input` we would call this `generate_common()`
Maby here? https://github.com/rust-lang/rust-bindgen/blob/d794a0823c83d9b8e36666cdcb932b7a4c5aac21/src/lib.rs#L1374
Before we go through the `self.options.clang_args` that the `BINDGEN_EXTRA_CLANG_ARGS` is stored?!

And then for it to just be run once we have a boolean argument to `Bindings::generate` that is set to false as default, but if true then we dont run the `generate_common()` 

Pretty much here, set a boolean to true https://github.com/rust-lang/rust-bindgen/blob/b424c17608206166b98db0e1b7da752a1e560f54/src/lib.rs#L1286
that we add to the `Bindings::generate(self.option)` abit lower down.

Thanks in advance :)

**Comment by smurfd** [comment]
Hey, if someone is interested in working on this, please please do.
Had completely forgot about this until last week when i got a mail about my pr conflicting with [67538b6](https://github.com/rust-lang/rust-bindgen/commit/67538b64ea1b90a0d01e4f6ebd45713ec03c9222)

Will probably close my pr in a while if i don't see something easy i have missed.

**Comment by smurfd** [comment]
nevermind the above, have an actual patch that might be what is looked for in #1915
