### ISSUE TITLE
extern const array is unexpectedly mut

### ISSUE THREAD

**Issue by bobbobbio** [rust-lang/rust-bindgen#1727]
### Input C/C++ Header

```C
extern const int foo[1];
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    pub static mut foo: [::std::os::raw::c_int; 1usize];
}
```

### Expected Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    pub static foo: [::std::os::raw::c_int; 1usize];
}
```

The const from the array seems to be lost. Arrays are a bit strange in C, but as best I can tell when you put `const` on an array it does in fact mean that values in the array are const, and as such the binding on the Rust side should not be `mut`.

**Comment by emilio** [comment]
Hmm... Yeah, this looks def. wrong. `Var::is_const` is returning `false` unexpectedly. I don't think this should be very hard to track down.

**Comment by emilio** [comment]
So the clang type for this test-case is `const int [1], kind: ConstantArray`. But `clang_isConstQualifiedType` returns `false` for that...

**Comment by bobbobbio** [comment]
I knows its a little late, but thank you for fixing this!
