### ISSUE TITLE
just a question: does bindgen generate the ::new() associated function (or are there plans to do that?)

### ISSUE THREAD

**Issue by nixomose** [rust-lang/rust-bindgen#1733]
just a question, didn't see anything in the docs, thought I'd ask here.

**Comment by emilio** [comment]
What do you plan to generate and how? I don't think this is easy to do in the general case.

**Comment by pvdrz** [comment]
@nixomose any updates?

**Comment by nixomose** [comment]
Wow we're going way back here.
I don't work on that project anymore so I don't exactly recall what this was about.
But I do have some vague memory of the generated code actually already having what I needed so I didn't need ::new().
But I couldn't tell you more than that without an archeological dig to figure out what I was referring to.
