### ISSUE TITLE
Possible optimizations for --help and --version (excessive calls to statx and friends)

### ISSUE THREAD

**Issue by kentfredric** [rust-lang/rust-bindgen#1736]
I'm not entirely sure where the root cause of this behaviour lies, but this is just silly:

```
 strace -c ./target/release/bindgen --help
...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 73.98    0.749463          11     64569      1564 statx
 12.85    0.130130          18      6950           getdents64
  4.73    0.047883          13      3598        36 openat
...

 strace -c ./target/release/bindgen --version
bindgen 0.53.1
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 73.81    0.766150          11     64569      1564 statx
 12.97    0.134592          19      6950           getdents64

```

**Comment by emilio** [comment]
I don't see such an outrageous use of syscalls, but this seems to come from `let version = clang_version()`, where we try to dynamically load libclang, and clang-sys does a lot of path-walking looks like.

Probably we don't need to do that so early on startup, I'd be happy to take a patch to move that till later or something.

**Comment by kentfredric** [comment]
While digging into seeing what I need to do, I spot this um, curious line:

https://github.com/rust-lang/rust-bindgen/blob/d65100ebbaffabcc91e81ba3e88160de7cb2d5ff/src/main.rs#L46-L48

I'm not sure that makes sense.

**Comment by kentfredric** [comment]
Thinking about it, its quite easy to eliminate the version + `info!()` call stuff for the `--help` target, but conceivably, there's a justified usecase for this information being visible with `--version`.

But looking at clap, it doesn't seem like there's a way to *lazily* execute this path in the `--version` path.

It *would* be nice if it could leverage `App::long_version` style functionality, where `-V` gives just bindgens version, and `--version` gives more verbose version info, including clang version data.

But there's no visible way to make these "get a version from a thing" through the `--version` handler, without making the "get a version from a thing" happen at the `App` building level -_-

I thought (wrongly) perhaps the fact `long_version()` takes an `Into<>` it might cleverly have a way to hold onto the trait object, and only convert it to a string when needed, but it seems it happens directly in the function call and is hard converted into `&str` :(

Thoughts?

**Comment by kentfredric** [comment]
Hmm, I toyed with `.settings(AppSettings::DisableVersion)` and reconstructing the `-V`,`--version` functionality from scratch, but its presently too much work.

Because `clap` doesn't appear to give any API to determine if the "short" or "long" form of the command was called, and although you could implement it as *2* commands, as far as I can tell, they'd get individual lines in `--help`, which changes things too much.

Clap itself presently has horror inducing hacks where `--version` and `-V` appear to be hard-coded special cases.
