### ISSUE TITLE
Request: sort all items emitted based on their item type

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-bindgen#1743]
When generating bindings for say SDL2 you get output portions like this:
```rust
pub const SDL_INIT_EVERYTHING: u32 = 62001;
extern "C" {
  pub fn SDL_GetPlatform() -> *const chlorine::c_char;
}
pub type size_t = chlorine::c_ulonglong;
pub type wchar_t = chlorine::c_ushort;
pub type va_list = __builtin_va_list;
pub const SDL_FALSE: SDL_bool = 0;
pub const SDL_TRUE: SDL_bool = 1;
pub type SDL_bool = i32;
```

It would be nice if all items could be sorted so that (for example) all types are declared first, then all structs, then all consts, then all function signatures, etc.

**Comment by emilio** [comment]
I think that'd be reasonable... I think our current ordering is the order in which we parse the C / C++
