### ISSUE TITLE
doesn't work (windows 10 64bit)

### ISSUE THREAD

**Issue by bugproof** [rust-lang/rust-bindgen#1752]
I installed the latest LLVM from here:

https://releases.llvm.org/download.html

(exactly following https://github.com/rust-lang/rust-bindgen/blob/master/book/src/requirements.md)

and when I try to use bindgen:

```
C:\Users\Konrad\source\repos\hf\testapp>bindgen testapp.h
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [(C:\\Program Files\\LLVM\\bin\\libclang.dll: invalid DLL (64-bit))])"', C:\Users\Konrad\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.53.2\src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`LIBCLANG_PATH` is set to `C:\Program Files\LLVM\bin`

it's my first time using bindgen, this is really discouraging

**Comment by bugproof** [comment]
OK, so I realized rust used x86 msvc toolchain by default (even if im on windows 10 x64), I installed x64 toochain and re-installed bindgen with cargo install bindgen and it works.

**Comment by andybry** [comment]
Thank you for posting this issue! It was an extremely helpful find at the end of hours of debugging! 

Just to supplement your answer slightly, the toolchain I ended up installing was: `stable-x86_64-pc-windows-msvc`.

**Comment by bugproof** [comment]
@andybry you're welcome!
