### ISSUE TITLE
document the minimum supported Rust version (policy)

### ISSUE THREAD

**Issue by tanriol** [rust-lang/rust-bindgen#1758]
I tried to find information on the minimum Rust version `bindgen` supports (MSRV) and failed to find this information or any policy regarding this, including the readme, the book's Requirements and FAQ sections. Could you please document it somewhere?

**Comment by emilio** [comment]
That's fair. We should:

 * Figure out what the current MSRV is.
 * Document it.
 * Test it so that we don't accidentally regress it.

I'm still a bit on the fence on whether bumping MSRV should be a breaking change in the library or not, though the above steps should be uncontroversial.
