### ISSUE TITLE
Dependency on `LIBCLANG_PATH` is not propagated back to cargo

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust-bindgen#1766]
I have upgraded clang from 7.0 to 10.0 and set `LIBCLANG_PATH` (the path changed) to a new clang, however to my surprise `cargo build` did not rebuild any of the crates that depend on bindgen to generate bindings.

Bindgen should be telling cargo to rerun the build.rs for the crate if following are true:

1. The used libclang shared library has changed;
2. `LIBCLANG_PATH` has changed…

and whatever other things can influence loading of the libclang.

**Comment by kulp** [comment]
I do not know all of the things that "can influence loading of the libclang", and my proposed #1809 may or may not sufficiently cover all the cases, but I think it meets the main need here.

**Comment by emilio** [comment]
Well, #1809 only addresses bindgen's tests. Ideally we should do something a bit more automatic here... Maybe `CargoCallbacks` should print this at some point, or Bindgen's `generate` if we detect we're running under Cargo? (what is the right way to detect that? Checking for `OUT_DIR`?)

**Comment by kulp** [comment]
@emilio, perhaps I misunderstand, but my demonstration in #1809 was meant to show that changing `LIBCLANG_PATH` when building a *downstream* crate _does_ cause bindings to be regenerated, so this does not affect only bindgen's tests, I think.

**Comment by emilio** [comment]
Ah, indeed. We invoke `testgen::main` unconditionally, so it ends up working... I'd say it makes sense for that bit to be outside of the `testgen` module though, as it's not related to test generation.

But yeah, this should be closed, behavior here after your PR is correct, thanks @kulp!

**Comment by kulp** [comment]
Good point about `testgen` -- I had not looked very carefully at where I was adding the code, I admit (I just added it in the vicinity of some other `cargo:rerun` prints). I will look for a better place.

**Comment by kulp** [comment]
I see you are way ahead of me in #1811. Thanks !

**Comment by kulp** [comment]
I guess we should probably check `BINDGEN_EXTRA_CLANG_ARGS` too, from #1537, so I created #1813.
