### ISSUE TITLE
--size_t-is-usize not working if the function is named malloc

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust-bindgen#1770]
### Input C/C++ Header
```
#include <stddef.h>
void* malloc(size_t size);
```

which reduces to this:

```
typedef long unsigned int size_t;
void* malloc(size_t size);
```

### Bindgen Invocation

```
bindgen --size_t-is-usize test.h -o test.rs  --dump-preprocessed-input
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    pub fn malloc(size: ::std::os::raw::c_ulong) -> *mut ::std::os::raw::c_void;
}
```

### Expected Results

I'd expect that if `--size_t-is-usize`, then the function would take an `usize` instead of a `raw::c_ulong`. 
The `--size_t-is-usize` seems to be ignored in this case?

**Comment by emilio** [comment]
Huh, that sure is odd. I think clang is messing with us on this one, it works if you change the name of the function to `malloc1` or such. lol

**Comment by pvdrz** [comment]
I think this is because `clang` performs a bunch of optimizations for built in functions. If you pass `-- -fno-builtin` to `bindgen` the output is the expected one
```rust
/* automatically generated by rust-bindgen 0.63.0 */

extern "C" {
    pub fn malloc(size: usize) -> *mut ::std::os::raw::c_void;
}
```
