### ISSUE TITLE
Rust method wrapper is still emitted for blacklisted functions

### ISSUE THREAD

**Issue by rinon** [rust-lang/rust-bindgen#1774]
Is it intended behavior that a Rust method is still emitted even though the function it wraps is blacklisted? Is there a different way to blacklist a method so the method wrapper is not emitted? Looking through the code I don't see one.

I've got a simple three line change to not emit methods for blacklisted functions, if this was not intended behavior. Because that's a behavior change, I thought I should file this issue to discuss first.

**Comment by emilio** [comment]
You mean that we emit an `impl Foo { fn bar() { ... } }` calling a blacklisted function? Yeah I don't think that's expected.

**Comment by emilio** [comment]
Feel free to submit the PR for discussion directly next time, fwiw :)

Thanks!
