### ISSUE TITLE
0.53.0 broke semver? 

### ISSUE THREAD

**Issue by dvdplm** [rust-lang/rust-bindgen#1776]
I think https://github.com/rust-lang/rust-bindgen/pull/1688 broke semver. Updating `rust-mbedtls` from using `bindgen@0.52.0`to ``bindgen@0.53.0` I'm getting a ton of errors like:

```
error[E0308]: mismatched types
   --> mbedtls/src/x509/csr.rs:196:22
    |
196 |                 Some(F::call),
    |                      ^^^^^^^ expected `u64`, found `usize`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, u64) -> _`
                  found fn item `unsafe extern "C" fn(_, _, usize) -> _ {<F as rng::RngCallback>::call}`
```

Possibly the culprit is https://github.com/rust-lang/rust-bindgen/pull/1688?

Not sure what can be done at this time, but yeah, upgrading `bindgen` is harder than it could be.

**Comment by xfix** [comment]
It didn't. See https://semver.org/.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by emilio** [comment]
Yes, plus fwiw, you may want `size_t_is_usize=true` to restore the previous behavior.

**Comment by dvdplm** [comment]
> Yes, plus fwiw, you may want `size_t_is_usize=true` to restore the previous behavior.

Right, which was introduced in 0.53.0 if I’m not mistaken?
