### ISSUE TITLE
Bindgen generates wrong bingings for function

### ISSUE THREAD

**Issue by DuckerMan** [rust-lang/rust-bindgen#1778]
### Input C/C++ Header

```C++
    typedef
        _Function_class_(EVT_VIGEM_X360_NOTIFICATION)
        VOID CALLBACK
        EVT_VIGEM_X360_NOTIFICATION(
            PVIGEM_CLIENT Client,
            PVIGEM_TARGET Target,
            UCHAR LargeMotor,
            UCHAR SmallMotor,
            UCHAR LedNumber,
            LPVOID UserData
        );

    typedef EVT_VIGEM_X360_NOTIFICATION *PFN_VIGEM_X360_NOTIFICATION;
```

### Bindgen Invocation

```
$ bindgen .\ViGEmClient.cpp -o mod.rs  --whitelist-function 'vigem_.*' 
```

### Actual Results

```rust
pub type PFN_VIGEM_X360_NOTIFICATION = ::std::option::Option<unsafe extern "C" fn()>;
```

### Expected Results
In rust bindings, there's function with no params, but as we can see in CPP code - there's a lot of params.

By the way, [bindings](https://github.com/DuckerMan/vigem/blob/master/src/binds/mod.rs)
[headers](https://github.com/DuckerMan/vigem/tree/master/src/binds)

**Comment by DuckerMan** [comment]
And there's no `EVT_VIGEM_X360_NOTIFICATION ` in bindings :(

**Comment by emilio** [comment]
This seems similar to some other issues where libclang doesn't expose the arguments probably, then bindgen tries to guess from the AST, but it still fails because of macros.

Can you paste a definition of `EVT_VIGEM_X360_NOTIFICATION` and the other macros in use here? Ideally a chunk of code that reproduces the issue entirely is the most helpful.

Thanks for filing!

**Comment by emilio** [comment]
Ah, apparently `_Function_class_` is some sort of VC++ annotation. TIL

**Comment by DuckerMan** [comment]
Hi there! I'm not familiar with C++. How can I find the macros in the code?

**Comment by emilio** [comment]
You need to find where `CALLBACK` and `VOID` are defined and so on.

**Comment by DuckerMan** [comment]
Do you mean LPVoid, right?

**Comment by DuckerMan** [comment]
There's [void](https://www.thoughtco.com/definition-of-void-958182).
and I could not find `CALLBACK` definition

**Comment by emilio** [comment]
No, I know what `void` is, this is about `VOID` (uppercase). The definition is probably in one of the windows headers.

It seems `CALLBACK` is just `__stdcall`.

**Comment by emilio** [comment]
So something like this should do:

```c
#define VOID void
#define CALLBACK __stdcall
#define UCHAR unsigned char

typedef
    VOID CALLBACK
    EVT_VIGEM_X360_NOTIFICATION(
        void* Client,
        void* Target,
        UCHAR LargeMotor,
        UCHAR SmallMotor,
        UCHAR LedNumber,
        void* UserData
    );

typedef EVT_VIGEM_X360_NOTIFICATION *PFN_VIGEM_X360_NOTIFICATION;
```

**Comment by emilio** [comment]
This is a libclang bug, https://bugs.llvm.org/show_bug.cgi?id=45919.

But we can workaround it in bindgen to some extent.

**Comment by DuckerMan** [comment]
I have not checked it yet, but thank you!
