### ISSUE TITLE
libclang not found when building using github actions for windows target

### ISSUE THREAD

**Issue by virtualritz** [rust-lang/rust-bindgen#1797]
I'm trying to use github actions to CI build my crate for several platforms. The `windows` target build fails on `bindgen` with:

```
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at C:\\msys64\\mingw64\\bin\\libclang.dll could not be opened: The specified module could not be found. (os error 126)"', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.54.0\src/lib.rs:1959:13
```

This works all fine for the `macos` and `ubuntu` targets btw.

**Comment by kulp** [comment]
Perhaps related: #918.

**Comment by emilio** [comment]
Yeah, you need to somehow install libclang on that windows machine.

**Comment by kulp** [comment]
@virtualritz, I do not think `bindgen` can do anything useful here except perhaps implement #918, so if you like that issue, you can lend your support to it.

**Comment by thomcc** [comment]
I think these machines supposedly do have clang on them, so I think there is probably more that can be done, as https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md mentions:

| Package | Version |
| :-- | :-- |
| ... | ... |
| Microsoft.VisualStudio.Component.VC.Llvm.Clang | 16.7.30310.162 |
| Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset | 16.3.29207.166 |
| ... | ... |
| Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang | 16.7.30310.162 |
| ... | ... |

However, I don't exactly know where the clangs in question are located, unfortunately.

**Comment by joshua-maros** [comment]
I'm trying to build a project on a Github runner and am running into the same problem. Doing some debugging with `ls` shows that there is a file `C:\msys64\mingw64\bin\libclang.dll` installed on the runner by default. However, I still get the same error as the original poster, which specifies this exact path in the error message.

**Comment by joshua-maros** [comment]
I don't know if this is significant, but the Github runners by default load the user's files onto the `D:` drive while all the preinstalled software is located on the `C:` drive.

**Comment by thomcc** [comment]
I was able to locate it ato some point inside `C:\msys64\mingw64\bin` (and some related stuff in `C:\msys64\mingw64\lib`), but never was able to make bindgen (or the clang-sys crate) load it, even trying various options.

Unsure why though, meant to follow up on it.

**Comment by joshua-maros** [comment]
Good news! :tada: I have found at least a partial solution.

It looks like on the Github runners, the libclang DLL relies on other DLLs in the same folder but that folder is never searched. The underlying error was one returned by Windows itself when trying to load the DLL which, annoyingly enough, can be caused both by a missing file and by missing dependencies. Adding the folder to `$Env:Path` seemed to resolve the problem. However, it only seems to work if added to the start of the path, which also means that MinGW will be used in place of MSVC, which is not acceptable in my case. I'll do some more investigation to see if this can be easily worked around.

For future Googlers, the program that ended up tracking down the problem was [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon). Basically it shows you all the interactions between applications and the kernel, including those extra DLLs that the program tried unsuccessfully to load. I didn't thoroughly look through the logs as there was a lot of information, but some examples of culprits were things like `libLLVM.dll` and `winpthread.dll`.

**Comment by saschanaz** [comment]
I had to add this step:

```
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
```

No idea why this is needed, though.

**Comment by KyleMayes** [comment]
I have added the Visual Studio LLVM component directory to the search paths used by `clang-sys` on Windows and tested it on my Windows machine. These changes are part of `clang-sys` `v1.1.0` which also includes Clang 11 support.

This should hopefully remove the need for users relying on the VS LLVM component to manually set the `LIBCLANG_PATH` environment variable.

**Comment by KyleMayes** [comment]
Addendum:

I previously created a custom GitHub Action (https://github.com/KyleMayes/install-llvm-action) which can be used to easily install any version of LLVM + Clang on all the operating systems supported by GitHub Actions. I use this action for testing the `clang-sys` and `clang` crates so it should also work with crates that depend on one of those crates like `bindgen`.

If people are having trouble getting Clang on their GitHub Action runners, they might want to check out that action.

**Comment by lovasoa** [comment]
For me the following worked : 

```yaml
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
    - name: Set LIBCLANG_PATH # see https://github.com/rust-lang/rust-bindgen/issues/1797
      run: echo "LIBCLANG_PATH=C:\msys64\mingw64\bin" >> $env:GITHUB_ENV
      if: matrix.config.os == 'windows-latest'
```

<details>
> I had to add this step: [...] (@saschanaz)

When I tried that, it failed with : 
```
Run echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
Get-Command: D:\a\_temp\b32fd303-37e7-49c6-b0fb-06fd5884522b.ps1:2
Line |
   2 |  echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $e …
     |                         ~~~~~~~~~
     | The term 'clang' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.

Error: Process completed with exit code 1.
``` 

</details>

**Comment by saschanaz** [comment]
Ah yeah, that means you didn't install LLVM yourself: https://github.com/marketplace/actions/install-llvm-and-clang
