### ISSUE TITLE
Interaction of whitelist and opaque 

### ISSUE THREAD

**Issue by remysucre** [rust-lang/rust-bindgen#1804]
It's not clear from the doc how `whitelist*` interacts with `opaque`. If a type is marked both as whitelist and opaque, which takes precedence? What about types transitively marked? Or is there different behavior depending on the order of the method calls? From what I tried it seems `opaque` overwrites `whitelist` regardless of order. Happy to help update the doc if someone clarifies this.

**Comment by emilio** [comment]
Whitelisted only tells whether it will appear in code generation. Opaque changes the result of the code generation... I don't _think_ making something opaque auto-whitelists it.

So basically, opaque should always have an effect, but the two flags are somewhat independent.

**Comment by emilio** [comment]
Clarifying this in the docs would be useful, I think :)
