### ISSUE TITLE
Consider deprecating whitelist / blacklist APIs

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust-bindgen#1812]
(And replace them with some with more inclusive terms than those).

I'm not a native English speaker so help with naming would be appreciated... Blocklist / Allowlist? Something else?

**Comment by kulp** [comment]
[Someone at Chromium / Google suggested "allow"/"block"](https://bugs.chromium.org/p/chromium/issues/detail?id=981129#c16). "Allow" and "Block" have the (somewhat trivial) nice property that they are the same length as each other and as "White" and "Black" so it would not mess up alignment to do a global replacement, if we do this.

Does `bindgen` have an existing deprecation policy / process ?

**Comment by kulp** [comment]
I guess I did not really address how to form the whole words -- "allowlist" and "blocklist" seem fine, but I would like to hear others' opinions.

**Comment by jlucangelio** [comment]
We're using both allowlist (no space) and allow-list (dash) and blocklist (no space) and block-list (dash) in Chromium OS.

(Chiming in because these are the last uses of white/blacklist in https://github.com/google/minijail, which I was hoping to clean up: https://github.com/google/minijail/blob/master/rust/minijail-sys/lib.rs)

**Comment by wokecanary** [comment]
I understand [replacing internal occurrences of "whitelist" with more descriptive terms](https://github.com/rust-lang/rust/pull/74127), but this? Many many crates [depend on `bindgen`](https://crates.io/crates/bindgen/reverse_dependencies). They'll all have to be "fixed".

Rust's community consists almost exclusively of smart people. How so many of them became convinced to spend time on this (and make others spend their time on it too) is beyond me. It's quite depressing, to be honest.

**Comment by tmfink** [comment]
@wokecanary I think we can avoid breakage by deprecating the current names and introducing new ones.

Whether we remove the deprecated names at a later release is a separate (independent) matter.

**Comment by emilio** [comment]
Right, the idea would be to mark the current APIs as deprecated and come up with better names for them. At some point in the future we can ideally remove the deprecated ones, but as @tmfink said that's a totally different matter.

**Comment by antiRadical** [comment]
Please don't spend time on this. Blacklist and whitelist have never been racist words. We can use our time for more meaningful things that have real impacts.

**Comment by LoganDark** [comment]
> (And replace them with some with more inclusive terms than those).

Personally I see no point to this. This whole "change every software term because diversity!" movement is purely political and I don't feel like Rust should have to be impacted by this. Other, more popular languages (and even platforms like GitHub) are taking the hit for us.

Whitelists and blacklists don't have anything to do with race/ethnicity/etc., so I don't see the point in removing every reference to "white"/"black" just because some people are sensitive to any use of those words (even if they're completely innocent).

**Comment by shadowcat-mst** [comment]
allowlist and blocklist are clearer terms, so adding those and encouraging people to use them will, overall, eventually make for better code at minimal cost.

also, frankly, the alternative is "keep having this argument every six months into the indefinite future" which will waste far more developer time than adding the new names and deprecating the old ones.

**Comment by TheButlah** [comment]
I never perceived the terms whitelist or blacklist to have anything to do with race. But maybe that's just my perspective, and doesn't translate to others.

I see no reason that deprecating would do any harm to anyone - the deprecated terms don't even need to be removed, as the mere fact that they are deprecated will cause people to use the non-deprecated versions and the old terms will pop up less frequently, which is the intended goal.

That being said, is there any evidence that these terms are offensive? I ask not to be contrarian, but I genuinely didn't perceive them that way and wouldn't expect someone else to. Does rust have any guidelines for what the threshold of complaint is for a word to be considered non-inclusive? Is there any historical context to other uses of the terms that could shed light on why they might be offensive? For example, were there literal white lists and black lists during segregation, and that is what the technical terms were inspired by?

**Comment by saschanaz** [comment]
https://github.com/rust-lang/rust/pull/74127 and https://github.com/rust-lang/rust/pull/74150 removed *list words altogether. Since there already is `hide_type` as an alias, it sounds like an option to me.

**Comment by LunarLambda** [comment]
I'd be heavily in favour of this too. For what it's worth, deprecating and renaming of functions has precedent in `std`. ([[1]](https://doc.rust-lang.org/stable/std/primitive.str.html#method.lines_any), [[2]](https://doc.rust-lang.org/stable/std/primitive.str.html#method.trim_left), [[3]](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.connect))

**Comment by hlopko** [comment]
Hi all, I'll try to fix this issue.

**Comment by emilio** [comment]
Thank you!

**Comment by JackRedstonia** [comment]
I do not mind this kind of change, as it isn't a breaking one, but IMO at least you replace those words with something clear, easy to understand, not awkward to read and already from the English dictionary.

`filter` could have been a good candidate. But well, the related PR is already merged.

**Comment by LunarLambda** [comment]
allow[list] / ban[list]

or, if you'd like both words to be the same length:
allow/block or accept/reject

**Comment by kulp** [comment]
> `filter` could have been a good candidate

I sympathize with the desire to use dictionary words, and in retrospect, `blocklist` sounds like a list of squares. But the old terms were unambiguously nouns, whereas `filter` can be a noun or a verb. @JackRedstonia, can you explain how you would use `filter` to meet both sides of the need, both for allowing and blocking?

I think a common problem in cases like this one is that a superior solution seems easier than it is.

Regardless, I think we can probably consider this to have been closed by #1990. If someone thinks there is more work to be done, please elaborate.

**Comment by JackRedstonia** [comment]
I have just got time to look at code changes in #1990. As it is terminology used in public, exposed interfaces, IMO it is best to use `ban`/`permit`. The ideal solution is to not try to cram `...list` into here. Try "Banning types for binding generation" for example.

If you want an example, please see that PR tamird opened on the Rust compiler. It is merged, it is perfect, no made-up words by a bunch of mad apologists.

**Comment by kulp** [comment]
@JackRedstonia, I agree that making up words is not good when clear alternatives exist, and I think the alternatives you and others pointed out are superior, maybe even in every way. [When I previously said](https://github.com/rust-lang/rust-bindgen/issues/1812#issuecomment-647254408):

> "allowlist" and "blocklist" seem fine

I had not given the implications of those specific word choices deep thought, and I expected alternative opinions to crop up soon thereafter. That is a reminder for me to avoid staking out a position, however weakly held, unless I can give it a positive rationale.

At any rate, I do not feel that this particular issue's resolution was rushed, just that this particular forum is little-trafficked enough to have avoided gleaning enough positive contributions "in time," so I guess we got a little unlucky that some of the later feedback was not just a bit earlier. If you see other lessons to be learned, feel free to share.

**Comment by dvc94ch** [comment]
well the reason for not jumping on the woke wagon is because in a few years when they fall on their noses we'll have to change everything back in order to avoid shame. why might you feel shame in a few years? because claiming that the words whitelist and blacklist are offensive to black people is indeed racist.

**Comment by peter9477** [comment]
Throwing in two cents more, I was confused by "blocklist", not because of the "squares" interpretation but because of the "groups of things" interpretation.  So that's at least three possible connotations for "block".  I would have preferred "banlist" or, better yet as there is precedence, "denylist".  There have long been /etc/hosts.allow and /etc/hosts.deny files in Linux, and I think that precedent could have been followed instead.  Too late now, I assume?

**Comment by pvdrz** [comment]
I'd favor `allow`/`deny` but that sail has shipped now
