### ISSUE TITLE
Publish Cargo.lock in the crates.io package

### ISSUE THREAD

**Issue by lexxvir** [rust-lang/rust-bindgen#1827]
Please, consider publish `Cargo.lock` in the crate on the crates.io. It allows to have reproducible builds for the `bindgen` binary (old) releases.

My case:
I required to use bindgen version 0.51.0 due to old version of the rustc.

Currently when I build `bindgen` binary version 0.51.0 via `cargo install --version 0.51.0 bindgen` I got errors such as 
`error[E0433]: failed to resolve: use of undeclared type or module clang_Cursor_getMangling`

bindgen version 0.51.0 is locked to clang-sys 0.28.0 (according to Cargo.lock) but currently tries to use clang-sys 0.28.2 when I building bindgen. It seem `clang-sys` have incompatible changes between version 0.28.0 and 0.28.2.

**Comment by kulp** [comment]
I agree that `Cargo.lock` [is not in 0.51.0](https://docs.rs/crate/bindgen/0.51.0/source/), but [it is present in 0.53.0 and later](https://docs.rs/crate/bindgen/0.53.0/source/), so I am not sure what we can do about this for 0.51.0.

**Comment by lexxvir** [comment]
Hi @kulp,

Thanks for the tip. Seems 0.51.1 have `Cargo.lock` (it's build successfully) and generates the same bindings, so I just switch over.
