### ISSUE TITLE
IncompleteArrayField Ergonomics

### ISSUE THREAD

**Issue by ssbanerje** [rust-lang/rust-bindgen#1832]
This is not a bug report, its a feature request. 

It seems like the `__IncompleteArrayField` type could be replaced to make it much more ergonomic.

### Input C/C++ Header
```C
struct vfio_irq_set {
	__u32	argsz;
	__u32	flags;
#define VFIO_IRQ_SET_DATA_NONE		(1 << 0) /* Data not present */
#define VFIO_IRQ_SET_DATA_BOOL		(1 << 1) /* Data is bool (u8) */
#define VFIO_IRQ_SET_DATA_EVENTFD	(1 << 2) /* Data is eventfd (s32) */
#define VFIO_IRQ_SET_ACTION_MASK	(1 << 3) /* Mask interrupt */
#define VFIO_IRQ_SET_ACTION_UNMASK	(1 << 4) /* Unmask interrupt */
#define VFIO_IRQ_SET_ACTION_TRIGGER	(1 << 5) /* Trigger interrupt */
	__u32	index;
	__u32	start;
	__u32	count;
	__u8	data[];
};
```

### Bindgen Invocation

```Rust
let bindings = bindgen::Builder::default()
    .header(vfio_wrapper)
    .derive_debug(true)
    .impl_debug(true)
    .rustified_enum(r".*")
    .whitelist_type(r"^vfio_.*")
    .whitelist_var(r"^VFIO_.*")
    .whitelist_var(r"^PCI_.*")
    .generate()
    .expect("Unable to generate bindings");
```

### Actual Results
```rust
#[repr(C)]
#[derive(Debug)]
pub struct vfio_irq_set {
  pub argsz: __u32,
  pub flags: __u32,
  pub index: __u32,
  pub start: __u32,
  pub count: __u32,
  pub data: __IncompleteArrayField<__u8>,
}
```

### Expected Results
Based on the documentation available in the nomicon (https://doc.rust-lang.org/nomicon/exotic-sizes.html#dynamically-sized-types-dsts), I would expect the generated code to look like this:

```rust
#[repr(C)]
#[derive(Debug)]
pub struct vfio_irq_set<T: ?Sized> {
    pub argsz: u32,
    pub flags: u32,
    pub index: u32,
    pub start: u32,
    pub count: u32,
    pub data: T,
}
```

This code is much more ergonomic to use than the one generated by bindgen. 

For example, to create a new instance of this type, we can simply use safe rust

```rust
let vis = vfio_irq_set<[u8;16]> {
  argsz:  (std::mem::size_of::<vfio_irq_set>() + std::mem::size_of::<u8>() * 16) as u32,
  ...
  data: [0xea; 16],
}
```

Compared to the unsafe pointer wrangling required to deal with the code generated by bindgen

```rust
let size = std::mem::size_of::<vfio_irq_set>() + std::mem::size_of::<u8>() * 16;
let layout = Layout::from_size_align(size, std::mem::align_of::<Self>()).unwrap();
unsafe {
      let mut vis = alloc(layout) as *mut vfio_irq_set;
      (*vis).0.argsz = size as u32;
      let data = (*vis).data.as_mut_slice(16)
      ...
}
```

Then there is of course the deallocation as well.

**Comment by emilio** [comment]
While you're right that the current thing is not particularly ergonomic, I don't think your proposal quite works. Let's say you have a function in C that takes a `vfio_irq_set*` as an argument, or returning it. How would that work?

Also, this pushes the burden of getting the right alignment to the consumer. Suddenly if I do `vfio_irq_set<u64>` with your proposal, the type has a different alignment and is not the same when passed down to C.

Plus that means that all the functions taking and passing these objects need to become generic over arbitrary types...

**Comment by emilio** [comment]
per the above I don't think this is particularly actionable, but let me know / reopen if I'm wrong :)
