### ISSUE TITLE
Feature request: Drop trait deconstructor

### ISSUE THREAD

**Issue by Volker-Weissmann** [rust-lang/rust-bindgen#1841]
Consider the following C++ header:
```
class MyClass {
public:
	MyClass();
	~MyClass();
};
```
If you want to construct and destruct  a MyClass object, you would have to write
```
let mut val = MyClass::new();
val.destruct();
```
It would be nice if rust bindgen would add this:
```
impl Drop for MyClass {
	fn drop(&mut self) {
		unsafe {
			self.destruct();
		}
	}
}
```
Which would allow you to just write 
```
let val = MyClass::new();
```
which would call the constructor and destructor.

**Comment by emilio** [comment]
Yeah, this is basically https://github.com/rust-lang/rust-bindgen/issues/1840. See there why this is not done by default. We could these days I think, with that breaking change of making stuff a `ManuallyDrop` when we implement drop.

Let's dupe this against that issue as you filed it earlier.
