### ISSUE TITLE
bindgen takes like a minute per C++ struct & produces gigabytes of log output with debug logging enabled

### ISSUE THREAD

**Issue by LoganDark** [rust-lang/rust-bindgen#1845]
### Input C/C++ Header

wxWidgets header files. The complete set is about 12 MB in size, but I am only doing `wx/aboutdlg.h`. But they are actually C++ header files, so I `#include` it from a `wrapper.hpp` file.

### Bindgen Invocation

```rust
	let bindings = bindgen::Builder::default()
		.header("wrapper.hpp")
		.detect_include_paths(false)
		.clang_args(cxx_flags)
		.parse_callbacks(Box::new(bindgen::CargoCallbacks))
		.whitelist_type("wx.*")
		.opaque_type("std::.*")
		.generate()
		.expect("Couldn't make bindings!");
```

### Actual Results

After each struct found, for example this:
![image](https://user-images.githubusercontent.com/4723091/88523268-84f20700-cfac-11ea-9e94-6e9b55ad23de.png)

bindgen doesn't output anything for about a minute. It does this for every struct in the program. After the minute wait, here is how much output it produces for one struct:

![bindgen](https://user-images.githubusercontent.com/4723091/88524354-1150f980-cfae-11ea-86b9-31280ae0bbfb.gif)

It's so large, it doesn't even fit in CLion's scrollback buffer.

Here is how much memory the `cargo` process takes up after about 30 minutes of `bindgen` taking forever to chew through `wx/aboutdlg.h`:

![image](https://user-images.githubusercontent.com/4723091/88524509-43625b80-cfae-11ea-934a-bdea1cc0258f.png)

This causes my kernel's OOM killer to go mad and start killing things that probably should not be killed.

**Comment by emilio** [comment]
Are you running with `RUST_LOG=debug` or something? Otherwise I'm pretty sure all that stuff you're seeing shouldn't show up.

**Comment by LoganDark** [comment]
Yes, I explicitly enabled debug logging. I thought that was obvious.

**Comment by emilio** [comment]
Well, it kinda was but worth double-checking... We could probably turn a bunch of the `debug` logs into trace logs or such, and for super noisy stuff we could definitely trim it down...

I've mostly used debug logging for reduced test-cases for which all that extra info is helpful.

**Comment by LoganDark** [comment]
Okay so at logging level `info`, `bindgen` can chew through the entire 12 MB of header files in like 40 seconds.

**Comment by kulp** [comment]
How do we decide what the "right" amount of memory should be consumed when debug logging is enabled ?

**Comment by emilio** [comment]
Right... I think this is wontfix for now. Improvements to make verbose logging equally useful but more compact are welcome of course, but... :)
