### ISSUE TITLE
need command line flag for i32/i64 default macro constant types

### ISSUE THREAD

**Issue by chih-hung** [rust-lang/rust-bindgen#1865]
Android's build system does not use cargo nor the build.rs file. libsqlite3-sys calls bindgen in build.rs and uses ParseCallbacks to give macros a default i32 type instead of bindgen's default u32 type. The ideal way to import libsqlite3-sys into Android would be calling the bindgen binary and passing some flag to select the default i32 type.

I found in bindgen source the default_macro_constant_type function. I would like to add a new command line flag like --default-macro-constant-type so that the function will use i32 or i64 type instead of u32 or u64, when the values fit.

A pull request is created to show the proposed changes: #1863

**Comment by Lokathor** [comment]
@emilio the PR for this got merged, so this issue can be closed

**Comment by kulp** [comment]
Closed by #1863 as noted by @Lokathor. Thanks.
