### ISSUE TITLE
Generating from build.rs and include! macro

### ISSUE THREAD

**Issue by bugproof** [rust-lang/rust-bindgen#1869]
The tutorial https://rust-lang.github.io/rust-bindgen/tutorial-4.html makes use of include! macro but apparently it's still not well supported in rust plugins/extensions.

https://github.com/intellij-rust/intellij-rust/issues/1908

Is it fine if we generate the bindings in src/ directory from build.rs and just do `pub mod bindings;` inside `src/lib.rs` ? Like:

```rust
bindings
        //.write_to_file(out_path.join("bindings.rs"))
        .write_to_file("src/bindings.rs")
        .expect("Couldn't write bindings!");
```

and inside lib.rs:

```rust
pub mod bindings;
```

instead of 

```rust
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
```

What's the benefit of writing to OUT_DIR?

**Comment by kulp** [comment]
> What's the benefit of writing to OUT_DIR?

It may be that what your alternative can work -- but [`cargo` certainly says not to do it](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) :

> Build scripts may save any output files in the directory specified in the `OUT_DIR` environment variable. Scripts should not modify any files outside of that directory.

I personally think it would often be confusing to have build scripts (or any automation) generating files in the same directory as source-controlled files, particularly when there is a normal expectation for build outputs to appear in `OUT_DIR` as documented and precedented.

That said, your solution is clever and it makes me think. Maybe it is not as bad an idea as I suppose.

**Comment by emilio** [comment]
Modifying the src directory will complain when you do `cargo publish`.

Another reason to write to `OUT_DIR` is when you compile to multiple architectures. `OUT_DIR` will point to something different depending on the architecture, but that will not be true of just writing to the srcdir.

Writing to `OUT_DIR` is the right thing to do. You definitely can avoid doing so if you want, but you're on your own then :)

**Comment by bugproof** [comment]
@emilio the problem with `OUT_DIR` is that it's not widely supported right now. IntelliJ Rust shows no autocompletion for files included with `include!`. Don't know how rust-analyzer handles this now.

**Comment by kulp** [comment]
@bugproof, that means that some tools may need to be improved. It does not really make sense to break a `cargo` rule to make some IDE work better in a narrow case, while breaking other cases.

You are certainly free to not use `OUT_DIR` yourself.
