### ISSUE TITLE
The target passed to clang is wrong for aarch64-apple-darwin

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust-bindgen#1871]
bindgen passes the rust target unchanged, but unfortunately, in the case of aarch64-apple-darwin, the clang target is different, and clang doesn't recognize aarch64-apple-darwin at all. The right target to use is arm64-apple-darwin.

**Comment by kulp** [comment]
Was this issue possibly fixed by d55b063e8010a3acf5c2a549a1d2d7c238286314 ?

**Comment by glandium** [comment]
Only when building on an Apple Silicon DTK with an arm64 rustc.

**Comment by simlay** [comment]
#1211 seems like this could be a related issue.

**Comment by glandium** [comment]
Yes, it's the exact same thing.

**Comment by emilio** [comment]
Ok, let's close as a dupe of #1211 and fix it there. Thanks @glandium!
