### ISSUE TITLE
--help message displays poorly in 80-column terminals

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-bindgen#1873]
The help message displays very poorly in 80-column terminals. If possible, the message printing should be terminal-size aware.

**Comment by LoganDark** [comment]
I believe clap 3 has this functionality, but bindgen is using clap 2 at the moment

**Comment by emilio** [comment]
There doesn't seem to be any clap 3 in the registry?

**Comment by emilio** [comment]
(But anyhow patches more than welcome :))

**Comment by LoganDark** [comment]
@emilio https://docs.rs/clap/3.0.0-beta.2/clap/index.html

**Comment by pvdrz** [comment]
Given that clap 4 is releasing soon-ish (https://epage.github.io/blog/2022/09/clap4/). Migrating from clap 2 would be a good move because it is entering maintenance mode.

**Comment by pvdrz** [comment]
We're using clap 4 so this shouldn't be an issue anymore.
