### ISSUE TITLE
__BindgenUnionField and __IncompleteArrayField are UB according to Stacked Borrows model.

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust-bindgen#1892]
Generated helpers `__BindgenUnionField` and `__IncompleteArrayField` are impossible to use without invoking UB according to the [Stacked Borrows](https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md) model.

The "short" explanation for why is that raw pointers created from a '&T' can only be used to access memory inside the T. The pointers "remember" that they come from a &T. I don't think I fully grasp Stacked Borrows to give more detail though :sweat: 

These two structs are zero-sized, so methods taking &self are forbidden to read memory "outside" self, even through pointer casts.

Quick [playground demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0e4b26415dc2e8eea7ef71b6db579841). To see the UB, run MIRI from the 'Tools' menu.

There's a possible workaround that works by calculating the offset of the member, and using it to construct a new "sanitized" pointer from the "original" pointer, that's not "tainted" by coming from a reference. See `slice_from_flexarray` in the playground above.

**Comment by Dirbaio** [comment]
See here for more context: https://github.com/rust-lang/unsafe-code-guidelines/issues/134#issuecomment-627609346

**Comment by emilio** [comment]
Hmm... sure, though I don't get how `slice_from_flexarray` is also not UB. It seems you're just fooling miri. For example this version of `as_slice` doesn't make miri complain:

```rust
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        let ptr = self as *const _ as usize;
        ::std::slice::from_raw_parts(ptr as *const u8 as *const T, len)
    }
```

I don't think that's fundamentally different though.

**Comment by emilio** [comment]
cc @ralfjung in case the above is a miri bug or what not...

But TLDR I think this should work as is to be fair. If there is a safer way to do it I'm all ears, or if the version of `as_slice` above is not UB somehow, I'd also love to know why. But other than that this doesn't seem actionable on bindgen right now.

**Comment by RalfJung** [comment]
rust-lang/unsafe-code-guidelines#134 is indeed the right reference. This is not a Miri bug, it is working as designed, but it might be a weakness of the design. Whether it is possible to resolve that without giving up many useful optimizations is still an open question. 

The keyword "flexarray" reminds me of a few discussions I had with @retep998 who I think developed a sound API for C-style flexible arrays. I think their approach was very similar to `slice_from_flexarray`. The key is that you want to make sure you have a pointer with the right provenance, ensuring it can access the entire array, not just the zero-sized pseudo-element at the beginning.

**Comment by RalfJung** [comment]
Also, could this code entirely avoid the use of references once https://github.com/rust-lang/rust/issues/73394 is stable? That is probably a much more sane solution that the "sensitization" trick.

**Comment by retep998** [comment]
For reference this is the API I use for working with such variable sized structs: https://github.com/retep998/wio-rs/blob/master/src/vsb.rs

**Comment by Easyoakland** [comment]
@emilio 
> Hmm... sure, though I don't get how `slice_from_flexarray` is also not UB. It seems you're just fooling miri. For example this version of `as_slice` doesn't make miri complain:
> 
> ```rust
>     #[inline]
>     pub unsafe fn as_slice(&self, len: usize) -> &[T] {
>         let ptr = self as *const _ as usize;
>         ::std::slice::from_raw_parts(ptr as *const u8 as *const T, len)
>     }
> ```
> 
> I don't think that's fundamentally different though.

Maybe something changed in since you wrote this, but [that is not](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f7200e49a2711bf46c3992c3056c6f29) not accepted by miri
> trying to retag from <wildcard> for SharedReadOnly permission

while the original sanitized pointer solution is accepted by miri.

**Comment by RalfJung** [comment]
Note that when there is the "warning: integer-to-pointer cast", even if Miri does not complain, that doesn't mean much. So if your "sanitized pointer solution" involves int2ptr casts, it can't really be tested in Miri.

Also this is a 4-year-old closed PR, not a suitable place for discussion. Not sure what you're trying to achieve but I suggest opening a new issue if there's something that should/could be improved.

**Comment by emilio** [comment]
Yes, please. FWIW this is effectively https://github.com/rust-lang/unsafe-code-guidelines/issues/256 which is still open.
