### ISSUE TITLE
Deduplicating generated code automatically

### ISSUE THREAD

**Issue by ethindp** [rust-lang/rust-bindgen#1895]
So I'm sorry if I should put this somewhere else. I wasn't quite sure though, so I thought I'd submit this here.

I'm writing bindings for the FMOD audio library. Thus far, I've got it generating bindings for the main FMOD API and the FSBank API, however I want to add the FMOD studio API as well. The problem is that fmod_studio.h includes fmod.h, which I've already got. Is there a way I can tell bindgen to ignore that header or some way I can get it to use my already defined code to avoid code duplication?

**Comment by emilio** [comment]
Sorry for the massive lag here. You can use the blacklist APIs to avoid generating types you already have, and you can use `raw_lines` to introduce those into scope, so I imagine something like this would work:

```
raw_line("use fmod_sys::*;")
blacklist_type("something_from_fmod_sys");
```
