### ISSUE TITLE
derive_debug(false) still derives Debug for rustified Enum

### ISSUE THREAD

**Issue by trinity-1686a** [rust-lang/rust-bindgen#1899]
### Input C/C++ Header

```C
enum boolean { false, true };
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
        .header("wrapper.h")
        .default_enum_style(bindgen::EnumVariation::Rust{ non_exhaustive: false })
        .derive_debug(false)
        .impl_debug(false)
        .no_debug(".*")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
```

### Actual Results

```Rust
/* automatically generated by rust-bindgen 0.55.1 */

#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum boolean {
    false_ = 0,
    true_ = 1,
}
```

### Expected Results

```Rust
#[repr(u32)]
#[derive(Copy, Clone, PartialEq, Eq, Hash)] // <= no Debug
pub enum boolean {
    false_ = 0,
    true_ = 1,
}
```
### Use case :
I'm trying to build some bpf program to run inside Linux kernel. It's pretty restrictive on what is allowed, and apparently having Debug implemented break something related to the "only one ELF section" rule (pretty much anything related to strings does).
I tried as hard as I could to tell Bindgen to not derive/generate Debug, but apparently it still does for enumerations. Stripping off all derive Debug fixes loading the program, but I feel like `derive_debug(false)` or `no_debug(".*")` should already have done that.

**Comment by emilio** [comment]
Fix at https://github.com/rust-lang/rust-bindgen/pull/1900, thanks for filing it!
