### ISSUE TITLE
Backport BINDGEN_EXTRA_CLANG_ARGS to 0.47

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust-bindgen#1910]
Would it be possible to backport `BINDGEN_EXTRA_CLANG_ARGS` to 0.47.0? I have a project that needs it and currently I have to rely on ugly hack.

I'm willing to do the work, you will just have to create a new branch for me to PR into and publish the release. :)

**Comment by emilio** [comment]
Sure, if you give me a branch to pull from I can publish it.

**Comment by Kixunil** [comment]
Done in https://github.com/Kixunil/rust-bindgen/tree/v0.47.x

I also backported `rerun-if-env-changed` as they were somewhat related.

**Comment by Kixunil** [comment]
Ping?

**Comment by emilio** [comment]
https://github.com/rust-lang/rust-bindgen/commit/faeaba6ac8974dbf20df74322d2834d74fb14820 / https://github.com/rust-lang/rust-bindgen/releases/tag/v0.47.4

(Sorry, been swamped this week)

**Comment by Kixunil** [comment]
Thanks a lot!
