### ISSUE TITLE
Publish release that depends on cfg-if v1.0

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust-bindgen#1925]
Hi @emilio, can you publish a new release of bindgen that includes https://github.com/rust-lang/rust-bindgen/commit/84b5455f882e10e9ddaa001dc8207023d82cdd5f?

I'm trying to update all of my deps to be on cfg-if 1.0.

**Comment by lopopolo** [comment]
Currently a dep on bindgen pulls in two versions of cfg-if because libloading 0.6.5 depends on cfg-if 1.0.

**Comment by emilio** [comment]
Yup, will publish a release ASAP. I wanted to get #1846 and such in before, but I just pushed that and sent a small follow-up, so should be done today.

**Comment by emilio** [comment]
11ae35089e4748b7e2a6f50f6bef7709af72e724 (I removed the cfg-if dependency altogether)
