### ISSUE TITLE
Private C++ members generate bindings that are public.

### ISSUE THREAD

**Issue by SilensAngelusNex** [rust-lang/rust-bindgen#1926]
### Input C/C++ Header

```C++
class PubPriv {
  public:
    int x;
  private:
    int y;
};
```

### Bindgen Invocation

```rust
bindgen::Builder::default()
    .header("input.h")
    .clang_args(&["-x", "c++"])
    .generate()
    .unwrap()
```

### Actual Results

```rust
#[repr(C)]
pub struct PubPriv {
    pub x: ::std::os::raw::c_int,
    pub y: ::std::os::raw::c_int,
}
```

### Expected Results

```rust
#[repr(C)]
pub struct PubPriv {
    pub x: ::std::os::raw::c_int,
    y: ::std::os::raw::c_int,
}
```

Declaring `y` as `pub` lets Rust read `y` and construct a `PubPriv` when neither should really be allowed, as well as making it hard for tools to treat the two fields differently, like [autocxx issue 53](https://github.com/google/autocxx/issues/53) wants to do.

**Comment by emilio** [comment]
We have _some_ code to generate private fields that could be leveraged here.

**Comment by SilensAngelusNex** [comment]
I've been working on this and have a few questions about what the best end-state is.

1. A lot of the tests depend on the fact that private C++ Decls generate public fields/items. Should I gate making those fields/items private behind an option so that the default behavior doesn't change or is it fine to change the test expectations?
2. C++ lets you use private types in a public interface:
    ```c++
    class A {
      class B {
       public:
        void frob() {}
      };

     public:
      B b;
    };

    int main() {
      A a;
      a.b.frob();
    }
    ```
    If we generate the obvious thing here, rustc will tell us [not to leak private types](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=294639164ba389e0e0996655aa273771):
    ```rust
    pub struct A {
        pub b: A_B
    }

    struct A_B {}
    ```
     
    Should all generated types be public regardless of their C++ access specifier to keep rustc from complaining? Would we ideally do something more clever like only making the private inner types public if they _actually_ escape?

**Comment by emilio** [comment]
I think making all types public is probably ok. If we want to get smarter in the future then that can be improved upon but...

**Comment by emilio** [comment]
Then there's also the thing of what to generate for `protected` fields...

**Comment by EricMiddelhove** [comment]
Hello Everyone
in my code I have private fields, which are vectors, in a class which are generated into public fields in the bindings. I understand this thread that this currently is expected behavior.
Do you have advice on how to handle vectors in bindings until this is improved?

**Comment by pvdrz** [comment]
you can control the visibility of fields from the [`Builder`](https://docs.rs/bindgen/latest/bindgen/struct.Builder.html#method.default_visibility) or with the [`ParseCallbacks` API](https://docs.rs/bindgen/latest/bindgen/callbacks/trait.ParseCallbacks.html#method.field_visibility) to have more granular control

**Comment by EricMiddelhove** [comment]
It appears, that the ParseCallbacks Method "[field_visibility](https://docs.rs/bindgen/latest/bindgen/callbacks/trait.ParseCallbacks.html#method.field_visibility)(&self, _info: [FieldInfo](https://docs.rs/bindgen/latest/bindgen/callbacks/struct.FieldInfo.html)<'_>)" takes a FieldInfo struct as a parameter. FieldInfo is marked as non-exhaustive and does not implement a constructing function which makes it impossible to construct outside the crate it was defined in.
Is this expected or am I missing something in the documentation?

**Comment by pvdrz** [comment]
Yes, `FieldInfo` is non-exhaustive to future-proof it: If someone requires extra information about the fields to decide its visibility we would have to add a new field to `FieldInfo` and this could break some people's code if they pattern match it to extract all its fields.

You don't need to construct it as it is given to you as a parameter:
```rust
use bindgen::{
    callbacks::{FieldInfo, ParseCallbacks},
    Builder, FieldVisibilityKind,
};

#[derive(Debug)]
struct MyCallbacks;

impl ParseCallbacks for MyCallbacks {
    fn field_visibility(&self, info: FieldInfo<'_>) -> Option<FieldVisibilityKind> {
        // Mark any field called `foo` as private unconditionally.
        if info.field_name == "foo" {
            Some(FieldVisibilityKind::Private)
        } else {
            None
        }
    }
}

fn main() {
    Builder::default()
        .parse_callbacks(Box::new(MyCallbacks))
        ...
}
```

**Comment by EricMiddelhove** [comment]
Ah! Perfect I misunderstood the documentation 🙈. Thank you for the clarification 👍🏼

**Comment by pvdrz** [comment]
Sure, next time it would be better if you open a new discussion or a new issue linking to the closed issue instead.
