### ISSUE TITLE
Allow to use symbols from another sys crate

### ISSUE THREAD

**Issue by gdesmott** [rust-lang/rust-bindgen#1929]
I have 2 C libraries, let's call them `A` and `B` and I'm generating low levels bindings for both using `bindgen`. `B` is using `A`'s symbols in its API. As a result the bindings generated in `B-sys` are using `B` namespaced types instead of `A`'s.

It would be great to be able to ask `bindgen` to depends on `A-sys` and use those symbols, saving users to cast between `B::some_type` to `A::some_type` when using API from `A-sys`.

**Comment by emilio** [comment]
This can work already, you can `blacklist_type("some_type")` then `raw_line("pub use B::some_type;");` or such. Does such a thing not work?

**Comment by gdesmott** [comment]
I'm already whitelisting B's symbols but A's are still generated anyway. Explicitly blacklisting them does not help either.

[Here is B's build.rs](https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/blob/master/pipewire-sys/build.rs#L21) and [here is the generated bindings file](desmottes.be/~cassidy/files/brol/bindings.rs).
As you can see, `spa` symbols (A), such as `spa_hook`, are still generated.

**Comment by emilio** [comment]
> I'm already whitelisting B's symbols but A's are still generated anyway. Explicitly blacklisting them does not help either.

So something like `blacklist_type("spa_.*")` in B's build.rs still generates `spa_hook` and co? That would be unexpected.

**Comment by gdesmott** [comment]
My mistake it does work! I was assuming that white listing would be enough to not generate those and when I tried black list I forgot the `.` in the regexp.

Thanks a lot for your help @emilio !

**Comment by emilio** [comment]
Ah, great, glad it works :-)
