### ISSUE TITLE
Possible improvement in runtime efficiency of generated `libloading` wrapper type impl

### ISSUE THREAD

**Issue by Cldfire** [rust-lang/rust-bindgen#1938]
[`libloading`'s docs for the `get` method](https://docs.rs/libloading/0.6.5/libloading/struct.Library.html#method.get) mention the following:

> The symbol may not contain any null bytes, with an exception of last byte. A null terminated symbol may avoid a string allocation in some cases.

This implies that passing a null-terminated symbol is recommended.

However, bindgen [currently doesn't generate](https://github.com/rust-lang/rust-bindgen/blob/master/tests/expectations/tests/dynamic_loading_template.rs#L23-L24) null-terminated symbols:

```rust
        let foo = __library.get("foo".as_bytes()).map(|sym| *sym);
        let foo1 = __library.get("foo1".as_bytes()).map(|sym| *sym);
```

**Comment by emilio** [comment]
https://github.com/rust-lang/rust-bindgen/pull/1939
