### ISSUE TITLE
Different data type generation on different platform i.e. Win & Linux

### ISSUE THREAD

**Issue by AWADHAMBIKA** [rust-lang/rust-bindgen#1967]
I ran the below command on both windows and Linux:
bindgen wrapper.h > src/lib.rs

wrapper.h code:
#include "sqlcli1.h"

Code generated in Windows:
pub type SQLHANDLE = *mut ::std::os::raw::c_void;

Code generated in LINUX:
pub type SQLHANDLE = SQLINTEGER;

Now because of this, the RUST code written in windows is not working on Linux as the datatype has changed completely.
Ideally the code generated should be same across platform rite?

**Comment by emilio** [comment]
What is the definition of this type on the header file? Chances are this is just working as intended.

**Comment by pvdrz** [comment]
I tried to look for this `sqlcli1.h` file just to be sure and it seems to be part of an IBM product that I don't have access to. I concur with Emilio here and think this is expected behavior if `sqlcli1.h` has platform dependent definitions for `SQLHANDLE`.
