### ISSUE TITLE
support for dynamic linking (or docs for it if there is a hidden option somewhere)

### ISSUE THREAD

**Issue by grandopener** [rust-lang/rust-bindgen#1974]
I want to dynamically link with a library with a C interface.  Note that I do _not_ want dynamic loading (i.e. `libloading::Library::new(...)`.  I want dynamic linking.  For example by hand I would write something like this:

    #[link(name = "my_library")]
    extern "C" {
        pub fn do_the_thing();
    }

I don't see any way to add the `#[link(...)]` annotations with bindgen currently.

**Comment by emilio** [comment]
So there's multiple ways to do this:

 * The `#[link]` attribute doesn't have to be on the extern block that declares the function. So just `#[link(name = "my_library")] extern "C" {}` anywhere in your crate would have the same effect.
 * You can also use `cargo:rustc-link-lib` from the build script.

Let me know if neither of those work for some reason and we could try to add something to bindgen. I haven't dug the history but IIRC last time this came up the answer was that it was not really needed.

Thanks for the report :)
