### ISSUE TITLE
Char in struct generates different type then param char

### ISSUE THREAD

**Issue by starsoccer** [rust-lang/rust-bindgen#1976]
### Input C/C++ Header

```C++
typedef unsigned int APICALL ;
typedef struct TestStruct{
	char                 name[1024];
} TestStruct;
int APICALL open(
    char name[1024]
);
```

### Actual Results
```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TestStruct{
    pub name: [::std::os::raw::c_char; 1024usize],
}
extern "C" {
    pub fn open(name: *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
```

### Expected Results

```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TestStruct{
    pub name: [::std::os::raw::c_char; 1024usize],
}
extern "C" {
    pub fn open(name: *mut [::std::os::raw::c_char; 1024usize]) -> ::std::os::raw::c_int;
}
```

**Comment by emilio** [comment]
The actual results are the correct results, afaict.

C doesn't have guarantee about the size of the input pointer of a function, regardless of how you declare it, and a pointer to an array is a different thing than a pointer to a char.

See https://stackoverflow.com/questions/1461432/what-is-array-to-pointer-decay etc.

**Comment by kulp** [comment]
I think @emilio is correct. I thought I remembered that in C99, the type of the parameter to `open` would be an array (with a size), but I had forgotten that in order to get that behavior you have to [use a `static` keyword](https://hamberg.no/erlend/posts/2013-02-18-static-array-indices.html) :
```c
int APICALL open(
    char name[static 1024]
);
```
@starsoccer, I have not tried this with `bindgen`, but maybe it would help.

**Comment by starsoccer** [comment]
Thanks @kulp sadly that didnt work it gets converted to `*mut ::std::os::raw::c_char` so I think I will need to do some reading on bindgen some more to figure out how to either make a custom type that I can plug in here

**Comment by emilio** [comment]
It's not clear to me what you're trying to do here, but a function like the one in the OP (with `*mut [c_char; 1024]`) wouldn't behave correctly, it'd have the wrong ABI. You can enforce whatever size you want on a wrapper function:

```
fn open(path: &[c_char; 1024]) -> c_int {
    bindings::open(path.as_ptr())
}
```

Or such

**Comment by starsoccer** [comment]
My issue is that prior to calling this function I have to call another function that returns `TestStruct` in my example. I then need to take name on `TestStruct `and provide it to open but currently I cant because the types are mismatched.

`name` on `TestStruct` is `[i8; 1024]` but open is expecting just `i8` so rust complains and says ` expected `i8`, found array `[i8; 1024]``

Some more code in case it makes the issue clearer:
`        
let mut device_name: [i8; 1024] = device_name.clone(); 
let mut device_name_ptr: *mut [i8; 1024] = &mut device_name as *mut [i8; 1024];
let mut data: *mut *mut std::os::raw::c_void = mem::uninitialized();

let result = testlibrary::open(device_name_ptr);
`

**Comment by emilio** [comment]
You just need to pass `device_name.as_ptr()` rather than `&mut device_name as *mut [i8; 1024]`

**Comment by starsoccer** [comment]
Sadly that doesnt work as rust tells me its expecting a `*mut ::std::os::raw::c_char` and then rust wont compile due to types differing in mutability

**Comment by emilio** [comment]
`device_name.as_mut_ptr()` then, but the C function should probably take a `const` argument :)

**Comment by starsoccer** [comment]
Ah cool that worked great thanks.

Yeah if I could change the C function I would sadly I dont have much choice ;)
