### ISSUE TITLE
Derive `Debug` is not generated for structs with large array fields (len() > 32) (need to add new rustc target)

### ISSUE THREAD

**Issue by DmitrySamoylov** [rust-lang/rust-bindgen#1977]
Hi! If my struct contains large arrays, then `Debug` is not being generated. However if I add `Debug` manually, it compiles and runs just fine.

### Input C/C++ Header

```C++
typedef struct {
    char f[33];
} A;
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.56.0 */

#[repr(C)]
#[derive(Copy, Clone)]
pub struct A {
    pub f: [::std::os::raw::c_char; 33usize],
}

...
```

### Expected Results

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct A {
    pub f: [::std::os::raw::c_char; 33usize],
}
```

**Comment by jplatte** [comment]
Arrays with more than 32 elements only implement `Debug` [since 1.47](https://caniuse.rs/features/array_gt_32_impls).

**Comment by jplatte** [comment]
The latest `--rust-target` supported being `1.47`, I guess this won't be supported even with `--rust-target nightly`.

**Comment by emilio** [comment]
If Rust supports this now we should add a new rustc version to the code and restrict the limitations to older versions of rust.

**Comment by jplatte** [comment]
I've already done the first part, I'll try to get to the latter soon or post a WIP PR with some notes if I don't find the time to finish it.
