### ISSUE TITLE
Request for patch release for fix to #1771

### ISSUE THREAD

**Issue by Dessix** [rust-lang/rust-bindgen#1978]
Hello- [Mumble-sys](https://crates.io/crates/mumble-sys) has a dependency on Rust-Bindgen and the latest version requires the fix that was merged from #1771 (fixed in 51778893c4cb18eb11cbfe83a72046f7cb0f3eac) in order to build, and I can't publish to Crates.io off of a git tag; As the Readme suggests: @emilio, can you release a patch version?

**Comment by emilio** [comment]
There were other breaking changes (very minor, but breaking after all) landed after v.0.56.0 but before that. Do you need a patch release or is a 0.57.0 release with current master enough?

Thanks

**Comment by Dessix** [comment]
Any new version works 👍

**Comment by Dessix** [comment]
Any chance of a rough ETA on that, @emilio? I have a few users trying to make use of my library and am trying to determine if I should build a workaround in the meantime.

**Comment by emilio** [comment]
https://github.com/rust-lang/rust-bindgen/commit/5ca2fc7a0221cacde41fd60b0ce485ee5ab8dac3, sorry for the lag (exams)
