### ISSUE TITLE
Support exporting re-exported types (those with pub use)

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rust-bindgen#2016]
I'm trying to create C bindings for a `lib.rs` file that has a `pub use somecrate::SomeEnum;` that I import and I would like to be exported as well.

I can't seem to get that case to be supported. I tried adding `include = [ "SomeEnum" ]` to the `cbindgen.toml` without success. I tried to `type SomeEnum = somecrate::SomeEnum;` but then it creates a typedef referring to itself (:sweat_smile:).

**Comment by emilio** [comment]
Are you using `parse_deps = true`? if not, that probably fixes it.

**Comment by emilio** [comment]
Well, wrong project? This issue should be moved to https://github.com/eqrion/cbindgen, aiui. What you do should be supported, let me know if parse_deps doesn't work and I can look deeper into it there.

**Comment by stevenroose** [comment]
Ah yeah that worked, sorry I didn't close the issue. I initially thought
parse_deps would expose all of the eligible types in all dependencies 😅

**Comment by emilio** [comment]
If you submit a clarification to the documentation that'd be incredibly helpful. Glad it worked!

**Comment by stevenroose** [comment]
Would that be in this repo or in cbindgen?
