### ISSUE TITLE
Padding not generated

### ISSUE THREAD

**Issue by danobi** [rust-lang/rust-bindgen#2050]
### Input C/C++ Header

Apologies for the `#include`s, not sure how to avoid it here.

```C
#include <stddef.h>
#include <stdbool.h>

struct bpf_object_open_opts {
        size_t sz;
        const char *object_name;
        bool relaxed_maps;
        bool relaxed_core_relocs;
        const char *pin_root_path;
        int attach_prog_fd;
        const char *kconfig;
};
```

### Bindgen Invocation

```
$ bindgen input.h --with-derive-default --no-layout-tests
```

### Actual Results

```
/* automatically generated by rust-bindgen 0.58.1 */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub type size_t = ::std::os::raw::c_ulong;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Default, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bpf_object_open_opts {
    pub sz: size_t,
    pub object_name: *const ::std::os::raw::c_char,
    pub relaxed_maps: bool,
    pub relaxed_core_relocs: bool,
    pub pin_root_path: *const ::std::os::raw::c_char,
    pub attach_prog_fd: ::std::os::raw::c_int,
    pub kconfig: *const ::std::os::raw::c_char,
}
impl Default for bpf_object_open_opts {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
```

### Expected Results

If you take the bindgen generated struct and also create a packed version (see https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=748d6dc00a88d3218bdb0bcf5912d667 ) and then print the sizes of regular and packed, there's a size difference. I think that means there's padding.

According to https://doc.rust-lang.org/stable/std/mem/fn.zeroed.html docs, `std::mem::zeroed()` on a struct with padding doesn't necessarily zero out the padding (which isn't very nice for libraries which do forward/backwards compat based on struct sizes.

Should there be padding generated for this struct? Or should the `default()` implementation be changed to actually zero padding?

**Comment by emilio** [comment]
We try to not generate padding when not needed. I think a simple fix would be to add an option to change `default()` to not use `zeroed()`, but instead use `uninitialized()` then zero the relevant size.
