### ISSUE TITLE
C javadoc comments are not Markdown-escaped, triggering `rustdoc` warnings

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust-bindgen#2057]
This comes up in Rust for Linux when generating the bindings for some C APIs that happen to have javadoc-like comments that end up being broken Markdown: https://github.com/Rust-for-Linux/linux/issues/323.

### Input C/C++ Header

```C
/**
 * vdso_data.cs[x].shift
 */
void f(void);
```

### Bindgen Invocation

```
$ bindgen f.h
```

### Actual Results

```rust
extern "C" {
    #[doc = " vdso_data.cs[x].shift"]
    pub fn f();
}
```

Which leads to `rustdoc` warnings such as:

```
warning: unresolved link to `x`
 --> f.rs:4:5
  |
4 |     #[doc = " vdso_data.cs[x].shift"]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
  = note: the link appears in this line:
          
          vdso_data.cs[x].shift
                       ^
  = note: no item named `x` in scope
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
```

### Expected Results

```rust
extern "C" {
    #[doc = " vdso_data.cs\\[x\\].shift"]
    pub fn f();
}
```

**Comment by emilio** [comment]
This is #1313 basically... I suspect the best path forward here is probably making sure we treat all doc comments as literal blocks of code (basically prepending triple-quotes or something) so that we don't mess up whitespace and other things people do on doc comments. There's some other discussion about this somewhere else, IIRC.

**Comment by pvdrz** [comment]
https://github.com/rust-lang/rust-bindgen/pull/2347 could provide a solution for this.

**Comment by chloekek** [comment]
> making sure we treat all doc comments as literal blocks of code

It would be nice to still offer the original behavior, in case comments were actually valid Markdown.

**Comment by pvdrz** [comment]
now that #2347 landed. This can be solved by implementing `ParseCallbacks::process_comments` to either wrap the comment in backticks:
```rust
#[derive(Debug)]
struct Cb;

impl ParseCallbacks for Cb {
    fn process_comment(&self, comment: &str) -> Option<String> {
        Some(format!("````\n{}\n````", comment))
    }
}
```
or parsing it with a javadoc parser (not sure if such thing exists in Rust)
