### ISSUE TITLE
size_t_is_usize(true) prevents generation of size_t definition (0.58.1)

### ISSUE THREAD

**Issue by Raekye** [rust-lang/rust-bindgen#2065]
### Input C/C++ Header

```C++
#include <stddef.h>
```

### Bindgen Invocation

```
$ bindgen input.h --size_t-is-usize --allowlist-type=size_t
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.58.1 */
```

### Expected Results
I thought the `--size_t-is-usize` just altered the definition of `size_t` rather than disabling its generation altogether. I couldn't find any clear documentation on this, but based on previous discussions about this flag it seemed to me that the definition should still be generated. Is this intended (since that flag means we can trivially define it ourselves)?

**Comment by emilio** [comment]
I think this is intended, since the point of `size_t-is-usize` is that you create more portable bindings by not relying on the platform definition.

I think it should be easy-ish to fix if we wanted to generate it, but unless there's a strong usecase for this I tend to close this, wdyt?

**Comment by Raekye** [comment]
It's good with me if it's intended - this "issue" was more of a question about the intended behaviour. 

Maybe could add to the documentation here - https://docs.rs/bindgen/0.58.1/bindgen/struct.Builder.html#method.size_t_is_usize - I see how it should be read now but when I originally read "Set whether `size_t` should be translated to `usize` automatically" I thought bindgen would still create a type alias. But maybe it's just me
