### ISSUE TITLE
Linux kernel - dealing with struct members being moved into unions

### ISSUE THREAD

**Issue by raymanfx** [rust-lang/rust-bindgen#2077]
We're running into the following issue in `v4l-rs`, the v4l[2] bindings for Rust:

In Linux 4.4, the `v4l2_ext_controls` struct looks like the following:
```
struct v4l2_ext_controls {
	__u32 ctrl_class;
	__u32 count;
	__u32 error_idx;
	__u32 reserved[2];
	struct v4l2_ext_control *controls;
};
```

but on recent kernel versions (e.g. 5.12), it looks like this instead:
```
struct v4l2_ext_controls {
        union {
                __u32 ctrl_class;
                __u32 which;
        };
        __u32 count;
        __u32 error_idx;
        __s32 request_fd;
        __u32 reserved[1];
        struct v4l2_ext_control *controls;
};
```

The problem being that the `ctrl_class` member was moved into a union. In C, this is fine since the actual memory layout of the struct was unchanged. Using bindgen however, we cannot seem to access the `ctrl_class` field without breaking backwards compatibility since it forces us to access it through an `__bindgen_anon_1` intermediate field (which is not available when compiling against Linux 4.4 of course).

Is there a way to deal with this while preserving support for old kernel versions?

See the original issue: https://github.com/raymanfx/libv4l-rs/pull/40.

**Comment by emilio** [comment]
Not sure how to make this work other than with conditional compilation and adding a getter, or perhaps block listing that struct and defining it yourself, rust doesn't have any sort of anonymous union we could use here...

**Comment by emilio** [comment]
Probably detecting the kernel version you're running bindgen against, and if it's old, blocklist that struct and define it yourself somewhere or such. Not pretty but that's the best I can think of r/n at least.

**Comment by raymanfx** [comment]
Thanks for the feedback. I think I prefer carrying my own struct then and reproducing the C layout of the Linux one. Conditional compilation would just make for ugly code and having to worry about all the different cases.

**Comment by farnz** [comment]
> Not sure how to make this work other than with conditional compilation and adding a getter, or perhaps block listing that struct and defining it yourself, rust doesn't have any sort of anonymous union we could use here...

OOI, why isn't a [Rust union](https://doc.rust-lang.org/reference/items/unions.html) suitable for this plain C case? Because of the need for `unsafe`?

**Comment by emilio** [comment]
You can use a rust union (bindgen should be able to generate them if you target a new enough version of rust or what not, and in fact I suspect it's doing it). But Rust doesn't have unnamed fields, so you still need to give the field a name which is the issue here.

**Comment by emilio** [comment]
I think this is not generally fixable (unless upstream Rust somehow adds support for unnamed fields), but please reopen if you disagree or think there's something that bindgen should do on this case.

**Comment by raymanfx** [comment]
I was going to close this tomorrow anyways.
We opted for block listing the struct (aka carrying our own cooy in the `v4l` crate) for now.

Thanks for the quick response on the matter!
