### ISSUE TITLE
Contributing testing guidelines install out-of-date rustfmt

### ISSUE THREAD

**Issue by KarelPeeters** [rust-lang/rust-bindgen#2080]
I'm trying to contribute to `rust-bindgen` for the first time, and I got hung up around [here](https://github.com/rust-lang/rust-bindgen/blob/master/CONTRIBUTING.md#overview) in `CONTRIBUTING.md`:

>The generated and expected bindings are run through rustfmt before they are compared. Make sure >you have rustfmt up to date:
>
>    $ rustup update nightly
>    $ rustup run nightly cargo install -f rustfmt-nightly

This second command installs an older version of rustfmt that doesn't compile on nightly any more. It looks like this step can simply be skipped, since rustfmt is now included by default.

**Comment by emilio** [comment]
I tweaked to suggest `rustup component add ...` in case you have minimal toolchains, but yeah, thanks for reporting this!
