### ISSUE TITLE
Error on deriving Default trait for __BindgenBitfieldUnit with too large array (redux)

### ISSUE THREAD

**Issue by rhdxmr** [rust-lang/rust-bindgen#2082]
Hello

I read this PR #1719 that prevents `Default` trait from deriving for structures that contain `__BindgenBitfieldUnit` with too large array.
 
But with rust 1.53 and bindgen 0.59 this problem raises again.

### Input C/C++ Header

Quote from `tests/headers/timex.h`
If the comment `// bindgen-flags: --rust-target 1.40` is removed, `cargo test timex` **fails**.

```C
struct timex {
        int tai;

        int  :32; int  :32; int  :32; int  :32;
        int  :32; int  :32; int  :32; int  :32;
        int  :32; int  :32; int  :32;
};

```

### Expected Results

No `#[derive(Default)]` for `struct timex` that contains `__BindgenBitfieldUnit<[u8; 44usize]>`

**Comment by emilio** [comment]
Hmm, thanks for filing, then this is likely a regression from #2070. CC @ian-p-cookie
