### ISSUE TITLE
Something doesn't get rebuilt even if build.rs failed

### ISSUE THREAD

**Issue by asomers** [rust-lang/rust-bindgen#2086]
Everything works fine when I use bindgen in an environment with llvm-config installed.  But in an environment that only has llvm-config90 installed, bindgen fails with the expected error message about "set the LLVM_CONFIG_PATH environment variable...".  However, even if I *do* set that environment variable, bindgen ignores it and attempts to execute llvm-config anyway.

### Bindgen Invocation

```Rust
    let bindings = bindgen::Builder::default()
        .header("/usr/include/libgeom.h")
        .header("/usr/include/sys/devicestat.h")
        .whitelist_function("geom_.*")
        .whitelist_function("gctl_.*")
        .whitelist_function("g_.*")
        .whitelist_type("devstat_trans_flags")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .generate()
        .expect("Unable to generate bindings");
```

or

### Actual Results

```
> env LLVM_CONFIG_PATH=/usr/local/bin/llvm-config90 cargo build
warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
```

### Expected Results

I would expect that bindgen would execute /usr/local/bin/llvm-config90 and everything would work.

**Comment by asomers** [comment]
**Update**

The real issue isn't what I thought it was.  `LLVM_CONFIG_PATH` does get interpreted correctly - the first time that the crate is built.  The problem is that even if the build.rs script fails due to LLVM_CONFIG_PATH being invalid, the old value of that variable gets cached somewhere, so subsequent built attempts use it instead of the current value.  For example:
```
somers@methionine /u/h/s/s/r/g/freebsd-libgeom-sys (master)> touch build.rs
somers@methionine /u/h/s/s/r/g/freebsd-libgeom-sys (master)> env LLVM_CONFIG_PATH=/usr/local/bin/llvm-config90x cargo build
   Compiling freebsd-libgeom-sys v0.1.1 (/usr/home/somers/src/rust/gstat-rs/freebsd-libgeom-sys)
warning: couldn't execute `/usr/local/bin/llvm-config90x --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
    Finished dev [unoptimized + debuginfo] target(s) in 1.04s
somers@methionine /u/h/s/s/r/g/freebsd-libgeom-sys (master)> env LLVM_CONFIG_PATH=/usr/local/bin/llvm-config90 cargo build
warning: couldn't execute `/usr/local/bin/llvm-config90x --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```
I would expect that Cargo would always rerun the build script if it failed.

**Comment by emilio** [comment]
Hmm, I'd think [this line](https://github.com/rust-lang/rust-bindgen/blob/d79922d763fa048fbc903beacf7dbf25aaad1f75/build.rs#L78) should take care of that... Which bindgen version is that crate using? it was added in https://github.com/rust-lang/rust-bindgen/commit/871d4725206600e787f7bbc92dcc7b51cc651433

**Comment by asomers** [comment]
Um, that might fix it.  I had been using 0.53.1, which does not have that line.  But now, on 0.55.1 or later, the build succeeds even if I supply an obviously bogus value for LLVM_CONFIG_PATH.  Does bindgen no longer use llvm-config or something?

**Comment by emilio** [comment]
I think clang-sys was probably updated to be smarter about fallback. I don't think there's much actionable here so closing, but please reopen if you disagree.
