### ISSUE TITLE
Querying `bindgen` for LLVM version being used

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust-bindgen#2138]
What is the preferred way to query `bindgen` about what is the LLVM / `libclang` version being effectively used/found?

One way is passing `bindgen` this header or similar:

```c
#pragma message __clang_version__
```

But ideally, one could query the version with something like:

```
bindgen --version --verbose
```

which would print an extra line:

```
LLVM version: 13.0.0
```

like `rustc` does. Possibly with other extra information (e.g. the path to the library instead of just the version, whether it was set at runtime via `CLANG_PATH`...).

Apologies if I missed any obvious way in the documentation and/or existing issues.

**Comment by emilio** [comment]
I think we print it from a debug log, but of course that's not optimal, it's a fair request. One problematic thing is that `--version` is handled by clap, though maybe we can do it manually.

**Comment by emilio** [comment]
With https://github.com/rust-lang/rust-bindgen/pull/2140 we'd print:

```
bindgen 0.59.2
Clang version: clang version 13.0.0 (Fedora 13.0.0-5.fc36)
```

Would that work for you?

**Comment by ojeda** [comment]
Yeah, that would be great!

**Comment by ojeda** [comment]
A couple extra thoughts:

  - Will the output remain stable? I may fetch this line from a script to see if the Clang version is recent enough. It is fine if not, I can use the `__clang_version__` approach (we use a similar approach to get the C compiler version anyway; and given we are not using a recent `bindgen`, I will start with that), but I am wondering whether parsing `--version --verbose` from scripts is a possibility.

  - I am thinking whether to check if the Clang used by `bindgen` is the same as the one used to compile the C side of the project. For this, I guess checking the full version string is a quite good approximation already, but perhaps there is a better way, like a commit hash, or the version + the path to the library (e.g. the `InstalledDir` that `clang --version` prints). Any suggestion?
