### ISSUE TITLE
std/libc type missing, results in build error with arm7a-none-eabi

### ISSUE THREAD

**Issue by sijupunnnoose** [rust-lang/rust-bindgen#2139]
We are working on a baremetal armv7a project, where in we did convert the c header to rust. But we have issues with standard types, initially we tried without --ctypes-prefix, 
with which all variable are prefix with ::std::os::raw::c_*. As std is not available for armv7a-none-eabi, we changed it --ctypes-prefix=libc. But with this we get errors as below for all types.

while compiling with rustc below error pops up

error[E0432]: unresolved import `libc::c_char`
 --> src\lib.rs:5:5
  |
5 | use libc::c_char;
  |     ^^^^^^^^^^^^ no `c_char` in the root
  
Can someone suggest, how to solve this issue?

**Comment by madsmtm** [comment]
Quick guess: `armv7a-none-eabi` is not supported by `libc`, perhaps open an issue there?

Or consider `--ctypes-prefix=crate::types`, and then defining `c_char` (and others) in a `types` module in yours crate?

**Comment by emilio** [comment]
Yeah, this is not a bindgen issue unfortunately, this is a libc issue.
