### ISSUE TITLE
Implement __attribute__((__warn_unused_result__))

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust-bindgen#2149]
### Input C/C++ Header

```C++
__attribute__((__warn_unused_result__)) int f();
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn f() -> ::std::os::raw::c_int;
}
```

### Expected Results

```rust
/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    #[must_use] pub fn f() -> ::std::os::raw::c_int;
}
```

**Comment by emilio** [comment]
Hmm, we're supposed to have some support for this, see tests/expectations/tests/attribute_warn_unused_result.rs

**Comment by emilio** [comment]
We have this behind the `--enable-function-attribute-detection`, because it is expensive to detect unfortunately, but we do support this.

**Comment by jethrogb** [comment]
Would it be ok to filter this through the ParseCallbacks to avoid calling it unnecessarily?
