### ISSUE TITLE
Changelog does not have a listing for latest release, 0.59.2

### ISSUE THREAD

**Issue by autarch** [rust-lang/rust-bindgen#2150]
The latest release is 0.59.2 but the changelog only goes up to 0.59.1.

**Comment by kulp** [comment]
Maybe this can be fixed during the next release, #2209.

**Comment by kulp** [comment]
This was resolved in [#2209](https://github.com/rust-lang/rust-bindgen/commit/355181134094202e0caae60c1fbf145d8e6ca84b).
