### ISSUE TITLE
allowlist entries like allowlist_function show no warning when they don't match anything.

### ISSUE THREAD

**Issue by noahgibbs** [rust-lang/rust-bindgen#2167]
It would be useful if bindgen printed a warning when allowlist_function, allowlist_type, allowlist_var and allowlist_file resulted in no symbols being matched. I know you can't always predict how *many* symbols are matched with a regexp. But presumably an allowlist entry exists to try to match something.

Right now it silently fails to emit a binding with no warning/error that can be checked for.

A similar warning for header() would also be nice.

(I apologise if there's an optional warning I could turn on. I haven't found one yet.)

### Input C/C++ Header

```C
int non_matched_function(int arg);
```

### Bindgen Invocation

```Rust
  let bindings = bindgen::builder()
    .header("foo.h")
    .allowlist_function("doesnt_match_anything")
    .generate()
    .expect("Unable to generate bindings");

  bindings.write_to_file("./bindings.inc.rs").expect("Couldn't write bindings!");
```

### Actual Results

Bindings are correct (empty). But no warning message is shown.

### Expected Results

A warning, such as "allowlist_function doesnt_match_anything matched no symbols!" and possibly "header file foo.h contained no matched symbols."

**Comment by acj** [comment]
I bumped into this recently and found that it was a logging level issue. The (somewhat confusingly named) [record_matches](https://github.com/rust-lang/rust-bindgen/blob/11f3b37faf5635bf005da3645b8f3bdcaab208dc/src/lib.rs#L1944-L1948) option will print the warnings you're looking for, but env_logger's default log level is [error](https://docs.rs/env_logger/0.9.0/env_logger/#enabling-logging).

```sh
$ cat header.h
int non_matched_function(int arg)

$ bindgen header.h --allowlist-function doesnt_match_anything
/* automatically generated by rust-bindgen 0.59.2 */

$ RUST_LOG=warn bindgen header.h --allowlist-function doesnt_match_anything
[2022-06-14T11:45:56Z WARN  bindgen::ir::context] unused option: --allowlist-function doesnt_match_anything
/* automatically generated by rust-bindgen 0.59.2 */
```

**Comment by noahgibbs** [comment]
That *sounds* fantastic. I'm not having any luck adapting it to use a build.rs file, though. It works fine on the command line, but with cargo and a builder it doesn't seem to be printed, even after I add the .record_matches(true) option and set RUST_LOG. Am I doing something obviously wrong? I'm pretty new to Rust.

**Comment by acj** [comment]
> It works fine on the command line, but with cargo and a builder it doesn't seem to be printed

I haven't tried it with build.rs, but you might need to do `env_logger::init();` before calling bindgen. That worked for me with `RUST_LOG=warn cargo xtask ...` in a similar use case.

Yeah, the current warning mechanism feels clunky. It would be nice if you could call a function on the builder to check matches, or maybe inspect something on the `Bindings` struct after you generate.

**Comment by noahgibbs** [comment]
There's an internal function to check for unmatched Rules. That's how the printed warning works. But it looks like it's not meant for external consumption.

**Comment by noahgibbs** [comment]
Looks like your fix *does* work for our case. Thank you! With a little grepping the output we can get the missed imports.
