### ISSUE TITLE
Bindgen generates anonymous members of blocklisted type

### ISSUE THREAD

**Issue by bugadani** [rust-lang/rust-bindgen#2199]
The input structure is this: https://github.com/espressif/esp-idf/blob/master/components/soc/esp32/include/soc/host_struct.h

This is a lot of stuff I don't need in my bindings, all I need is `host_dev_t` as an opaque type. If I set `host_dev_s` as blocklisted, `host_dev_t` as opaque, there are no references to `host_dev_s` in the generated bindings. Still, `host_dev_s__bindgen_ty_*` structs are generated, and I can't seem to blocklist those. This inflates my generated bindings.rs considerably.

**Comment by emilio** [comment]
`--allowlist-type host_dev_s --opaque-type host_dev_s --blocklist-type 'host_dev_s_.*'` generates exactly what you want, afaict? Blocklisting them seems to work but let me know if I'm missing something.

**Comment by bugadani** [comment]
Thanks for the hint, my OP contains my mistake: even though I know bindgen expects a regexp, I keep thinking `*` will just work as a wildcard. Oh dang...
