### ISSUE TITLE
derive/impl fail inconsistently for blocked uint32_t/etc

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust-bindgen#2211]
### Input C/C++ Header

```C
typedef int uint32_t;

struct foo {
  uint32_t a;
};
```

### Bindgen Invocation

```Rust
    bindgen::Builder::default()
        .header("test.h")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .allowlist_type("foo")
        .allowlist_recursively(false)
        .generate()
        .expect("bindgen failure").write_to_file("test.rs").unwrap();
```

### Actual Results

No derive impl generated. With `.impl_debug(true)`, the field is not printed.

### Expected Results

Derive impl generated (since the struct is correctly generated, and even without `allowlist_recursively(false)` the struct definition doesn't use the `type` definition instead of `u32`).

The particularly odd part is that this _succeeds_ without the `parse_callbacks`. In 0.58.1 this failed regardless. Workaround is to just generate twice, and throw out the one with the parse callbacks.

**Comment by pvdrz** [comment]
@talchas could you specify what's what you want to omit? Do you want to avoid deriving `Debug` on the disallowed items?

**Comment by talchas** [comment]
I wanted to _have_ Debug derived. If `allowlist_type("uint32_t")` or equivalent isn't required for a working struct generated for that `struct foo`, it is weirdly inconsistent for it to be required in order to have Debug derived for it.

**Comment by pvdrz** [comment]
I ran your example on the current master and got this output:
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct foo {
    pub a: u32,
}
#[test]
fn bindgen_test_layout_foo() {
    const UNINIT: ::std::mem::MaybeUninit<foo> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<foo>(),
        4usize,
        concat!("Size of: ", stringify!(foo))
    );
    assert_eq!(
        ::std::mem::align_of::<foo>(),
        4usize,
        concat!("Alignment of ", stringify!(foo))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).a) as usize - ptr as usize },
        0usize,
        concat!("Offset of field: ", stringify!(foo), "::", stringify!(a))
    );
}
```
Which means that `Debug` is being derived now. Is that OK for you?

**Comment by talchas** [comment]
Yeah, sounds like this was fixed at some point then.

**Comment by pvdrz** [comment]
That's great to hear, thanks for reporting this :)
