### ISSUE TITLE
Take advantage of `feature(core_ffi_c)` (and possibly `feature(c_size_t)`)

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust-bindgen#2231]
[`feature(core_ffi_c)`](https://github.com/rust-lang/rust/issues/94501) was stabilized (and possibly [`feature(c_size_t)`](https://github.com/rust-lang/rust/issues/88345) in the future), so we may want to extend `--use-core` to use them (gated on `--rust-target` or some other flag).

In fact, it could potentially be made the default, since it would work for all projects (i.e. both `std` and `no_std`).

Currently, a workaround is to manually specify the prefix via `--ctypes-prefix core::ffi`.

### Input C/C++ Header

```C++
void f(int);
```

### Bindgen Invocation

```
$ bindgen input.h --use-core
```

Or in the future:

```
$ bindgen input.h
```

### Actual Results

```rust
extern "C" {
    pub fn f(arg1: ::std::os::raw::c_int);
}
```

### Expected Results

```rust
extern "C" {
    pub fn f(arg1: ::core::ffi::c_int);
}
```

**Comment by emilio** [comment]
Yes, making this the default based on the rust target seems like a great path forward. It seems `core_ffi_c` got stabilized already? A patch for this should be easy-ish to write / review :)

**Comment by ojeda** [comment]
Yeah, I have piled up a few things for `bindgen` that I want to take a look at and submit -- I should have some time in a week or so :)
