### ISSUE TITLE
Allow passing `AsRef<OsStr>` as valid `clang_arg` value.

### ISSUE THREAD

**Issue by i509VCB** [rust-lang/rust-bindgen#2233]
This allows more easily setting arguments that may come from an OsString like a path from `pkg-config`

**Comment by emilio** [comment]
Seems reasonable, would take a patch if it doesn't break backwards compat. Thanks.

**Comment by pvdrz** [comment]
I think this interacts poorly with `clang` because it expects `CString`s everywhere. On unix-like platforms this is not an issue as we can turn `OsString`s into bytes and then into `CStrings` without issue. But on windows we cannot do that as we can only get wide slices.

**Comment by pvdrz** [comment]
This discussion is adjacent to https://github.com/rust-lang/rust-bindgen/issues/1297 as we need to figure out how to handle lossy conversion between string types. I'm closing this issue as the #1297 has a more developed discussion.
