### ISSUE TITLE
Assertion failure `!isValueDependent()` triggered

### ISSUE THREAD

**Issue by chbaker0** [rust-lang/rust-bindgen#2239]
When using bindgen with an assertions-enabled libclang build, the following code fails an assertion.

The assertion indicates either bindgen or the internals of libclang are requesting const eval of `sizeof(c)` which depends on a type parameter of the template.

### Input C++ Header

```c++
template <class a> class b {
    a : sizeof(a);
};
```

<details>
<summary>Previous, less reduced case</summary>

```c++
template <class a> class b {
    typedef a c;
    struct {
        c : sizeof(c);
    };
};
```

</details>

### Bindgen Invocation

`cargo test` on https://github.com/chbaker0/rust-bindgen/commit/a17d868fff33e304c7924b096c1d3c2950819e1e

Ignore the changes to `Cargo.toml`; that was just to link with a static libclang build.

### Actual Results

```
tests-a8e2fa07fdd9a37d: /b/s/w/ir/cache/builder/src/third_party/llvm/clang/lib/AST/ExprConstant.cpp:15219: llvm::APSInt clang::Expr::EvaluateKnownConstInt(const clang::ASTContext &, SmallVectorImpl<clang::PartialDiagnosticAt> *) const: Assertion `!isValueDependent() && "Expression evaluator can't be called on a dependent expression."' failed.
error: test failed, to rerun pass '--test tests
```

### Expected Results

No assertion failure

**Comment by emilio** [comment]
Do you have a full stack by any chance?

**Comment by chbaker0** [comment]
Not yet, trying to get that

**Comment by chbaker0** [comment]
This asserts while dumping the AST:

https://gist.github.com/chbaker0/c75dd83b78fe9e48af98259db11ed9c0

Is bindgen and/or libclang assuming the bitfield size specifier is not dependent on any template parameters?

**Comment by chbaker0** [comment]
When the options `--emit-ir --emit-ir-graphviz ir.dot --emit-clang-ast` are removed it still asserts but with a different backtrace:

https://gist.github.com/chbaker0/1f03ead2fcc5faab5ff3788143b8139b

**Comment by chbaker0** [comment]
Reduced the test case further. The typedef was not necessary to repro

**Comment by chbaker0** [comment]
The problem seems to lie on both sides:

bindgen assumes that any bitfield's bit width, including those in a template definition, can be evaluated immediately: https://github.com/rust-lang/rust-bindgen/blob/87e2e91356d52ba8aaa32cf3d06a2dd978740bc8/src/ir/comp.rs#L1320:L1320

libclang doesn't provide an obvious way to determine if a bitfield's width depends on a template parameter. Furthermore, its public method to get a bitfield's width does not itself check, which leads to an assert: https://github.com/llvm/llvm-project/blob/f494f89b2a88f9de48781f43e7be2386809c7db5/clang/tools/libclang/CXType.cpp#L380

bindgen's assumption is not correct but libclang should probably document this case too. Instead of asserting, the clang_getFieldDeclBitWidth should probably return an error.

**Comment by chbaker0** [comment]
I'm trying to write a fix on bindgen's side that checks the bit width's expression tree for any references to template parameters, but it's challenging.

It's not really possible for bindgen to generate bindings for these types of bitfields, so it needs to bail when such a field is detected. But this can happen arbitrarily deep in a class definition. My first attempt was to add logic to `CompInfo::from_ty` to back out, which almost works. Except that the `BindgenContext` is modified while traversing the AST, and undoing all those changes is difficult.

You can see this if there are other declarations preceding the class that contains an unsupported bitfield. With the original repro case, bindgen will generate `pub type ...` definitions because they were added to the context before seeing the bitfield.

**Comment by chbaker0** [comment]
Draft fix here: https://github.com/rust-lang/rust-bindgen/pull/2243

**Comment by chbaker0** [comment]
Fixed by https://github.com/rust-lang/rust-bindgen/pull/2243
