### ISSUE TITLE
Remove `TraversalPredicate` trait.

### ISSUE THREAD

**Issue by pvdrz** [rust-lang/rust-bindgen#2261]
I've noticed that all the uses of `ItemTraversal` and implementations of `TraversalPredicate` only use `for<'a> fn(&'a BindgenContext, Edge) -> bool`. I was wondering if keeping both this generic parameter and trait is worth given that no other type uses them to the date.
cc @emilio, @kulp, @fitzgen

**Comment by emilio** [comment]
Yeah, probably can be a typedef (`type TraversalPredicate = fn(&BindgenContext, Edge) -> bool` or so).

**Comment by pvdrz** [comment]
Great! I'll open a PR later.
