### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by amanjeev** [rust-lang/rust-bindgen#2286]
In the light of continuing removing outright offensive language from the project, consider renaming `master` to `main`.

Earlier discussion about offensive words was in #1812 

Things that might break: 
- CI
- ???

Note: `master` and `main` runs into the issue that there may be branches out there that rely on pulling master. A solution can be a symbolic-ref: `git symbolic-ref refs/heads/master refs/heads/main`

**Comment by kulp** [comment]
If we do this, I think we should find out what comparable projects have made the same kind of transition, so we can learn from any pitfalls they encountered.

**Comment by emilio** [comment]
Renaming this sounds ok to me fwiw.

**Comment by glandium** [comment]
Note that AFAIK, github doesn't support symbolic refs. which means it's impossible to make the transition transparent to people with existing clones.

**Comment by kulp** [comment]
> I don't know if this is actually possible, but it sounds like it should be.

I think this would be:
```bash
git push origin origin/main:refs/heads/master
```

**Comment by amanjeev** [comment]
I have created a new branch, `main`, off of `master`.  I also have the workflow here to automatically merge main -> master. See my branch : https://github.com/ferrous-systems/rust-bindgen/blob/amanjeev/set-default-branch-as-main/.github/workflows/sync-master-from-main.yml

I "tested" this within ferrous' fork of bindgen.  Please let me know if there are any concerns.

**Comment by pvdrz** [comment]
@amanjeev is this workflow being triggered if someone opens a PR against main? because I think it should only run on pushes to main

**Comment by amanjeev** [comment]
@pvdrz and I chatted and it seems my solution had "pull_request" trigger too which we do not want.  I have removed it.  I will open a PR soon.
