### ISSUE TITLE
Allowlisting in objective c yields no bindings

### ISSUE THREAD

**Issue by ericmarkmartin** [rust-lang/rust-bindgen#2305]
### Input C/C++ Header

```objc
@interface Foo
- (void)foo;
@end

@interface Bar
- (void)bar;
@end

```

### Bindgen Invocation

```
$ bindgen foobar.h --allowlist-function foo -- -x objective-c
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.60.1 */



```

### Expected Results

I expect bindings to be generated for the `Foo` interface and `foo` function—in particular something like
```rust
/* automatically generated by rust-bindgen 0.60.1 */

use objc::{self, class, msg_send, sel, sel_impl};
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct Foo(pub id);
impl std::ops::Deref for Foo {
    type Target = objc::runtime::Object;
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.0 }
    }
}
unsafe impl objc::Message for Foo {}
impl Foo {
    pub fn alloc() -> Self {
        Self(unsafe { msg_send!(class!(Foo), alloc) })
    }
}
impl IFoo for Foo {}
pub trait IFoo: Sized + std::ops::Deref {
    unsafe fn foo(&self)
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, foo)
    }
}
```

I tried using each of `--allowlist-function`, `--allowlist-type`, and `--allowlist-var` on both `foo` and `Foo`.

**Comment by pvdrz** [comment]
Hmmm interesting, yeah The `I` prefix should at least be documented somewhere.

**Comment by simlay** [comment]
> Hmmm interesting, yeah The `I` prefix should at least be documented somewhere.

https://rust-lang.github.io/rust-bindgen/objc.html. Huh. Yeah. I didn't really write anything about how to use the `IFoo` in allowlisting. Just a brief mention on use in a blocklist. I'll admit when I authored a bunch of the Objective-C stuff I didn't use the allowlisting much. Just the blocklisting.

**Comment by pvdrz** [comment]
This was properly documented in the docs for `bindgen` 0.65.1
