### ISSUE TITLE
Linking with C source files

### ISSUE THREAD

**Issue by Jomy10** [rust-lang/rust-bindgen#2307]
### Input C/C++ Header

I am trying to link to the [VelocityRaptor](https://github.com/Mithreindeir/VelocityRaptor) library.

This has the following structure:
```
include
 └── *.h
src
 └── *.c
```

And `include/velocityraptor.h` is the file containing includes to all the `.h` files in the `include` directory.

### Bindgen Invocation

```Rust
    println!("cargo:rerun-if-changed={}", VELOCITYRAPTOR_H);
    
    let bindings = builder()
        .header("VelocityRaptor/VelocityRaptor/include")
        .generate_inline_functions(true)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .rustified_enum("vrShapeType")
        .generate()
        .expect("Unable to generate bindings");

```

### Actual Results

The bindings are generated correctly, but when I test the following code:

```rust
let world = crate::vrWorldInit(crate::vrWorldAlloc());
```

I get the following error:

```
  = note: Undefined symbols for architecture x86_64:
            "_vrWorldAlloc", referenced from:
                test::new_world::h7ebeb60611f3aaa3 in test-776306246dde4def.hkamu477u9t1ruq.rcgu.o
            "_vrWorldInit", referenced from:
                test::new_world::h7ebeb60611f3aaa3 in test-776306246dde4def.hkamu477u9t1ruq.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

My guess is that I still have to link to the `src/*.c` files, but I do not know how to do this. And I can't find any documentation on this.

### Expected Results

Expected the test to succeed.

**Comment by emilio** [comment]
Bindgen doesn't take care of linking the library. You should do that yourself, see this for an example from our integration tests:

https://github.com/rust-lang/rust-bindgen/blob/17dd0931306977abd13c90532d35b86237fcd7a7/bindgen-integration/build.rs#L151-L155

Any patch to improve the docs here would be appreciated of course.

**Comment by Jomy10** [comment]
@emilio Thanks, that's what I was looking for!
