### ISSUE TITLE
Generated core bindings use types beyond MSRV

### ISSUE THREAD

**Issue by declanvk** [rust-lang/rust-bindgen#2324]
### Input C/C++ Header

In `/tmp/bindgen-msrv/vendor/header.h`:

```c
typedef unsigned char  mp_sign;
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("/tmp/bindgen-msrv/vendor/header.h")
    .use_core()
    .generate()
    .unwrap()
```

### Actual Results

In `/tmp/bindgen-msrv/target/debug/build/bindgen-msrv-76670de3f461768b/out/bindings.rs`:

```rust

/* automatically generated by rust-bindgen 0.61.0 */

pub type mp_sign = ::core::ffi::c_uchar;
```

and while running `cargo +1.57.0 build`:

```
error[E0412]: cannot find type `c_uchar` in module `core::ffi`
 --> /private/tmp/bindgen-msrv/target/debug/build/bindgen-msrv-7c473a0810493086/out/bindings.rs:3:33
  |
3 | pub type mp_sign = ::core::ffi::c_uchar;
  |                                 ^^^^^^^ not found in `core::ffi`
  |
help: consider importing this type alias
  |
3 | use std::os::raw::c_uchar;
  |
```

[`core::ffi::c_uchar` was introduced in Rust version 1.64.0.](https://doc.rust-lang.org/nightly/core/ffi/type.c_uchar.html)

### Expected Results

Should compile without errors.

**Comment by declanvk** [comment]
I'm not actually sure if the MSRV is supposed to be 1) the minimum version of Rust that can build `bindgen` OR 2) the minimum version of Rust that can build the generated bindings.

**Comment by declanvk** [comment]
Seems related to #2277

**Comment by declanvk** [comment]
Ah I see the [`Builder::rust_target`](https://docs.rs/bindgen/latest/bindgen/struct.Builder.html#method.rust_target) controls which version of rust the bindings support, I should just enable that.

This is probably not an issue then? Maybe just improving the [MSRV statement](https://github.com/rust-lang/rust-bindgen#msrv) to include some references to `rust_target` or mentioning that MSRV only covers building `bindgen`, not the generated bindings.

**Comment by pvdrz** [comment]
If you set the rust target to anything below 1.64.0, bindgen will use `std::os::raw` instead as expected.

The MSRV is the minimum version that can be used to compile bindgen. However, bindgen itself can produce code for targets below the current MSRV. Maybe we should clarify this in the readme.

**Comment by pvdrz** [comment]
Fixed via: https://github.com/rust-lang/rust-bindgen/commit/d86db07859025445230c8833e7a629792f5a2990

Thanks for the report and please feel free to reopen if you think this is not an adequate solution
