### ISSUE TITLE
Mention bindgen-cli in the changelog as a breaking change

### ISSUE THREAD

**Issue by benma** [rust-lang/rust-bindgen#2337]
I was quite confused why `cargo install bindgen --version 0.61.0` didn't work after updating from `cargo install bindgen --version 0.59.2`.

It was not obvious for me to find what happened and only when I found [this commit](https://github.com/rust-lang/rust-bindgen/commit/0296f9e86c7756e718b6b82836ce1e09b5f8d08a#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L38) I realized that I needed to use `cargo install bindgen-cli --version 0.61.0` instead.

**Comment by pvdrz** [comment]
This was already in the [changelog](https://github.com/rust-lang/rust-bindgen/blame/0631a27bee19601e393e31e7dfc2563412b2fe01/CHANGELOG.md#L207).
> - The bindgen CLI utility must be installed using cargo install bindgen-cli now.

**Comment by benma** [comment]
Sorry for the noise! No idea how I missed this :see_no_evil:
