### ISSUE TITLE
use of VOID typedef results in bindings that return c_void

### ISSUE THREAD

**Issue by AdamGlass** [rust-lang/rust-bindgen#2377]
### Input C/C++ Header

```C++
void this_api_returns_nothing(void);

typedef void VOID;

VOID this_api_also_returns_nothing(VOID);

```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("input.h")
    .generate()
    .unwrap()
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.63.0 */

extern "C" {
    pub fn this_api_returns_nothing();
}
pub type VOID = ::std::os::raw::c_void;
extern "C" {
    pub fn this_api_also_returns_nothing() -> VOID;
}

```
```

### Expected Results
extern "C" {
    pub fn this_api_returns_nothing();
}

extern "C" {
    pub fn this_api_also_returns_nothing();
}

Basically the codebase has a typedef for VOID which it uses instead of void..  This results in functions that return c_void which is only intended for pointers.  Any ideas on how to solve?

**Comment by AdamGlass** [comment]
I have to acknowledge that commenting out the typedef and replacing it with  '#define VOID void' works just fine.  It's not a great out of the box solution given the typedef is in the shipping headers.

**Comment by emilio** [comment]
This seems like a plain oversight. The code we have to detect whether the return type of a function is void doesn't look through type aliases. https://github.com/rust-lang/rust-bindgen/pull/2379 is a potential fix, but needs a test and I can't write it right now.
