### ISSUE TITLE
auto handle errno from libc functions

### ISSUE THREAD

**Issue by daixiang0** [rust-lang/rust-bindgen#2383]
It is a feature request.

Take an example, bindgen would make `fork()` from libc return i32 result. 

As well known, libc use errno to indicate the error details. I know [std::io::Result](https://doc.rust-lang.org/std/io/type.Result.html) can do this, but it is a big job for a libc project.

Is there any auto way to do it? Maybe for each func, we have 2 versions: return i32 and Result.

**Comment by pvdrz** [comment]
I think this would be a bit out of scope and very specific to unix-like kernel calls. This could be handled using regular functions
```rust
fn fallible_call<F: Fn() -> i32>(f: F) -> std::io::Result<i32> {
    let output = f();
    if output == -1 {
        Err(std::io::Error::from_raw_os_error(errno()));
    } else {
        Ok(output)
    }
}
```

Then you could do:

```rust
fallible_call(fork)?;
fallible_call(|| open(path, flags))?;
```

I imagine you could achieve something similar using macros but it would be a bit more complex as you would have to parse each function's signature.

**Comment by daixiang0** [comment]
Thanks for your tips, that is very helpful!

As well-known, UNIX-like -- Linux and Mac are widely used, users would be happy to see it. Also, it makes users easier to migrate from libc to rust.

**Comment by amanjeev** [comment]
Hi there @daixiang0, let me chime in. I think @pvdrz  is correct here by pointing out issues with bindgen supporting this feature. In bindgen, we try to keep the API as much cross-platform as possible. There is a consensus among the maintainers that this is better done at a higher level crate than bindgen. That higher level crate could be more specific to the target/working OS.

I am afraid, I will have to close this for now.
