### ISSUE TITLE
Allow to whitelist `#[derive(Copy, ...)]` for certain types

### ISSUE THREAD

**Issue by ensc** [rust-lang/rust-bindgen#2393]
At the moment, `Copy` and similar traits can only be disabled (e.g. globally by `derive_copy(false)` or by `no_copy()`).

But I am in the situation (wrapping `/usr/include/linux/videodev2.h`) that a lot of the C structures are big and that I do not want to implement `Copy` for them.  On the other side, I create wrappers with `newtype_enum()` for some enums and would like to have `Copy` for them.

Because rust regexps do not support negative matches, I have to implement the traits manually.

It would be nice to have methods which override the blacklisting functions.

Ditto for the other traits affected by `no_...()`.

**Comment by pvdrz** [comment]
Maybe you can use the new custom derive flags or parse callbacks for that? They haven't been released yet but they should allow you to implement `Copy` for any type matching a regex.

**Comment by pvdrz** [comment]
To extend a little further, the following code would derive `Copy` for every `enum` and not derive it for anything else:
```rust
struct Callbacks;

impl bindgen::ParseCallbacks  for Callbacks {
    fn add_derives(&self, info: &DeriveInfo<'_>) -> Vec<String> {
        if info.kind == TypeKind::Enum {
            vec!["Copy".to_owned()]
        } else {
            vec![]
        }
    }
}

builder
    .derive_copy(false)
    .parse_callbacks(Box::new(Callbacks))
```
