### ISSUE TITLE
Bindgen skips macros with token concatenation.

### ISSUE THREAD

**Issue by TranquilRock** [rust-lang/rust-bindgen#2402]
### Input C/C++ Header

```C++
# define UL(x) x##UL
# define A UL(4294967295)
# define B 4294967295UL
```

### Bindgen Invocation
```
$ bindgen input.h
```

### Actual Result

```
/* automatically generated by rust-bindgen 0.59.1 */

pub const B: u32 = 4294967295;
```

### Expected Results

```
/* automatically generated by rust-bindgen 0.59.1 */

pub const A: u32 = 4294967295;
pub const B: u32 = 4294967295;
```

### Ref

- https://gcc.gnu.org/onlinedocs/cpp/Concatenation.html

**Comment by K900** [comment]
I'm pretty sure it's not just token concatenation - any invocation of a macro in a #define seems ignored, even something as simple as

```
#define WRAP(v) v
#define WRAPPED WRAP(1)
#define NOT_WRAPPED 2
```

**Comment by K900** [comment]
Actually looks like this is just a subset of https://github.com/rust-lang/rust-bindgen/issues/753

**Comment by oToToT** [comment]
The bindgen output of the C code below

```c
#define A 1 ## 2
#define B 2
```

is

```rust
/* automatically generated by rust-bindgen 0.61.0 */

pub const B: u32 = 2;
```

IIUC, it doesn't seemed to be included in #753.

**Comment by jbaublitz** [comment]
@oToToT The newest bindgen release includes work that resolves this issue despite not being included in the issue. I just tested with the newest bindgen and this syntax is handled with the `--clang-macro-fallback` flag.

**Comment by pvdrz** [comment]
Closed via https://github.com/rust-lang/rust-bindgen/pull/2779
