### ISSUE TITLE
Should bindgen depend on `clang-sys/clang_15` when using clang >= 15?

### ISSUE THREAD

**Issue by decathorpe** [rust-lang/rust-bindgen#2409]
According to the clang-sys README, some API change in clang >= 15 causes it to return different results in some cases when compared to clang < 15:
https://github.com/KyleMayes/clang-sys#supported-versions

If bindgen is affected by this issue when running on clang >= 15, it might be a good idea to enable the `clang-sys/clang_15` feature if clang >= 15 is detected.

**Comment by pvdrz** [comment]
iirc we don't use `CXCursor_TranslationUnit` anywhere in the `bindgen/clang.rs` module so we shouldn't be affected by this. That being said we should have some sort of sanity check in case someone decides to use it at some point.
