### ISSUE TITLE
Incomplete handling of typedef aliases with enums

### ISSUE THREAD

**Issue by jasta** [rust-lang/rust-bindgen#2431]
### Input C/C++ Header

```C++
typedef enum {
  VARIANT1 = 0,
  VARIANT2,
  VARIANT3,
} original_t;

typedef original_t alias_t;
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
pub const original_t_VARIANT1: original_t = 0;
pub const original_t_VARIANT2: original_t = 1;
pub const original_t_VARIANT3: original_t = 2;
pub type original_t = ::std::os::raw::c_uint;
pub use self::original_t as alias_t;
```

### Expected Results

Regeneration of the enum const values with the alias_t prefix as such:

```rust
pub const original_t_VARIANT1: original_t = 0;
pub const original_t_VARIANT2: original_t = 1;
pub const original_t_VARIANT3: original_t = 2;
pub type original_t = ::std::os::raw::c_uint;
pub use self::original_t as alias_t;
pub const alias_t_VARIANT1 = original_t_VARIANT1;
pub const alias_t_VARIANT2 = original_t_VARIANT2;
pub const alias_t_VARIANT2 = original_t_VARIANT3;
```

The motivation for this being the default is that for C/C++ the original header would've allowed for enum identifier to be
re-used anywhere that either original_t or alias_t were expected (by just using the identifier `VARIANT1`).  So this can be an effective way for C/C++ to migrate folks to a newer API over time by first getting everyone to adopt the new name and then eventually to define new variants.  But with bindgen this creates a pretty painful migration because the new preferred API has to use the naming from the old one unless we use `constified_enum_module` for these types then manually creating an alias to the module.

Further, I can't use `ParseCallbacks` to hack around this problem because I'm not able to redefine the enum's module (in this case, original_t to alias_t), I can only redefine the original name (VARIANT1, etc).  It seems enum_variant_behaviour isn't any help either and actually generates some kind of surprising duplicate identifier issues if I try (though maybe I used the feature wrong of course).

**Comment by pvdrz** [comment]
An alternative would be to use `--no-prepend-enum-name`:
```rust
pub const VARIANT1: original_t = 0;
pub const VARIANT2: original_t = 1;
pub const VARIANT3: original_t = 2;
pub type original_t = ::std::os::raw::c_uint;
pub use self::original_t as alias_t;
```
In that way you can use `VARIANT1` as either an `original_t` or `alias_t`.

**Comment by jasta** [comment]
> An alternative would be to use `--no-prepend-enum-name`:
> ```rust
> pub const VARIANT1: original_t = 0;
> pub const VARIANT2: original_t = 1;
> pub const VARIANT3: original_t = 2;
> pub type original_t = ::std::os::raw::c_uint;
> pub use self::original_t as alias_t;
> ```
> In that way you can use `VARIANT1` as either an `original_t` or `alias_t`.

Unfortunately this option applies to all types in the bindgen invocation, which for large projects can be even more painful than the module workaround (as is the case for me).  A great solution though would be to make this option use the regexp pattern that the others have, or even as an enum behavior for ParseCallbacks.

**Comment by pvdrz** [comment]
Maybe [`ParseCallbacks::enum_variant_name`](https://docs.rs/bindgen/latest/bindgen/callbacks/trait.ParseCallbacks.html#method.enum_variant_name) could be what you want.

**Comment by jasta** [comment]
> Maybe [`ParseCallbacks::enum_variant_name`](https://docs.rs/bindgen/latest/bindgen/callbacks/trait.ParseCallbacks.html#method.enum_variant_name) could be what you want.

Could as in we could modify it?  Right now I don't think it'll work since you can only rename the `VARIANT*` part, not the prefix.  If it allowed for the latter, that would work great I think.

**Comment by pvdrz** [comment]
Yeah I think we can reuse that function to add this functionality. I'm a bit reluctant to add a new flag/builder method because it feels like it would overlap with this and could lead to unexpected behavior when using both. I think for now you could use both the callback and `prepend_enum_name(false)`:
```rust
pub fn main() {
    #[derive(Debug)]
    struct CB;

    impl ParseCallbacks for CB {
        fn enum_variant_name(
                &self,
                enum_name: Option<&str>,
                variant_name: &str,
                _value: bindgen::callbacks::EnumVariantValue,
            ) -> Option<String> {
            let new_name = match enum_name {
                Some(name) if name != "original_t" => format!("{}_{}", name, variant_name),
                _ => variant_name.to_string(),
            };

            Some(new_name)
        }
    }
    let bindings = bindgen::Builder::default()
        .header("./wrapper.h")
        .parse_callbacks(Box::new(CB))
        .prepend_enum_name(false)
        .generate()
        .expect("Unable to generate bindings");
    
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("bindings.rs");

    bindings
        .write_to_file(out_path)
        .expect("Couldn't write bindings!");
}
```

The only problem with changing `enum_variant_name` is that we would need to do it in a way we don't change how it works silently. Maybe we could add a boolean argument called `prefix_enum_name` or something like that.
