### ISSUE TITLE
`--wrap-static-fns` generates code that `return`s a call to a `void` function

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust-bindgen#2485]
### Input C/C++ Header

```C
static inline void f(void) {}
```

### Bindgen Invocation

```
$ bindgen --wrap-static-fns --experimental input.h
```

### Actual Results

In `/tmp/bindgen/extern.c`:

```C
void f__extern() { return f(); }
```

### Expected Results

In C one should avoid returning a call to a `void` function to please `-Wpedantic`:

```C
void f__extern() { f(); }
```

**Comment by pvdrz** [comment]
This is already fixed and will be available on `bindgen` 0.65.0

**Comment by ojeda** [comment]
Thanks!

**Comment by pvdrz** [comment]
Sorry this was fixed here: https://github.com/rust-lang/rust-bindgen/pull/2497
