### ISSUE TITLE
"invalid identifier" when clang targets obj-c

### ISSUE THREAD

**Issue by duckfromdiscord** [rust-lang/rust-bindgen#2486]
### Input Obj-C Header

```obj-c
//
//  HapticIFace.h
//  rusttest
//
//  Created by user on 4/6/23.
//

#ifndef HapticIFace_h
#define HapticIFace_h

#import <CoreHaptics/CoreHaptics.h>

@interface HapticIFace : NSObject       {
}

@property (nonatomic, strong) CHHapticEngine* engine;

@end

#endif /* HapticIFace_h */
```
This is here as a placeholder since it was the last file I tried. Any file causes this error.

### Bindgen Invocation

```
bindgen ./HapticIFace.h -- -target arm64-apple-ios -x objective-c -isysroot /Users/user/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
```

### Actual Results

```
panicked at 'Invalid identifier: Error("expected identifier")', /Users/user/.cargo/registry/src/github.com-x/bindgen-0.64.0/ir/objc.rs:272:30
```

### Expected Results

Unknown

===

This error happens on all files I use w/ objective-c.

I mistakenly [attached](https://github.com/rust-lang/rust-bindgen/issues/2029#issuecomment-1496556695) this onto issue #2029. 
There, I'd used a premade command courtesy of @.simlay: https://simlay.net/posts/rust-bindgen-objc-support/#adding-a-build-rs . I modified it to the correct paths for my usecase and ran that build.rs using `cargo` and had the same issue.

Importantly, if I put a random file in, it goes through that file and obviously detects syntax errors. Perhaps the issue happening here comes after the file is processed? I ran with `RUST_BACKTRACE=1` and there was no difference in the error message, and I also am currently running with `RUST_LOG=bindgen`. It's been going for about fifteen minutes but it's getting slower as more stuff gets printed. It's definitely working with the code given, so I think whatever the issue is is happening after the ir is generated.

**Comment by duckfromdiscord** [comment]
Anyone have any ideas? I get this issue when trying to build a header file that builds just fine in Xcode.

**Comment by duckfromdiscord** [comment]
**Issue disappears in previous version 0.63.0.**

**Comment by pvdrz** [comment]
Hmm this sounds like a regression. Do you have a minimal example so I can bisect this?

**Comment by duckfromdiscord** [comment]
> Hmm this sounds like a regression. Do you have a minimal example so I can bisect this?

@pvdrz I appreciate the offer quite a bit. A minimal example would be an obj-c header file with just an include/import of a system header in it, say `#import <Foundation/Foundation.h>` or `#import <CoreHaptics/CoreHaptics.h>`.

The command to run would be `bindgen [the name of your header file] -- -target arm64-apple-ios -x objective-c -isysroot [path to your Xcode.app]/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk` using the `bindgen-cli`.

The error is somewhere between v0.63.0 and v0.64.0 for me.

**Comment by pvdrz** [comment]
I'd need something more minimal than that as I don't have a local machine with MacOS so I don't have any system headers for it.

**Comment by pvdrz** [comment]
There's no guarantee that it will work but you could try and use c-reduce to generate a minimal example: https://github.com/rust-lang/rust-bindgen/blob/main/CONTRIBUTING.md#using-creduce-to-minimize-test-cases

**Comment by grant0417** [comment]
A little more context, also running into this issue. It seems to be with parsing the name of some identifier named `self`, which is not a valid identifier in Rust.

```
thread 'main' panicked at 'Invalid identifier: Error("expected identifier, found keyword `self`")',
```

**Comment by pvdrz** [comment]
my bad :P

Apparently `self` cannot be used as a raw identifier because of reasons: https://doc.rust-lang.org/reference/identifiers.html

I'll submit a in a moment

**Comment by pvdrz** [comment]
Can you check if this https://github.com/rust-lang/rust-bindgen/pull/2587 fixes your issue?

**Comment by grant0417** [comment]
That seems to have fixed the issue for me!

**Comment by duckfromdiscord** [comment]
Will try right now, thank you all again for bisecting and fixing

**Comment by pvdrz** [comment]
@duckfromdiscord ohh sorry I closed it eagerly (I got excited about fixing it). Please reopen the issue if the fix did not work

**Comment by duckfromdiscord** [comment]
> @duckfromdiscord ohh sorry I closed it eagerly (I got excited about fixing it). Please reopen the issue if the fix did not work

It did indeed work 😄

**Comment by pvdrz** [comment]
Glad to hear it worked :)
