### ISSUE TITLE
Mishandle of variadic function with wrapped static functions

### ISSUE THREAD

**Issue by Urgau** [rust-lang/rust-bindgen#2498]
### Input C/C++ Header

```C++
static inline void foo(int flags, ...) {
    // ...
}
```

### Bindgen Invocation

```
$ bindgen --experimental --wrap-static-fns input.h
```

### Actual Results

```rust
extern "C" {
    #[link_name = "foo__extern"]
    pub fn foo(flags: ::std::os::raw::c_int, ...);
}
```

and

```c
#include "input.h"

// Static wrappers

void foo__extern(int flags) { foo(flags); } // At least missing `...`
```

### Expected Results

I expect bindgen to either handle correctly (what ever that would be) or to ignore those bind of functions.

cc @pvdrz

**Comment by pvdrz** [comment]
@Urgau I couldn't find a way to forward a call to a variadic function in C. For now I opened a PR that will skip any variadic functions that are also static if the `--wrap-static-fns` option is enabled.

**Comment by Urgau** [comment]
> I couldn't find a way to forward a call to a variadic function in C. 

Neither could I.

However in my situation and I suppose many others, those variadic static inline are just helpers that call an underline `va_list` function. See this [example](https://code.videolan.org/videolan/vlc/-/blob/f93de3ef234c010a8e3788985ed9d0ae2e5b0aca/include/vlc_stream.h#L398-409):
```c
int vlc_stream_vaControl(stream_t *s, int query, va_list args);

static inline int vlc_stream_Control(stream_t *s, int query, ...)
{
    va_list ap;
    int ret;

    va_start(ap, query);
    ret = vlc_stream_vaControl(s, query, ap);
    va_end(ap);
    return ret;
}
```

If we could have a way to "generate" this intermediate code, maybe with a callback that takes the function name and returns an option of the va_list fn name to delegate to?

**Comment by pvdrz** [comment]
That sounds like something that `ParseCallbacks` could certainly do but I wonder how common is this operation considering that you could append that code to the C file generated by `bindgen`.
