### ISSUE TITLE
`_Float16 _Complex` leads to panic (such as when including `immintrin.h` on clang 16)

### ISSUE THREAD

**Issue by xzn** [rust-lang/rust-bindgen#2500]
### Input C/C++ Header

```C++
/* input.h */
_Float16 _Complex h;
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```
panicked at 'Non floating-type complex? Type(_Complex _Float16, kind: Complex, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Type(_Float16, kind: Float16, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))', J:\Compilers\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.65.1\ir\context.rs:1994:26
```

### Expected Results

Command completes without error.

### Synopsis

Ran into this when using a header from a project that includes `immintrin.h`, which on clang 16 always seems to include `avx512fp16intrin.h` and `avx512vlfp16intrin.h`, which in turn have construct `_Float16 _Complex`, which currently bindgen cannot handle.

For example, running bindgen on SDL2's `SDL.h` which includes `immintrin.h` through `SDL_cpuinfo.h` results in the above error.

**Comment by pvdrz** [comment]
Handling this case is relatively straightforward. The only question is to what should we map `_Float16` on the first place?

**Comment by DexterHill0** [comment]
Also currently facing this issue in a project that includes fmtlib/fmt. 
For the mapping, if `_Float16` is already converted to `u16` without a newtype then wouldn't it make sense for `_Float16 _Complex` to become `__BindgenComplex<u16>`, also without a newtype?

**Comment by xzn** [comment]
`float128` seems to get mapped to `u128` or `[u64; 2]` if `u128` isn't available on the target. (I'm not quite understanding the source code of bindgen though)

**Comment by pvdrz** [comment]
> Also currently facing this issue in a project that includes fmtlib/fmt. For the mapping, if `_Float16` is already converted to `u16` without a newtype then wouldn't it make sense for `_Float16 _Complex` to become `__BindgenComplex<u16>`, also without a newtype?

`_Float16` is not being mapped to `u16` either:
```
panicked at 'Couldn't resolve constant type, and it wasn't an nondeductible auto type or unexposed type!', /home/christian/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.64.0/ir/var.rs:307:25
```

Even if it were I think it could be misleading as you'd have no warning about treating a value as an `u16` when it should be treated as a float.

**Comment by pvdrz** [comment]
> `float128` seems to get mapped to `u128` or `[u64; 2]` if `u128` isn't available on the target. (I'm not quite understanding the source code of bindgen though)

I think there's an issue about this behavior being incorrect as `u128` is not FFI-safe: https://github.com/rust-lang/rust-bindgen/issues/2105

**Comment by DexterHill0** [comment]
> > Also currently facing this issue in a project that includes fmtlib/fmt. For the mapping, if `_Float16` is already converted to `u16` without a newtype then wouldn't it make sense for `_Float16 _Complex` to become `__BindgenComplex<u16>`, also without a newtype?
> 
> `_Float16` is not being mapped to `u16` either:
> 
> ```
> panicked at 'Couldn't resolve constant type, and it wasn't an nondeductible auto type or unexposed type!', /home/christian/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.64.0/ir/var.rs:307:25
> ```
> 
> Even if it were I think it could be misleading as you'd have no warning about treating a value as an `u16` when it should be treated as a float.

That's quite interesting. If you use `_Float16` as a struct member type (and seemingly in function signaturs) it does work:
```c++
struct A {
    _Float16 foo;
};
```
then it generates:
```rs
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct A {
    pub foo: u16,
}
```
However just using it as a variable type alone does not work. Maybe that's known behaviour but `_Float16` is already becoming a `u16` in some places.

**Comment by pvdrz** [comment]
Hmm that's interesting. I think this `u16` conversion is not happening explicitly. What I mean is that I couldn't find any special case for `_Float16` in `bindgen`'s source code. Apparently what's happening is that `_Float16` is being treated as an opaque type with size and align 2, so it is converted to `u16` as it should.

**Comment by DexterHill0** [comment]
Makes sense. 
In that case, a wrapper struct is probably the best option however I think it really depends on the end goal. For example, is the goal to make a completely opaque `f16` type that functions exactly like a float, or is it to just simply make a transparent wrapper so you can use the ident `f16` rather than `u16`?
Personally, I'd say the latter makes sense for private, internal usage, but if there was a public item that used a `_Float16`, I still think a simple transparent wrapper, like the one you showed originally, _doesn't_ help clear confusion as you'd still need to access the underlying u16 in certain situations.

**Comment by koutheir** [comment]
Is there a temporary work around this issue?

**Comment by pravic** [comment]
@koutheir A temporary workaround is to use clang <= 15.

**Comment by koutheir** [comment]
This issue can be reproduced by running:

```shell
$ bindgen --verbose /usr/x86_64-w64-mingw32/include/winsock2.h -- --target=x86_64-pc-windows-gnu
Bindgen unexpectedly panicked
This may be caused by one of the known-unsupported things (https://rust-lang.github.io/rust-bindgen/cpp.html), please modify the bindgen flags to work around it as described in https://rust-lang.github.io/rust-bindgen/cpp.html
Otherwise, please file an issue at https://github.com/rust-lang/rust-bindgen/issues/new
panicked at 'Non floating-type complex? Type(_Complex _Float16, kind: Complex, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Type(_Float16, kind: Float16, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))', $HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.66.1/ir/context.rs:2020:26
```

However, forcing the preprocessor definition `__SSE2__` to be **undefined**, through the `clang` flag `-U__SSE2__`, shows another problem:

```shell
bindgen --verbose /usr/x86_64-w64-mingw32/include/winsock2.h -- --target=x86_64-pc-windows-gnu -U__SSE2__
Bindgen unexpectedly panicked
This may be caused by one of the known-unsupported things (https://rust-lang.github.io/rust-bindgen/cpp.html), please modify the bindgen flags to work around it as described in https://rust-lang.github.io/rust-bindgen/cpp.html
Otherwise, please file an issue at https://github.com/rust-lang/rust-bindgen/issues/new
panicked at 'called `Result::unwrap()` on an `Err` value: FromBytesWithNulError { kind: InteriorNul(1) }', $HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.66.1/codegen/mod.rs:717:71
```

**Comment by koutheir** [comment]
Notice that, using `bindgen` built from `main` branch (commit `2df02c2668f41d35616c8385ed61ada896a4bf4c`) fixes the second issue above, so that the following succeeds:

```shell
$ <...>/rust-bindgen/target/release/bindgen --verbose /usr/x86_64-w64-mingw32/include/winsock2.h -- --target=x86_64-pc-windows-gnu -U__SSE2__
```

**Comment by koutheir** [comment]
For reference, a more precise way to work around this issue is to define the preprocessor definitions `__AVX512VLFP16INTRIN_H` and `__AVX512FP16INTRIN_`, instead of undefining `__SSE2__` entirely:

```shell
$ <...>/rust-bindgen/target/release/bindgen --verbose /usr/x86_64-w64-mingw32/include/winsock2.h -- \
    --target=x86_64-pc-windows-gnu -D__AVX512VLFP16INTRIN_H -D__AVX512FP16INTRIN_H
```

This effectively disables the C definitions (`_Float16 _Complex ...`) that trip `bindgen` inside `avx512vlfp16intrin.h` and `avx512fp16intrin.h`.

And, of course, `bindgen` version `0.66.1` stumbles at a different place even with this work around, so one would need to fetch and build the `main` branch for the moment.

**Comment by pvdrz** [comment]
If https://github.com/rust-lang/rfcs/pull/3453 get's merged we might have a clearer way forward here.

**Comment by sagudev** [comment]
https://github.com/rust-lang/rfcs/pull/3453 is merged, there is already WIP implementation, but even when this is released it would be hidden behind [RustTarget](https://docs.rs/bindgen/latest/bindgen/enum.RustTarget.html), so fallback (non-`f16`) impl would still be needed in bindgen.
