### ISSUE TITLE
libclang error when using `-std=`

### ISSUE THREAD

**Issue by thajohns** [rust-lang/rust-bindgen#2542]
### Input C/C++ Header

```C++
int test();
```

### Bindgen Invocation

```
$ bindgen input.h -- -std=c++11
```

### Actual Results

```
panicked at 'libclang error; possible causes include:
- Invalid flag syntax
- Unrecognized flags
- Invalid flag arguments
- File I/O errors
- Host vs. target architecture mismatch
If you encounter an error missing from this list, please file an issue or a PR!', /home/thajohns/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.65.1/ir/context.rs:545:15
```

### Expected Results

Successful generation of bindings, as if the `-std=c++11` flag was not there.

**Comment by pvdrz** [comment]
This happens because `-std=c++11` implies that the input is a C++ file but the extension implies it is a C file. If you run `clang input.h -- -std=c++11` you'll get:
```
error: invalid argument '-std=c++11' not allowed with 'C'
```
So the solution here is to rename `input.h` to `input.hpp`.

Let me know if this works :)

**Comment by thajohns** [comment]
Ah, I see. From your advice, I was able to solve the problem with `-xc++`. What's up with the complete lack of diagnostic information from libclang?

**Comment by pvdrz** [comment]
I'm not sure if libclang let's us access the diagnostic info so we can display it or not. Feel free to open an issue about it.
