### ISSUE TITLE
Can't implement `ParseCallbacks::blocklisted_type_implements_trait` as `ir` module is private

### ISSUE THREAD

**Issue by rblenkinsopp** [rust-lang/rust-bindgen#2545]
I'm implementing the `ParseCallbacks` trait and am trying to implement the `blocklisted_type_implements_trait` trait method as I have several types blocklisted that I've manually implemented. 

However the `ir` modules is not public so it's impossible to implement this method as the return type is `Option<bindgen::ir::derive::CanDerive>` and hence private, which seems unintentional.

### Input C/C++ Header

N/A

### Bindgen Invocation

```Rust
struct MyCallbacks {}

impl ParseCallbacks for MyCallbacks {
    fn blocklisted_type_implements_trait(
        &self,
        _name: &str,
        _derive_trait: DeriveTrait,
    ) -> Option<bindgen::ir::derive::CanDerive> {
        todo!()
    }
}

bindgen::Builder::default()
    .header("input.h")
    .parse_callbacks(Box::new(MyCallbacks {}))
    .generate()
    .unwrap()
```

### Actual Results

```
error[E0603]: module `ir` is private
   --> myproject\build.rs:103:26
    |
103 |     ) -> Option<bindgen::ir::derive::CanDerive> {
    |                          ^^ private module
    |
note: the module `ir` is defined here
   --> C:\Users\[REDACTED]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.65.1\lib.rs:48:1
    |
48  | mod ir;
    | ^^^^^^
```

### Expected Results

The function should be usable and return no compilation errors. The `blocklisted_type_implements_trait` trait method should be implementable and function to allow me to add implemented traits to blocklisted types to allow types composed of them to have automatically derived traits.

**Comment by pvdrz** [comment]
I think that type is reexported by the callback module as [`ImplementsTrait`](https://docs.rs/bindgen/latest/bindgen/callbacks/enum.ImplementsTrait.html) could you try doing that?

**Comment by rblenkinsopp** [comment]
> I think that type is reexported by the callback module as [`ImplementsTrait`](https://docs.rs/bindgen/latest/bindgen/callbacks/enum.ImplementsTrait.html) could you try doing that?

When I used CLion to generate the implements stub, it populated with the private type, changing to `ImplementsTrait` as you suggested works correctly. Many thanks!
