### ISSUE TITLE
How can I specify the search path of the Header file

### ISSUE THREAD

**Issue by xuzihan351** [rust-lang/rust-bindgen#2574]
I am trying to use `bindgen` to generate wrappers to a lib which is used in a embedded riscv32 platform.
It seems that header files of the host is used to done this.
How can I specify the `C` header search path to the `riscv32 toolchain include path` during bindgen?

**Comment by pvdrz** [comment]
Any clang flag can be passed after `--` on the bindgen CLI or with `clang_args` in the bindgen library. So you can use `-isystem <directory>` to add a directory to the system search path and `-I <dir>` to add a directory to the regular search path.

**Comment by xuzihan351** [comment]
Thank you~
