### ISSUE TITLE
bindgen seems to generate GCC/Clang style name mangling on Windows instead of MSVC name mangling

### ISSUE THREAD

**Issue by nwoods-cimpress** [rust-lang/rust-bindgen#2580]
I strongly suspect that I'm making a newbie error, so please forgive me for reporting this issue in this venue.  However, searching around I have not been able to identify anybody having a similar problem, but I have been able to find cases where people have gotten this to work successfully.

### Input C/C++ Header

```C++
#include <stdio.h>

class Foo {
public:
  void bar();
};


void Foo::bar()
{
  printf("Hello!\n");
}
```

### Bindgen Invocation

```
C:\> bindgen foo.cpp --allowlist-type=Foo
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.66.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo {
    pub _address: u8,
}
#[test]
fn bindgen_test_layout_Foo() {
    assert_eq!(
        ::std::mem::size_of::<Foo>(),
        1usize,
        concat!("Size of: ", stringify!(Foo))
    );
    assert_eq!(
        ::std::mem::align_of::<Foo>(),
        1usize,
        concat!("Alignment of ", stringify!(Foo))
    );
}
extern "C" {
    #[link_name = "\u{1}_ZN3Foo3barEv"]
    pub fn Foo_bar(this: *mut Foo);
}
impl Foo {
    #[inline]
    pub unsafe fn bar(&mut self) {
        Foo_bar(self)
    }
}
```

### Expected Results

Instead of `#[link_name = "\u{1}_ZN3Foo3barEv"]`, I would expect to see `#[link_name = "?bar@Foo@@QEAAXXZ"]`

**Comment by pvdrz** [comment]
:wave: I don't have a windows machine so I'm of little help but if you happen to know any `clang` argument that would fix the mangling you could pass that to bindgen using `-- <the clang argument>` otherwise you can try to see if changing the `--target` argument does what you want.

**Comment by nwoods-cimpress** [comment]
Thank you!  This did the trick:

`bindgen foo.cpp --allowlist-type=Foo -- --target=x86_64-pc-windows-msvc`

Here are the results:
````
extern "C" {
    #[link_name = "\u{1}?bar@Foo@@QEAAXXZ"]
    pub fn Foo_bar(this: *mut Foo);
}
impl Foo {
    #[inline]
    pub unsafe fn bar(&mut self) {
        Foo_bar(self)
    }
}
````

Unfortunately when I do this "for real", I get an `#error` in system header files; I was able to reproduce this in my test file with the following code:
````
#if __clang_major__ < 15
#error "Unexpected compiler version, expected Clang 15.0.0 or newer."
#endif // ^^^ old Clang ^^^
````

To my knowledge, I have a newer `clang`:
````
C:\temp>bindgen foo.cpp --allowlist-type=Foo -- --target=x86_64-pc-windows-msvc
foo.cpp:4:2: error: "Unexpected compiler version, expected Clang 15.0.0 or newer."
panicked at 'Unable to generate bindings: ClangDiagnostic("foo.cpp:4:2: error: \"Unexpected compiler version, expected Clang 15.0.0 or newer.\"\n")', C:\Users\NathanielWoods\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-cli-0.66.1\main.rs:52:36

C:\temp>clang --version
clang version 16.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: c:\program files\llvm\bin
````

Is it possible that `bindgen` is picking up the wrong `clang`?  How would I find out which one aside from going on a "search and destroy" mission on my hard drive?

Thanks!

**Comment by nwoods-cimpress** [comment]
Ok I definitely am picking up an old `clang`:

````
C:\temp>bindgen c:\temp\foo.cpp -- --version
clang version 14.0.6
Target: x86_64-w64-windows-gnu
````

**Comment by pvdrz** [comment]
We depend on `clang-sys` to use `libclang`. This means you can configure which version of clang are you using by tweaking your environment: https://github.com/KyleMayes/clang-sys#environment-variables

Usually `LIBCLANG_PATH` does the trick.

**Comment by nwoods-cimpress** [comment]
I got it working, thanks for your help!
