### ISSUE TITLE
bindgen doesn't generate impls for --target=wasm32-unknown-unknown

### ISSUE THREAD

**Issue by nwoods-cimpress** [rust-lang/rust-bindgen#2589]
### Input C/C++ Header

```C++
class Frobber
{
public:
  Frobber();
  
  int frob();
  
private:
  int m_myStuff;
};
```

### Bindgen Invocation

```
C:\>bindgen foo.h -- -x c++ --target=wasm32-unknown-unknown
```

### Actual Results

The implementation is missing

```rust
/* automatically generated by rust-bindgen 0.66.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Frobber {
    pub m_myStuff: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_Frobber() {
    const UNINIT: ::std::mem::MaybeUninit<Frobber> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Frobber>(),
        4usize,
        concat!("Size of: ", stringify!(Frobber))
    );
    assert_eq!(
        ::std::mem::align_of::<Frobber>(),
        4usize,
        concat!("Alignment of ", stringify!(Frobber))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_myStuff) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Frobber),
            "::",
            stringify!(m_myStuff)
        )
    );
}
```

### Expected Results

I would expect this to return something like this (though not with MSVC-style name mangling):

```rust
extern "C" {
    #[link_name = "\u{1}?frob@Frobber@@QEAAHXZ"]
    pub fn Frobber_frob(this: *mut Frobber) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}??0Frobber@@QEAA@XZ"]
    pub fn Frobber_Frobber(this: *mut Frobber);
}
impl Frobber {
    #[inline]
    pub unsafe fn frob(&mut self) -> ::std::os::raw::c_int {
        Frobber_frob(self)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        Frobber_Frobber(__bindgen_tmp.as_mut_ptr());
        __bindgen_tmp.assume_init()
    }
}
````

**Comment by nwoods-cimpress** [comment]
Reproduced in a debug build.  The funny thing is that when running a debug build on `x86_64-pc-windows-msvc`, I had to use `EDITBIN.EXE` to increase the stack size beyond 1 MB.

**Comment by nwoods-cimpress** [comment]
Ok some discoveries:

First, I was able to reproduce this problem with a much simpler header file; with this header file `bindgen -- --target=wasm32-unknown-unknown` simply ignores the declaration:
````C++
int frob(int x, char y);
````

Debugging side by side, I was able to narrow down the difference to the conditional on line 720 of `bindgen/ir/function.rs`:
https://github.com/rust-lang/rust-bindgen/blob/main/bindgen/ir/function.rs#L719-L722
````rust
impl ClangSubItemParser for Function {
    fn parse(
        cursor: clang::Cursor,
        context: &mut BindgenContext,
    ) -> Result<ParseResult<Self>, ParseError> {
        use clang_sys::*;

        let kind = match FunctionKind::from_cursor(&cursor) {
            None => return Err(ParseError::Continue),
            Some(k) => k,
        };

        debug!("Function::parse({:?}, {:?})", cursor, cursor.cur_type());
        let visibility = cursor.visibility();
        if visibility != CXVisibility_Default {
            return Err(ParseError::Continue);  // <-- BAILS HERE ONLY UNDER WEBASSEMBLY
        }
````

When compiling under `wasm32-unknown-unknown`, the visibility is not `CXVisibility_Default ` and the function bails.  When compiling conventionally, this logic does not bail.

As an experiment, I tried commenting out that code and observed the following results:
1. My trivial test case (`int frob(int x, char y);`) successfully generates Rust bindings
2. When compiling the original test case (`class Frobber`), `bindgen` panics downstream.

While I don't know much about the innards of Clang, it doesn't feel to be overly surprising that something called "visibility" might be different when compiling WebAssembly.

Still diving into things, and thanks!

**Comment by nwoods-cimpress** [comment]
Looks like adding `-fvisibility=default` to the Clang arguments makes the problem go away.  I have absolutely no idea if this should be considered something that `bindgen` should handle or not.

**Comment by pvdrz** [comment]
Hey! thanks for digging into this. 

I think `bindgen` bailing here is a bit weird. But I think it is equally weird for clang to return a non default visibility for a C struct :thinking:. However, if bindgen panics downstream it sounds like this bail out is necessary somehow. If I understood correctly, the panic only happens on C++ after you remove the bail out code, right?

**Comment by nwoods-cimpress** [comment]
Yes exactly - the panic only happens with the C++ code when I remove the conditional that bails out.  I made no attempt to investigate the panic, I just assumed that the panic was a response to a legit expectation that something be filtered out from the conditional.

**Comment by pvdrz** [comment]
I dug a bit deeper on this and what seems to happen is that the default visibility for WASM in the backend is hidden: https://github.com/WebAssembly/tool-conventions/issues/176

I wouldn't change the way bidngen behaves here, particularly because if the wasm folks change their mind and decide to change the visibility again then we would have to roll this back. However, I think it is important to document it somewhere.

**Comment by nwoods-cimpress** [comment]
Makes sense, thanks!
