### ISSUE TITLE
Provide an `allowlist_item` equivalent to `blocklist_item`

### ISSUE THREAD

**Issue by LoganDark** [rust-lang/rust-bindgen#2598]
Right now, there is a `blocklist_item` that doesn't care what type of item it is, but there doesn't seem to be an `allowlist_item` that serves the same purpose in reverse. So currently I have to do either:

```rs
		.allowlist_function("^LUA.*$")
		.allowlist_function("^lua.*$")
		.allowlist_function("^Luau::.*$")
		.allowlist_function("^gluau_.*$")
		.allowlist_var("^LUA.*$")
		.allowlist_var("^lua.*$")
		.allowlist_var("^Luau::.*$")
		.allowlist_var("^gluau_.*$")
		.allowlist_type("^LUA.*$")
		.allowlist_type("^lua.*$")
		.allowlist_type("^Luau::.*$")
		.allowlist_type("^gluau_.*$")
```
or
```rs
		.allowlist_function("^LUA.*$|^lua.*$|^Luau::.*$|^gluau_.*$")
		.allowlist_var("^LUA.*$|^lua.*$|^Luau::.*$|^gluau_.*$")
		.allowlist_type("^LUA.*$|^lua.*$|^Luau::.*$|^gluau_.*$")
```
even though directly below I can easily do
```rs
		.blocklist_item("^Luau::list$")
```

**Comment by pvdrz** [comment]
I don't see any reason to not have this but there might be a technical or usability issue that I'm not aware of (cc-ing @emilio in case he knows)

This shouldn't be hard to implement (but I might be wrong :sweat_smile:). 

A small suggestion, I think you don't need the `^` and `$` in your regular expressions as bindgen adds those automatically.

**Comment by LoganDark** [comment]
> bindgen adds those automatically

good to know, thanks~
