### ISSUE TITLE
Exclude windows.h

### ISSUE THREAD

**Issue by NiiightmareXD** [rust-lang/rust-bindgen#2604]
### Input C Headers

Headers: <https://github.com/winsiderss/systeminformer/tree/master/phnt>

### Bindgen Invocation

```Rust
bindgen::Builder::default()
        .clang_arg("-Iphnt\\include")
        .header(r"phnt\include\phnt_windows.h")
        .header(r"phnt\include\phnt.h")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .translate_enum_integer_types(true)
        .anon_fields_prefix("Anonymous")
        .default_visibility(bindgen::FieldVisibilityKind::Public)
        .impl_debug(true)
        .impl_partialeq(true)
        .derive_copy(true)
        .derive_debug(true)
        .derive_default(true)
        .derive_eq(true)
        .derive_partialeq(true)
        .layout_tests(false)
        .enable_function_attribute_detection()
        .disable_header_comment()
        .disable_nested_struct_naming()
        .rust_target(bindgen::RustTarget::Nightly)
        .vtable_generation(true)
        .allowlist_recursively(false)
        .generate()
        .expect("Unable to generate bindings");
```

### Actual Results
in the phnt_windows.h is includes windows.h and I want it to use windows-rs types instead of generating bindings for windows.h or atleast don't generate binding for windows.h at all but if I remove the windows.h from headers the code won't compile and no bindings will be generated

### Expected Results
use windows-rs or don't include windows.h at all

**Comment by pvdrz** [comment]
I don't have a windows machine so I cannot actually test this, but it sounds like the problem in unix-like systems with the `libc` crate. See this discussion (https://github.com/rust-lang/rust-bindgen/discussions/2599) for an example or how can you remove a whole type from the generated bindings and replace it by one imported from a crate.

**Comment by NiiightmareXD** [comment]
> I don't have a windows machine so I cannot actually test this, but it sounds like the problem in unix-like systems with the `libc` crate. See this discussion (#2599) for an example or how can you remove a whole type from the generated bindings and replace it by one imported from a crate.

Yea, that works I will use windows-rs instead of libc but the problem is that windows.h itself is about 90000 lines when the bidning are generated and I can't inspect all of those lines can I just make it so bindgen don't generate bidning for windows.h but use it so the actual header don't produces error?

**Comment by pvdrz** [comment]
well it all depends. If you use `--allowlist-file` with the file you're using as input that will only emit items that are the ones you have in the input file and the items that are dependencies of those (transitively). That would let you filter most of the `windows.h` item and then cherry-pick the ones you want from `windows-rs`

**Comment by NiiightmareXD** [comment]
> well it all depends. If you use `--allowlist-file` with the file you're using as input that will only emit items that are the ones you have in the input file and the items that are dependencies of those (transitively). That would let you filter most of the `windows.h` item and then cherry-pick the ones you want from `windows-rs`

thanks that worked I used this config:

```Rust
bindgen::Builder::default()
        .clang_arg("-Iphnt\\include")
        .header(r"phnt\include\phnt_windows.h")
        .header(r"phnt\include\phnt.h")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .translate_enum_integer_types(true)
        .anon_fields_prefix("Anonymous")
        .default_visibility(bindgen::FieldVisibilityKind::Public)
        .impl_debug(true)
        .impl_partialeq(true)
        .derive_copy(true)
        .derive_debug(true)
        .derive_default(true)
        .derive_eq(true)
        .derive_partialeq(true)
        .layout_tests(false)
        .enable_function_attribute_detection()
        .disable_header_comment()
        .disable_nested_struct_naming()
        .generate_comments(false)
        .rust_target(bindgen::RustTarget::Nightly)
        .vtable_generation(true)
        .allowlist_recursively(false)
        .allowlist_file(r"phnt\\include\\phnt.h")
        .generate()
        .expect("Unable to generate bindings");
```

it even works better with  `.allowlist_recursively(false)` I actually tried that before and it didn't work and I thought it is because I excluded windows.h but it seems like I have to put `\\` even in `r""` which was confusing

**Comment by NiiightmareXD** [comment]
Uhhhh now I get why because allowlist_file expects a regex and even though I used r"" to allow backslash in rust I have to make the backslash work in regex too

thanks for helping I will close the issue now

**Comment by pvdrz** [comment]
Glad to know you manage to solve this :)
