### ISSUE TITLE
Bindgen does not find some standard headers

### ISSUE THREAD

**Issue by Clueliss** [rust-lang/rust-bindgen#2612]
### Input C/C++ Header

input1.h
```c++
#include <stdlib.h>
```

input2.h
```c++
#include <stdalign.h>
```

### Bindgen Invocations
```
$ bindgen input1.h
$ bindgen input2.h
```

### Actual Results

for input1.h
```
/usr/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found
panicked at /home/liss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-cli-0.62.0/main.rs:52:36:
Unable to generate bindings: ClangDiagnostic("/usr/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found\n")
```

for input2.h
```
test.h:1:10: fatal error: 'stdalign.h' file not found
panicked at /home/liss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-cli-0.62.0/main.rs:52:36:
Unable to generate bindings: ClangDiagnostic("test.h:1:10: fatal error: 'stdalign.h' file not found\n")
```

### Notes
```
$ clang++ --version
```
```
clang version 16.0.6 (Fedora 16.0.6-2.fc38)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

What I noticed is that the more specialized headers (like `stdalign.h`, `stddef.h`...) are not located in `/usr/include`, instead they live at  `/usr/lib/gcc/x86_64-redhat-linux/13/include` / `/usr/lib64/clang/16/include`.

So just passing `bindgen input.h -- -isystem /usr/lib/gcc/x86_64-redhat-linux/13/include` fixes the problem.

**Comment by StellarHS** [comment]
In LLVM many standared header files may only find in the model `libcxx`. Get the model additionally may solve your problem.

**Comment by john01dav** [comment]
I see that this was closed, but where is the fix? I am using the latest bindgen from crates.io and I encountered this problem. I tried with the latest commit on the main branch from git and I still see it. I am using bindgen from build.rs, but I am getting errors about stddef.h missing. I could add that include path but then my build.rs is tied to Fedora/RHEL which is obviously undesirable, so I'd like to get whatever fix caused this issue to be closed.

**Comment by StellarHS** [comment]
I solved it by set the variable `INCLUDE` as `/path/to/gcc/headers`.
Use the `libclang.so` and headers of gcc. XD
I just use it compile gdnative.

**Comment by mstoeckl** [comment]
> I see that this was closed, but where is the fix?

I was able to reproduce this error message for Ubuntu (missing `limits.h` and missing `stddef.h` when using bindgen) -- the solution was to install the clang library packages providing those files. (Which for 24.10 were `libclang1-19` and `libclang-common-19-dev`; but `apt install clang` picked up both.)
