### ISSUE TITLE
No functions with wasm32-wasi

### ISSUE THREAD

**Issue by vmx** [rust-lang/rust-bindgen#2624]
I don't know if bindgen is supposed to work with the wasm32-wasi target or not. I might also do something wrong here.

### Input C/C++ Header

```C
int add(int aa, int bb)
```

### Bindgen Invocation

```
$ bindgen add.h -- -target wasm32-wasi --sysroot /opt/wasi-sdk/share/wasi-sysroot
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.66.1 */


```

### Expected Results

When I run `bindgen add.h -- -target x86_64-unknown-linux-gnu` I get:

```
/* automatically generated by rust-bindgen 0.66.1 */                                   

extern "C" {
    pub fn add(aa: ::std::os::raw::c_int, bb: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
```

which is what I also would expect from the `wasm32-wasi` target.

**Comment by vmx** [comment]
I forgot to mention that in case this is a bug, I'm happy to have a look into a possible fix (pointers are of course welcome).

**Comment by emilio** [comment]
The default visibility for wasm targets is hidden. I think if you pass the `-fvisibility=default` flag or so it should work.

**Comment by vmx** [comment]
Perfect thanks, that's it.

```console
> /bindgen add.h -- -target wasm32-wasi --sysroot /opt/wasi-sdk/share/wasi-sysroot -fvisibility=default
/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub fn add(aa: ::std::os::raw::c_int, bb: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
```

**Comment by joe-p** [comment]
For anyone using the `Builder` programmatically: `.clang_arg("-fvisibility=default")`
