### ISSUE TITLE
Macro as function are ignored

### ISSUE THREAD

**Issue by ValouBambou** [rust-lang/rust-bindgen#2626]
### Input C/C++ Header

```C++
#define N 10
#define N2 (N << 2)
#define FN(x) (x + 1)
#define N3 (FN(N))
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```
pub const N: u32 = 10;
pub const N2: u32 = 40;
```

### Expected Results
I expected the FN macro to be expanded to `10 + 1` and then evaluated to 11.

```rust
pub const N: u32 = 10;
pub const N2: u32 = 40;
pub const N3:u32 = 11;
```

**Comment by pvdrz** [comment]
Duplicated of https://github.com/rust-lang/rust-bindgen/issues/753
