### ISSUE TITLE
Fix to Objective-C header parsing has broken certain method calls

### ISSUE THREAD

**Issue by csmulhern** [rust-lang/rust-bindgen#2647]
### Input C/C++ Header

```Objective-C
@interface MyEvent

@property(nonatomic, retain) id type;

@end
```

### Bindgen Invocation

```
$ bindgen input.h -- -x objective-c
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.68.1 */

use objc::{self, class, msg_send, sel, sel_impl};
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct MyEvent(pub id);
impl std::ops::Deref for MyEvent {
    type Target = objc::runtime::Object;
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.0 }
    }
}
unsafe impl objc::Message for MyEvent {}
impl MyEvent {
    pub fn alloc() -> Self {
        Self(unsafe { msg_send!(class!(MyEvent), alloc) })
    }
}
impl IMyEvent for MyEvent {}
pub trait IMyEvent: Sized + std::ops::Deref {
    unsafe fn type_(&self) -> id
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, r#type)
    }
    unsafe fn setType_(&self, type_: id)
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, setType: type_)
    }
}
```

### Expected Results

type_ should be implemented as:

```rust
unsafe fn type_(&self) -> id
where
    <Self as std::ops::Deref>::Target: objc::Message + Sized,
{
    msg_send!(*self, type)
}
```

I believe this was caused by the changes in 97e29b49bebaba4d067d4f5f2270748c7d28a557.  While the fix in that commit fixes usage of `format_method_call` in parsing, `format_method_call` is also used in codegen, see:

https://github.com/rust-lang/rust-bindgen/blob/046d6f9eea1803253c06dd99a0d38f5dcb5ed9c1/bindgen/codegen/mod.rs#L4210

This change causes reserved words to escaped in the generated msg_send calls, which causes unrecognized selector errors at runtime (i.e. `-[MyEvent r#type]` is called instead of `-[MyEvent type]`).

@pvdrz, do you have any additional context here?

**Comment by pvdrz** [comment]
mmm... I checked out to 251dec9 which is the parent of 97e29b49 and the emitted code is still
```rust
pub trait IMyEvent: Sized + std::ops::Deref {
    unsafe fn type_(&self) -> id
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, r#type)
    }
    unsafe fn setType_(&self, type_: id)
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send ! (* self , setType : type_)
    }
}
```
so the culprit should be before that

**Comment by pvdrz** [comment]
I added a fix in #2648, @csmulhern could you let me know if this fixes your issue?

**Comment by csmulhern** [comment]
Ahh, sorry for the misleading attribution. #2648 does fix it! Thanks for the quick fix!

**Comment by pvdrz** [comment]
I opened https://github.com/rust-lang/rust-bindgen/issues/2652 to track the integration tests for objective-c
