### ISSUE TITLE
--version no longer works without <HEADER> argument

### ISSUE THREAD

**Issue by jbeich** [rust-lang/rust-bindgen#2677]
Regressed by #2656. Found via https://github.com/mesa3d/mesa/commit/1cc26e8b6657 due to https://github.com/mesonbuild/meson/commit/0f2f87a00347

```
$ bindgen --help | fgrep -A1 -- --version
  -V, --version
          Prints the version, and exits

$ bindgen --version
error: the following required arguments were not provided:
  <HEADER>

Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...

For more information, try '--help'.

$ bindgen --version /dev/null
bindgen 0.69.0
```

Previously,
```
$ bindgen --version
bindgen 0.68.1
```

**Comment by jbeich** [comment]
According to `git bisect` regressed by #2656.

**Comment by orhun** [comment]
Also hit this while generating shell completions:

```sh
$ bindgen --generate-shell-completions bash

error: the following required arguments were not provided:
  <HEADER>

Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...

For more information, try '--help'.
```

**Comment by erik-bershel** [comment]
Hey @orhun! How long it will take theoretically to fix this issue (to publish release)? We are blocked with an image generation for actions with this bug and thinking now about what to do next. To pin version of cli or to wait new release...

**Comment by orhun** [comment]
Hey @erik-bershel, I'm just an outside contributor so I'm not sure. The PR should be ready to go though.

**Comment by felixonmars** [comment]
This breaks the build of mesa because they rely on `--version` to determine whether passing `--size_t-is-usize` or not: https://gitlab.freedesktop.org/mesa/mesa/-/commit/a9cce40dab3218a8bda043387e1df0e27aba211b

**Comment by tshepang** [comment]
@erik-bershel a fresh release is available with the issue fixed

**Comment by jbeich** [comment]
Please, reopen. Regressed again by 4d809171a7ac:
```
$ bindgen --version /dev/null
bindgen 0.71.0
$ bindgen --version
error: the following required arguments were not provided:
  <HEADER>

Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...

For more information, try '--help'.
```
