### ISSUE TITLE
Subtract underflow when generating explicit paddings

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust-bindgen#2695]
### Input C/C++ Header

```C
#pragma pack(2)

struct Test {
        unsigned long x;
        char a;
        char b;
        char c;
};

```

### Bindgen Invocation

```
$ bindgen input.h --explicit-padding
```

### Actual Results

```
panicked at bindgen/codegen/struct_layout.rs:309:20:
attempt to subtract with overflow
```

### Analysis

The reason this happens is because in `saw_field_with_layout`, padding bytes size is always calculated using the specified pack alignment, i.e. 2 bytes. however, if the field itself has a smaller alignment requirement, that should be used instead.

**Comment by yshui** [comment]
And padding is not generated for packed layout with align > 1, I will open another bug after this is fixed.

**Comment by Connor-GH** [comment]
This should probably still be open; affects me on 0.71.1.
