### ISSUE TITLE
feat: add blocklist_var

### ISSUE THREAD

**Issue by dhruvin-dev** [rust-lang/rust-bindgen#2730]
### Input C/C++ Header

```C++
extern int should_be_blocked;
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("input.h")
    .blocklist_var("should_be_blocked")
    .generate()
    .unwrap()
```

or

```
$ bindgen input.h --blocklist-var should_be_blocked
```

### Actual Results

There's no method to blocklist a variable.

### Expected Results

`blocklist_var` is the only missing `allowlist_*` mirror method. I don't yet see any use besides having parity with `allowlist`. I have a patch ready, if we decide to implement this.

**Comment by emilio** [comment]
Fixed by https://github.com/rust-lang/rust-bindgen/pull/2731
