### ISSUE TITLE
shlex <1.3 has serious security issue

### ISSUE THREAD

**Issue by notmgsk** [rust-lang/rust-bindgen#2733]
https://github.com/comex/rust-shlex/security/advisories/GHSA-r7qv-8r2h-pg27

Suggested resolution is to bump `shlex` version `shlex = "1.3"`.

**Comment by pcmenke** [comment]
The Cargo.lock file has been updated https://github.com/rust-lang/rust-bindgen/blob/main/Cargo.lock#L571 but not the Cargo.toml https://github.com/rust-lang/rust-bindgen/blob/main/bindgen/Cargo.toml#L41

**Comment by emilio** [comment]
I think this is fine as-is. As per the above we don't use smaller versions. But happy to take a patch to bump the toml file too.
