### ISSUE TITLE
Add a `Builder::headers` helper

### ISSUE THREAD

**Issue by kupiakos** [rust-lang/rust-bindgen#2738]
Much like `clang_args`, a helper for adding multiple headers in a chained builder expression. The signature should be:

```rust
pub fn headers<I: IntoIterator>(self, headers: I) -> Self where I::Item: Into<String>
```

**Comment by christianheussy** [comment]
I'm learning Rust and took a crack at this!

**Comment by tshepang** [comment]
should this be closed

**Comment by pvdrz** [comment]
I think so, there's a commit on main with the change. @christianheussy feel free to reopen this if your changes didn't made it to main for some reason.

**Comment by christianheussy** [comment]
They did, thanks for closing!
