### ISSUE TITLE
Strip leading \brief or \short at the start of Doxygen comment

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/rust-bindgen#2755]
`rustdoc` treats the first paragraph of an item's description as a brief description to be used in higher level docs (module item list, etc). Historically, Doxygen has required use of `\brief` or `\short` to achieve the same effect. Nowadays you can use [JAVADOC_AUTOBRIEF](https://www.doxygen.nl/manual/config.html#cfg_javadoc_autobrief) instead, but many older C/++ projects will still use the `\brief` or `\short` Doxygen directive style.

As a result, the autogenerated rustdoc ends up being spammed with leading `\brief`s:

![image](https://github.com/rust-lang/rust-bindgen/assets/1305080/b781f417-f5e2-436b-bfe3-bf5984695e55)

It would be great if `bindgen` could detect `\brief`s at the start of Doxygen comments and strip them off instead.

### Input C/C++ Header

```C++
/** \brief Object info attribute (name and value strings)
 *
 * \sa hwlocality_info_attr
 */
struct hwloc_info_s {};
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

Bindgen keeps the leading `\brief` in the rustdoc output, resulting in the rustdoc `\brief` spam illustrated above.

```rust
#[doc = " \\brief Object info attribute (name and value strings)\n\n \\sa hwlocality_info_attr"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hwloc_info_s {}
```

### Expected Results

Bindgen strips the leading `\brief` to switch to rustdoc's brief description convention.

```rust
#[doc = "Object info attribute (name and value strings)\n\n \\sa hwlocality_info_attr"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hwloc_info_s {}
```

**Comment by laurooyen** [comment]
I've come across a similar problem with same-line documentation, often used for struct fields or enums.
```cpp
enum Foo {
    FOO_A, ///< A description
    FOO_B, ///< Another description
};
```
The `<` is copied over to the Rust documentation. A generic solution to trim the start of documentation strings, maybe through `ParseCallbacks` could be usefull.

**Comment by pvdrz** [comment]
Sounds like something you could do via [`process_comment`](https://docs.rs/bindgen/latest/bindgen/callbacks/trait.ParseCallbacks.html#method.process_comment)

**Comment by pvdrz** [comment]
I'm closing this issue as doxygen-rs should be able to handle both your use cases. I think any extra functionality regarding doxygen parsing should be requested to the doxygen-rs' folks to avoid duplication of efforts and because they probably have a better idea of how to solve such issues than us.
