### ISSUE TITLE
Have some easy way to #[allow(non_camel_case_types)] (or even do it by default)

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/rust-bindgen#2757]
C and C++ commonly use `snake_case` type names, so the `non_camel_case_types` default rustc lint generates a lot of noise in bindgen-originated modules. There should at least be an easy way to disable this lint in bindgen's output, and imo it should be turned off by default.

**Comment by HadrienG2** [comment]
After closer investigation, `--raw-line` can be used to inhibit the lint quite easily, so the only remaining question is, should bindgen make it the default.

**Comment by pvdrz** [comment]
Even though having it as a default sounds like an attractive proposition, it would require to have an option to opt out from this behavior as bindgen's API is pretty large already.

This also opens the door to have other attributes injected by default and, as a consequence, more options to not inject those attributes.
