### ISSUE TITLE
Bindgen release

### ISSUE THREAD

**Issue by GKFX** [rust-lang/rust-bindgen#2802]
Hi @emilio, would it be possible for there to be a new release? I'd like to be able to use the compile-time layout tests.

**Comment by jschwe** [comment]
@emilio It seems you already updated the changelog last month to prepare for a release. Are there any issues currently blocking a release?

**Comment by jschwe** [comment]
@pvdrz @emilio  Any chance one of you could create a new release? It's been quite a while since the last one.

**Comment by pvdrz** [comment]
on it :wrench:

**Comment by GKFX** [comment]
Thanks!
