### ISSUE TITLE
Blocklist/allowlist based on header

### ISSUE THREAD

**Issue by kellda** [rust-lang/rust-bindgen#2811]
Selecting items to generate based on the header where they're defined would be a convenient alternative to selecting them by name.

Clang's API allows getting the `CXSourceLocation` for definitions, which then allows to get the source file for it.

@rustbot label enhancement

**Comment by emilio** [comment]
Isn't `--allowlist-file` just this?

**Comment by kellda** [comment]
Yes, it's exactly that. I don't know why I didn't found it, sorry for that.
