### ISSUE TITLE
allowlist_item does not work for anonymous enums - allowlist_var does

### ISSUE THREAD

**Issue by hkonetzky** [rust-lang/rust-bindgen#2826]
### Input C/C++ Header

```C++
enum
{
  BASS_FX_BFX_ROTATE = 0x10000
  BASS_FX_BFX_ECHO,
  BASS_FX_BFX_FLANGER
};
```

### Bindgen Invocation

```
$ bindgen input.h --allowlist-item "BASS.*" -o output.rs
```

### Actual Results

empty file - apart from the bindgen comment

one warning is outputted by bindgen: `bindgen::ir::context] unused option: --allowlist-items BASS.*`

### Expected Results

consts generated like this (works when omitting the `allowlist-items` flag or using `allowlist-var` instead):

```rust
/* automatically generated by rust-bindgen 0.69.4 */

pub const BASS_FX_BFX_ROTATE: _bindgen_ty_1 = 65536;
pub const BASS_FX_BFX_ECHO: _bindgen_ty_1 = 65537;
pub const BASS_FX_BFX_FLANGER: _bindgen_ty_1 = 65538;
pub type _bindgen_ty_1 = ::std::os::raw::c_int;
```

**Comment by pvdrz** [comment]
Thanks for the report!

It seems that anonymous enums need some special casing that was overlooked when `--allowlist-item` was implemented.
