### ISSUE TITLE
Unable to run bindgen on ubuntu 22.04

### ISSUE THREAD

**Issue by uglyoldbob** [rust-lang/rust-bindgen#2837]
When running bindgen on an ubuntu 22.04 system, I get an assert error.

thread 'main' panicked at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.4/lib.rs:899:13:
  assertion `left == right` failed: "x86_64-unknown-linux-gnu" "x86_64-unknown-linux-gnu"
    left: 2
   right: 8
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by uglyoldbob** [comment]
Apparently bindgen was picking up clang for a totally different architecture. I just uninstalled it and its working now.

**Comment by Nohac** [comment]
I'm getting this exact error on Arch Linux, but only when building in debug mode, building with `--release` works as expected. Is there a way to debug this issue? The output tells me nothing about what compilers or clang versions are being used, so it's a bit difficult to know what to do.
