### ISSUE TITLE
bindgen has bumped MSRV without updating semver

### ISSUE THREAD

**Issue by CGMossa** [rust-lang/rust-bindgen#2850]
Hey! We've been using `0.69.4` for a while, and suddenly the MSRV was bumped to `1.70`. 
The reason for this is the `home`-crate.

```sh
cargo clean; rm Cargo.lock; cargo msrv --min 1.67.0
# redacted
Check for toolchain '1.69.0-aarch64-apple-darwin' failed with:
┌──────────────────────────────────────────────────────────────────────────┐
│ error: package `home v0.5.9` cannot be built because it requires rustc   │
│ 1.70.0 or newer, while the currently active rustc version is 1.69.0      │
│ Either upgrade to rustc 1.70.0 or newer, or use                          │
│ cargo update -p home@0.5.9 --precise ver                                 │
│ where `ver` is the latest version of `home` supporting rustc 1.69.0      │
└──────────────────────────────────────────────────────────────────────────┘
   Finished The MSRV is: 1.70.0
   ```

It has caused a bit of trouble for us, that we suddenly have to bump MSRV to `1.70.0`. Is it at all possible for someone to deal with this?

**Comment by madsmtm** [comment]
Hmm, the `home` crate does not seem to be a dependency of `bindgen`?

Besides, `bindgen` does not have an established MSRV policy (see the README), so such a bump is not a violation of SemVer.

In any case, I'd suggest you resolve this by applying the solution suggested by Cargo.

**Comment by CGMossa** [comment]
Thanks for the answer. You've now answered two questions from me, so thank you very much.

I ran this 
```sh
cargo update -p home@0.5.9 --precise 0.5.5
```

and then the MSRV is `The MSRV is: 1.67.1`. How do I make that the case for my library and all dependents of it? Do I just commit the `Cargo.lock` file?

**Comment by madsmtm** [comment]
> How do I make that the case for my library and all dependents of it?

You should not, you should raise your own MSRV to match the dependency, and then tell users on lower Rust versions the same advice as here (i.e. to follow Cargo's suggestions).

**Comment by pvdrz** [comment]
Closing as bindgen 0.69.4 effectively compiles with a 1.69.0 toolchian.
