### ISSUE TITLE
How to handle C array of undefined size?

### ISSUE THREAD

**Issue by mgeier** [rust-lang/rust-bindgen#2883]
### Input C/C++ Header

```C++
extern FLAC_API const char * const FLAC__StreamMetadata_Picture_TypeString[];
```

This is the declaration in the header file: https://github.com/xiph/flac/blob/28e4f0528c76b296c561e922ba67d43751990599/include/FLAC/format.h#L764-L771

And here's the definition (which I guess isn't visible to `bindgen`): https://github.com/xiph/flac/blob/28e4f0528c76b296c561e922ba67d43751990599/src/libFLAC/format.c#L185-L207

### Bindgen Invocation

```
$ bindgen wrapper.h -o ../src/bindings.rs \
	--disable-name-namespacing \
	--no-doc-comments \
	--no-prepend-enum-name \
	--use-core \
	--ctypes-prefix libc \
	--allowlist-function "FLAC_.*" \
	--allowlist-type "FLAC_.*" \
	--allowlist-var "FLAC_.*" \
	--blocklist-type FILE \
	--blocklist-type "_IO_.*" \
	--
```

### Actual Results

```rust
extern "C" {
    pub static FLAC__StreamMetadata_Picture_TypeString: [*const libc::c_char; 0usize];
}
```

I have used this in the past to access array elements:

```rust
    let ptr = unsafe { *FLAC__StreamMetadata_Picture_TypeString.get_unchecked(idx) };
```

But recently I've been getting this panic (in debug mode):

```
unsafe precondition(s) violated: slice::get_unchecked requires that the index is within the slice
```

This is understandable, since it is defined as zero-element array, but it has more than zero elements in the C library ...

I could work around this by using something like:

```rust
    let ptr = unsafe { *FLAC__StreamMetadata_Picture_TypeString.as_ptr().add(idx) };
```

But is this the right thing to do?

### Expected Results

I don't know!

Maybe something has to be changed in the original C definitions?

I'd be grateful for any hints!

**Comment by pvdrz** [comment]
I wouldn't suggest modifying the C definition as [it seems](https://xiph.org/flac/api/group__flac__format.html#ga2d27672452696cb97fd39db1cf43486b) this array is supposed to be indexed by values of the `FLAC__StreamMetadata_Picture_Type` enum and [those values](https://github.com/xiph/flac/blob/192bf227ae87047797c391d8d342c07f8d993769/include/FLAC/format.h#L739-L762) could easily change in the future, right now they go up to 20 so you could argue that this should be an array of 20 elements but I wouldn't set that in stone.

I would argue that having zero sized arrays as the default representation of unsized C arrays is not the most correct thing and maybe bindgen should translate them as pointers instead. But for the meantime, I think your solution is correct. You could wrap such logic in a function to avoid issues in the future

```rust
fn get_picture_type(idx: FLAC__StreamMetadata_Picture_Type) -> Option<const* c_char> {
    if idx == FLAC__STREAM_METADATA_PICTURE_TYPE_UNDEFINED {
        None
    } else {
        Some(unsafe { *FLAC__StreamMetadata_Picture_TypeString.as_ptr().add(idx) })
    }
}
```
