### ISSUE TITLE
Installing bindgen twice with `cargo install --locked` creates different binaries.

### ISSUE THREAD

**Issue by NickeZ** [rust-lang/rust-bindgen#2884]
Hello!

I'm trying to create container images that are reproducible. Installing other tools like `cbindgen` does not have the same issue, therefore I think `bindgen-cli` is doing something different. Since I have a workaround, this isn't urgent. But perhaps someone else runs into the same issue, therefore I write this bug report.

What I would like to run in my Dockerfile:

```
cargo install --locked bindgen-cli --version 0.69.4
```

### Actual Results

Looking at the binary with `strings` I see that it contains references to what I believe is its target directory: `/tmp/cargo-installxmn5lp/release`

### Expected Results

I expect two invocations of `cargo install --locked` to generate the same binary.

### Workaround
I found that specifying the target-dir works:
```
cargo install --locked bindgen-cli --version 0.69.4 --target-dir=/tmp/bindgen-target
```

Regards

**Comment by pvdrz** [comment]
Hi @NickeZ. Thanks for the report.

After doing the same inspection with `strings` it seems those are the error strings that `clang-sys` would display while trying to load `libclang` dynamically. So I suspect that disabling the `runtime` feature and enabling the `static` feature and providing a static `libclang` should remove those. However, clang no longer distributes static libraries so you'd have to compile them from source.

You could use the [binary release](https://github.com/rust-lang/rust-bindgen/releases/tag/v0.69.4) of bindgen as a workaround.

**Comment by NickeZ** [comment]
Thanks! I'll look into the binary releases
