### ISSUE TITLE
Generate `unsafe extern` blocks (Edition 2024)

### ISSUE THREAD

**Issue by marmitar** [rust-lang/rust-bindgen#2901]
I know Edition 2024 is very experimental at the moment, so this is more of a heads-up than an actual issue.

### Description

Rust has just implemented [RFC 3484](https://github.com/rust-lang/rfcs/blob/master/text/3484-unsafe-extern-blocks.md), requiring all `extern` blocks to be marked `unsafe extern` in Edition 2024. Older editions don't yet compile this `unsafe extern` construct (as of the latest stable, `rustc-1.80.0`), but they will eventually accept the `unsafe` keyword for compatibility reasons. This crate needs some way of generating bindings with this future requirements, either via `Builder` configuration, or by detecting the current edition.

I've implemented a minimal (but complete) example that triggers the error here: [bindgen-unsafe-extern](https://github.com/marmitar/bindgen-unsafe-extern).

### Input C/C++ Header

```C
void cool_function(int i, char c);
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("src/cool.h")
    .generate()
    .unwrap()
    .write_to_file("src/cool.rs")
    .unwrap()
```

### Actual Results

Generated file:

```rust
extern "C" {
    pub fn cool_function(i: ::std::os::raw::c_int, c: ::std::os::raw::c_char);
}
```

Compiler error:

```log
error: extern blocks must be unsafe
 --> src/cool.rs:3:1
  |
3 | / extern "C" {
4 | |     pub fn cool_function(i: ::std::os::raw::c_int, c: ::std::os::raw::c_char);
5 | | }
  | |_^
```

### Expected Results

For Edition 2024, the generated file should be:

```rust
unsafe extern "C" {
    pub fn cool_function(i: ::std::os::raw::c_int, c: ::std::os::raw::c_char);
}
```

**Comment by GKFX** [comment]
It's worth noting that Edition 2024 safe extern functions, plus either the proposed `[[safe]]` attribute for C ([N2659](https://www.open-std.org/JTC1/SC22/WG14/www/docs/n2659.htm)) or an equivalent, would solve #2774.

**Comment by ojeda** [comment]
The proposed `[[safe]]` attribute did not get enough support from the committee back then, but lately memory safety is talked about more in WG14 and is in the latest charter, so perhaps things change. Rust `safe` functions within `unsafe` blocks could help there.

Or perhaps a C implementation wants to add something like that to improve interop with Rust for their users.

**Comment by ehuss** [comment]
Just FYI, `unsafe extern` is now stabilized in all editions in 1.82.0 (2024-10-17). And just a heads up that we are still aiming to have the 2024 edition hit stable in 1.85 (2025-02-20).

**Comment by pvdrz** [comment]
once #3002 is merged, bindgen will have support for editions. However, it seems to me that this should be enabled regardless of the edition for every rust target greater or equal than 1.82 as not using `unsafe extern` will generate a warning for all the other editions anyway. Is that correct?

**Comment by ojeda** [comment]
Yeah, as far as I can see, the lint is not enabled by default (`rust_2024_compatibility` or `missing_unsafe_on_extern`) but it can be used starting with 1.82 even for 2015, so it could help those that want to enable the warning.
