### ISSUE TITLE
Clippy warning with 0.70: this operation has no effect

### ISSUE THREAD

**Issue by michaellass** [rust-lang/rust-bindgen#2905]
bindgen 0.70 produces code that causes a clippy warning due to operations that have no effect. This is a regression as 0.69 did not produce these warnings.

### Input C/C++ Header

```C++
struct foo {
    int bar;
};
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
        .header("header.h")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .unwrap();
```

### Actual Results

cargo clippy prints the following warning:

```
warning: this operation has no effect
  --> /home/bevan/bindgen-test/target/debug/build/bindgen-test-eabc42a75cc3e549/out/bindings.rs:11:35
   |
11 |     ["Offset of field: foo::bar"][::std::mem::offset_of!(foo, bar) - 0usize];
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider reducing it to: `{builtin # offset_of($Container, $($fields)+)}`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_op
   = note: `#[warn(clippy::identity_op)]` on by default
```

### Expected Results

I would expect no clippy warnings from the generated code.

**Comment by emilio** [comment]
I'd file a clippy bug, but we could also `#[allow()]` it I guess.

**Comment by emilio** [comment]
Clearly `{builtin # offset_of($Container, $($fields)+)}` is not code you can replace the expression with, so that seems worth fixing.

**Comment by michaellass** [comment]
Having no clue about the bindgen code and ignoring that weird clippy suggestion: ` - 0usize` looks like a noop, doesn't it?

**Comment by lure23** [comment]
It is a no-op, but I took that the authors wanted to document the sizes and alignments to us humans, in this way. It's really clever and way more readable than `test`s (I believe) in 0.69. I hope they remain.

**Comment by pvdrz** [comment]
I'll push a fix and release a patch version later
