### ISSUE TITLE
Linking issues when using Rust-bindgen for a USB CAN driver DLL

### ISSUE THREAD

**Issue by notmmao** [rust-lang/rust-bindgen#2925]
Hi, I am working on creating bindings for a USB-based CAN driver DLL for Windows using Rust. I followed the [Rust-bindgen guide](https://rust-lang.github.io/rust-bindgen/) and successfully generated the bindings.rs file. I also ran tests using cargo test, and everything worked smoothly. 

However, I ran into an issue when moving forward. The current project, let's call it can-sys, is not the final application but rather a library I intend to distribute (I'm not sure if the correct term in Rust is "lib"). When I tried to include can-sys in another project, let's call it can-app (locally imported), I encountered a linking error.

Here are my main points of confusion:

1. Do I still need to write a build.rs in the can-app project?
2. If required, should I bundle the .dll, .lib, and .h files when distributing can-sys?
3. Could you add some guidance to the documentation explaining how a project like xxx-app should properly link to a project like xxx-sys?

Thanks in advance for any help, and I appreciate all the great work on Rust-bindgen!

**Comment by pvdrz** [comment]
>     1. Do I still need to write a build.rs in the can-app project?

AFAIK you shouldn't need to as the build script for the hypotetical can-sys crate should already handle the linking to the library. Some authors include some mechanism in their sys crates so you can set the path to the library. See [`clang-sys`](https://github.com/KyleMayes/clang-sys?tab=readme-ov-file#environment-variables) as an example where you can set the path to the library using env variables)

>     2. If required, should I bundle the .dll, .lib, and .h files when distributing can-sys?

That's up to you, some folks write their build script in such a way it fails with a helpful message explaning how to install the library if it is not found.

>     3. Could you add some guidance to the documentation explaining how a project like xxx-app should properly link to a project like xxx-sys?

I find this tricky as basically everyone handles this however they see fit. But if you have the library already installed, using the sys crate shouldn't require any extra steps in comparison to a regular dependency.

**Comment by notmmao** [comment]
Thank you for your reply. 

> I find this tricky as basically everyone handles this however they see fit. But if you have the library already installed, using the sys crate shouldn't require any extra steps in comparison to a regular dependency.

Not having a solution that I think is `fit` might really be the real difficulty I'm facing now, because this is my first attempt to write Rust bindings for a DLL. I don't even know where to start or what more templates to refer to. 
Now I'm searching on crates.io and analyzing the project structure, but I always feel uncertain due to the lack of guidance.

**Comment by pvdrz** [comment]
the crates I'm most familiar with, would be [`clang-rs`](https://github.com/KyleMayes/clang-rs) and [`clang-sys`](https://github.com/KyleMayes/clang-sys) where the former doesn't have a build script at all and the latter handles all the linking in its build script but doesn't distribute the binaries for the library itself.
