### ISSUE TITLE
Confusion about dependencies on Debian based Linux

### ISSUE THREAD

**Issue by e00E** [rust-lang/rust-bindgen#2934]
The user guide says [here](https://rust-lang.github.io/rust-bindgen/requirements.html#debian-based-linuxes) that bindgen requires these Debian packages: llvm-dev, libclang-dev, clang.

However, the page also says at the top that bindgen "leverages libclang". So why are we installing anything besides libclang-dev?

I tested this briefly. On a fresh Debian system I install Rust and run `cargo test` in this repository. When I install only libclang-dev, 4 tests fail (dump_preprocessed_input, header_atomic_constant_h, header_issue_753_h, header_ptr32_has_different_size_h). Installing clang makes dump_preprocessed_input pass. Installing llvm-dev makes no difference.

**Comment by emilio** [comment]
Yeah, `dump_preprocessed_input` relies on the clang executable, though it's a somewhat niche / debugging feature. If llvm-dev makes no difference please send a patch fixing the docs, it'd be appreciated :)
