### ISSUE TITLE
Backport commit 35f0f9a to 0.70.x series (clang_getFileLocation instead of clang_getSpellingLocation)

### ISSUE THREAD

**Issue by yonas** [rust-lang/rust-bindgen#2948]
Backport this fix https://github.com/rust-lang/rust-bindgen/commit/35f0f9aafc9b25c3bf05cc49d9c23515e0c53141 into the 0.70.x series.

On FreeBSD, https://www.freshports.org/devel/rust-bindgen-cli  will pick it up as a new release.

Fixes: https://github.com/aws/aws-lc-rs/issues/476

**Comment by emilio** [comment]
But it's already in 0.70.1 right? Or what am I missing?

**Comment by pvdrz** [comment]
> But it's already in 0.70.1 right? Or what am I missing?

Yes this change was published first on 0.70.0.

I find this request intriguing as 0.69.5 was released exclusively to address the issue that `aws-lc-rs` couldn't use bindgen 0.70.0 and further due to their MSRV and they needed this change.

**Comment by yonas** [comment]
I don't see the commit in:

https://github.com/rust-lang/rust-bindgen/compare/v0.70.0...main
https://github.com/rust-lang/rust-bindgen/compare/v0.70.1...main

**Comment by emilio** [comment]
Correct, because it's in https://github.com/rust-lang/rust-bindgen/compare/v0.69.4...v0.70.0

I think this doesn't need any change on our end unless I'm missing something.

**Comment by emilio** [comment]
(Please reopen if that's the case!)

**Comment by pvdrz** [comment]
I think part of the confusion might have to do with the fact that git doesn't use the same hash for the cherry-picked commit that appears on 0.69.5 (35f0f9a) and the one that's on the default tree (600f638):
```bash
$ git show --no-patch 35f0f9a
commit 35f0f9aafc9b25c3bf05cc49d9c23515e0c53141 (origin/llvm-19-fix, llvm-19-fix)
Author: Mike Hommey <mh@glandium.org>
Date:   Tue Apr 30 05:40:58 2024 +0900

    Use clang_getFileLocation instead of clang_getSpellingLocation

    Both had the same behavior... until https://github.com/llvm/llvm-project/commit/2e770edd8ce13f48402f1d93e5fb982d8a2ebe64
    which fixed getSpellingLocation, but bindgen looks like it actually expects
    the getFileLocation result.
$ git tag --contains 35f0f9a
v0.69.5
$ git show --no-patch 600f638
commit 600f63895f73c80d6bf7ff3c71b86a068d1663d2
Author: Mike Hommey <mh@glandium.org>
Date:   Tue Apr 30 05:40:58 2024 +0900

    Use clang_getFileLocation instead of clang_getSpellingLocation

    Both had the same behavior... until https://github.com/llvm/llvm-project/commit/2e770edd8ce13f48402f1d93e5fb982d8a2ebe64
    which fixed getSpellingLocation, but bindgen looks like it actually expects
    the getFileLocation result.
$ git tag --contains 600f638
v0.70.0
v0.70.1
```
