### ISSUE TITLE
bindgen (or clang?) wrongly assumes return by register for tiny c++ classes

### ISSUE THREAD

**Issue by fneddy** [rust-lang/rust-bindgen#2992]
disclaimer: i only tested Linux on x86_64 

when bindgen creates bindings for functions that return a very tiny(<=0x10 bytes) **classes by value** it will assume return **in register** rax and rdx if the class fits in this registers. 
in my tests g++ and clang++ will **always return a `class`  on the stack**.

this can be noticed when generating bindings for [lldb](https://lldb.llvm.org/cpp_reference/namespacelldb.html) (the llvm debugger), as it wraps all internal objects with tiny wrapper classes and **always** [returns objects by value](https://lldb.llvm.org/cpp_reference/classlldb_1_1SBDebugger.html#a0e423c608ce554a133d8611578da5f7f)

my workaround i found so far is:
- mark all the classes as _opaque_  => `.opaque_type(".*")`
- insert phantom data into the the rust type definition by replacing `pub _bindgen_opaque_blob` with `pub _bindgen_phantom: [u64; 3usize], pub _bindgen_opaque_blob`

this will force the compiler to assume return by stack for all the types.

i don't know of any option how to tell the compiler that a  function will return by stack. so i think is is actually a problem in the rust compiler, as it cannot differentiate between `POD` and `c++ class`.

as a workaround it would be nice to have an bindgen extended option to **insert phantom bytes** into opaque classes so the compiler will assume return by stack.

**Comment by fneddy** [comment]
this is the snipped from my `build.rs` to make the bindings work:

```
   ...
    let bindings = bindgen::Builder::default()
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .header(format!("{}/lldb/API/LLDB.h", llvm_headers_path))
        .layout_tests(false)
        .allowlist_item("lldb::.*")
        .opaque_type(".*")
        .no_copy("lldb::.*")
        .enable_cxx_namespaces()
        .generate_cstr(true)
        .clang_arg("-xc++")
        .generate()
        .expect("Unable to generate bindings");

    let bindings = bindings.to_string().replace(
        "pub _bindgen_opaque_blob",
        "pub _bindgen_phantom: [u64; 3usize], pub _bindgen_opaque_blob",
    );

    let mut file = OpenOptions::new()
        .write(true)
        .truncate(true)
        .open(PathBuf::from("./src/").join("bindings.rs"))
        .expect("could not open bindings file");

    file.write(bindings.as_bytes())
        .expect("could not write bindings file");
    ...
```

**Comment by emilio** [comment]
Yes this is a known thing, see #778 and MSVC equivalent #2865

**Comment by Zack-asdf776** [comment]
hi, I get a segfault calling a small C++ function through bindgen — the type has a custom destructor:
 
```cpp
struct SBError {
    unsigned int e;
    SBError();
    ~SBError();
};
 
SBError make_error();
```
 
bindgen emits:
 
```rust
pub fn make_error() -> SBError;
```
 
looks fine, but it seems to go through a hidden pointer on the C++ side (RVO / sret) that Rust doesn't set up. Is there a way to handle the non-trivial-destructor case? (0.72.0)

**Comment by emilio** [comment]
The only way is to don't pass these by value unfortunately.
