### ISSUE TITLE
No more prebuilt binaries/installer in the v0.71.0 release

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rust-bindgen#3038]
Hello,

I have observed that the recent GitHub release (https://github.com/rust-lang/rust-bindgen/releases/tag/v0.71.0) omits the previously included artifacts, such as the prebuilt binaries and an accompanying installer script.

Rustup’s current CI workflow relies on these artifacts. While we have a fallback mechanism in place to execute `cargo install` in the event of failure, I would like to know whether this change was intentional so that we will be able to adjust our setup accordingly.

Many thanks in advance!

**Comment by pvdrz** [comment]
Hey, we're reorganizing our release process and there are some rough edges still. If you really need them we can keep generating them regularly.

**Comment by pvdrz** [comment]
I redid the release to include the binaries
