### ISSUE TITLE
Bindgen 0.71.1 has broken my builds with rustc < 1.82.0

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rust-lang/rust-bindgen#3054]
See https://github.com/andrewdavidmackenzie/libproc-rs/issues/157

Despite bindgen having minimum rust version at 1.70.0

**Comment by ojeda** [comment]
Please provide the details here.

Are you referring to the `unsafe extern` blocks issue? If so, if you were actually passing that minimum version to `bindgen`, then it should work. Can you please show how you call it, and ideally a repro?

**Comment by pvdrz** [comment]
bindgen having an msrv of 1.70 means that bindgen will compile with 1.70.

If you want bindgen to generate code that's compatible with a specific Rust version, you have to use `--rust-target` or `Builder::rust_target`.

**Comment by andrewdavidmackenzie** [comment]
Hi, thanks for comments. Something has changed in this regard between 0.70.0 and 0.71.0/0.71.1 that has broken it.

But I'm fine with "doing it right" to un-break my builds if I can.

I invoke Builder in my build.rs script for libproc-rs, then CI test it on a matrix, including as far back as my (previous) minimum rust of 1.72.0.

Should I invoke Builder with .rust_target(RustTarget::stable(72, 0) for all my builds, as code generated for 1.72.0 should be compilable by all after it as well?

**Comment by andrewdavidmackenzie** [comment]
I've tried that and works. So I am closing this issue.

**Comment by ojeda** [comment]
> Should I invoke Builder with .rust_target(RustTarget::stable(72, 0) for all my builds,

If you are not doing that, then you are getting the latest stable Rust known by the given `bindgen`'s version.

> as code generated for 1.72.0 should be compilable by all after it as well?

If you mean if Rust is backwards compitable, then yes, unless you are using unstable features etc.

**Comment by pvdrz** [comment]
@andrewdavidmackenzie happy to know you made it work.

Just to exapnd on what @ojeda said: This breaking change was introduced because the most recent Rust version emits a warning for code that was legal before. The issue is that the fix is not backwards compatible. For future reference, you can also write your `RustTarget` as a `&str` and parse it:
```rust
builder.rust_target("1.72.0".parse().unwrap())
```
