### ISSUE TITLE
Our polyfill for `__float128` should have 16 byte alignment

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/rust-bindgen#317]
Right now it is an array of `u8` and has 1 byte alignment, I think.

`u128` and `i128` just [landed in rustc](https://github.com/rust-lang/rust/pull/37900), and we should take advantage of them here until Rust has a proper `f128` since they should have the alignment restrictions we need.

This will only be available on nightly / unstable for a bit I think.

**Comment by pvdrz** [comment]
This already happens. I wasn't able to bisect to get the right commit due to not being able to compile old versions of bindgen with the right rustc version
