### ISSUE TITLE
Look into issues when generating grpc bindings.

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust-bindgen#406]
Just a reminder so I can look into the issues described in https://github.com/grpc/grpc/issues/9316#issuecomment-273564948

**Comment by fitzgen** [comment]
@emilio can we close this now?

**Comment by amanjeev** [comment]
Since the upstream issues https://github.com/grpc/grpc/issues/9316#issuecomment-273564948 and https://github.com/rust-lang/rust-bindgen/issues/381 (up the chain) seem to be closed/done, I am closing this issue. Please reopen if you think this has been closed erroneously.
