### ISSUE TITLE
Missing template argument for inner type typedef.

### ISSUE THREAD

**Issue by kkimdev** [rust-lang/rust-bindgen#422]
Header:
```C++
template <typename T>
class Foo {
 public:
  class InnerType {};
};

typedef Foo<int>::InnerType Bar;

Bar func();
```

Generated:
```Rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo<T> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<T>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo_InnerType<T> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<T>,
}
pub use self::Foo_InnerType as Bar;
extern "C" {
    #[link_name = "_Z4funcv"]
    pub fn func() -> Bar;
}
```

Compile error
```
error[E0243]: wrong number of type arguments: expected 1, found 0
  --> generated.rs:18:22
   |
18 |     pub fn func() -> Bar;
   |                      ^^^ expected 1 type argument
```

I think it should have generated

```Rust
pub type Bar = self::Foo_InnerType<::std::os::raw::c_int>;
```

**Comment by fitzgen** [comment]
@emilio this seems related to the type aliases -> use statements change. I don't think that trick is valid if we have template arguments.

**Comment by emilio** [comment]
huh? Indeed we check for that. I was pretty sure [this check](https://github.com/servo/rust-bindgen/commit/dfb25b389bec5492b6fd61e92a2552cab03a6afc#diff-a93145b6ffec56949842cfb61224da24R532) should've caught it, I'll take a look

**Comment by emilio** [comment]
So we do check that, and that check works. the thing is that the applicable_template_args check probably avoids specialized args.

**Comment by emilio** [comment]
i.e., this was a pre-existing bug

**Comment by emilio** [comment]
This is annoying. So when scanning the `Foo<int>::InnerType`, clang says us we're a template specialization, but when it points us to the specialized template, it points us to the unspecialized version of `Foo` (which is probably a logical thing to do, but that we don't take into account).

When asking about template parameters, of course, clangs tells us that we have none, so we end up not seeing the int at all. Ouch.

I can't keep investigating today (3AM here and I need to wake up in exactly 4 hours :/), but that's pretty much it, we're going to need to find that type, somehow.

**Comment by fitzgen** [comment]
After #544, there is still a bug here, but we need to modify the test case so that `Foo<T>::InnerType` uses `T` to make the bug reproduce:

```c++
template <typename T>
class Foo {
public:
    class InnerType {
        T t;
    };
};

typedef Foo<int>::InnerType Bar;

Bar func();
```

Generates this code:

```Rust
/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo_InnerType<T> {
    pub t: T,
}
pub type Bar = InnerType;
extern "C" {
    #[link_name = "_Z4funcv"]
    pub fn func() -> Bar;
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct InnerType {
    pub _address: u8,
}
impl Clone for InnerType {
    fn clone(&self) -> Self { *self }
}
```

Not sure what is going on with that top level `InnerType`.

**Comment by kkimdev** [comment]
@emilio @fitzgen 

@fitzgen's example code now generate the following and compiles fine.  Should we consider this as fixed?

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo_InnerType<T> {
    pub t: T,
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
}
pub type Bar = InnerType;
extern "C" {
    #[link_name = "\u{1}_Z4funcv"]
    pub fn func() -> Bar;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct InnerType {
    pub _address: u8,
}
```

**Comment by emilio** [comment]
Yes, we should add a test-case to the test-suite if we don't have one though.
