### ISSUE TITLE
Generate placeholder for .h implementation

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust-bindgen#440]
Use case: implement in Rust the functions defined in a .h. Currently I use bindgen + manual modifications (no_mangle, unimplemented!()).

**Comment by emilio** [comment]
You mean to generate a `.h` file from a rust file, right?

**Comment by emilio** [comment]
Ohh, ok, the other way around, I see

**Comment by emilio** [comment]
I think this should be sort of trivial once we have #429. We'd only have to change the code generation for functions after that.

**Comment by Yamakaky** [comment]
Example of generated output: https://github.com/Yamakaky/cinder/blob/master/src/vulkan_h.rs#L2875-L2879

**Comment by Zorvalt** [comment]
Is there any update on this ? I need to implement a rust library based on a large C header and did not find an appropriate tool to generate those placeholders. For now, I'm doing it by hand, based on what bindgen normally outputs, and it's long... Does someone has a better solution ?

**Comment by amanjeev** [comment]
Triage note: 

It has been long and the [example url](https://github.com/Yamakaky/cinder/blob/master/src/vulkan_h.rs#L2875-L2879) that is mentioned in [the comment above](https://github.com/rust-lang/rust-bindgen/issues/440#issuecomment-275107142) is gone.

To get clarification - 

- is this still needed?
- is it only about generating skeleton `fn`s with `unimplemented!`?

**Comment by amanjeev** [comment]
We have not heard back in a while.  I am closing this for now.  Please reopen if this is needed again.  Thank you.
