### ISSUE TITLE
It would be nice to be able to whitelist/blacklist methods

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust-bindgen#669]
Sometimes only a small number of a class's methods are needed, and the other unwanted ones have bad side-effects (namely, use awkward complex types, etc). It would be nice to have a `whitelist-method` option to allow selectively generating bindings for methods.

**Comment by fitzgen** [comment]
Sounds reasonable!

**Comment by iulianR** [comment]
Hello, is it currently not possible to whitelist a type, together with all its methods? I had some functions whitelisted and I'm also trying to whitelist the type (and all it's methods), but by using `whitelist_type("foo::bar::Baz:.*")`, only code for Baz is generated.
