### ISSUE TITLE
Support request: ChangeLog / NEWS

### ISSUE THREAD

**Issue by devurandom** [rust-lang/rust-bindgen#706]
I am unable to find a ChangeLog or NEWS file in this repo, in the docs or on crates.io. Could you please point me to it? I am specifically looking for the changes between 0.24 and 0.25.

**Comment by emilio** [comment]
So in the [releases page](/servo/rust-bindgen/releases) you can see the commits corresponding to each version using the `/compare/xxx..yyy` urls:

For example, for those changes: [compare/v0.24.0...v0.25.0](https://github.com/servo/rust-bindgen/compare/v0.24.0...v0.25.0) should list all the relevant changes from one version to the other.

I think that's the best thing we have right now. We try to use descriptive commit messages, so hopefully that's good enough. Perhaps we could enforce a link to that on each release from the readme? I'm not sure how much a `ChangeLog` really helps.

**Comment by devurandom** [comment]
You're right, a GNU-style ChangeLog that just lists all commits would not be helpful. But many projects abuse a file of this name for what GNU would put into a NEWS file, which is why I listed both filenames in this request to make search easier for others.

Thanks for the link. Commits are few and messages are good, so that indeed helped me.

**Comment by fitzgen** [comment]
Although I'm not usually a fan of writing changelogs and think it is often busy work...

I think from a marketing/publicity point of view, it would be great if we announced releases on users.rust-lang.org. We could list the contributors to each release, some changelog-y items, and I think this would serve as marketing/motivation for attracting more users, contributors, and eventually maintainers.

WDYT @emilio ? I am happy to take responsibility for writing it if we want to go down this path.

**Comment by kulp** [comment]
Starting in a4d5c7aed6f2ef0dfbb9d6cc27ce725de8ccab72 a `CHANGELOG.md` was introduced. It was marked as having fixed #1131, but it could have fixed the current issue too.

Consequently I am marking this issue closed.
