### ISSUE TITLE
Support marking types with "#[must_use]"

### ISSUE THREAD

**Issue by upsuper** [rust-lang/rust-bindgen#710]
There are some types (noticeable `already_AddRefed`) that we want them to always be consumed.

It is `MOZ_MUST_USE_TYPE` in Gecko, but there is currently no way to mark them `#[must_use]` in generated binding. We probably need something here.

I don't have idea what would be the best way to handle this, though.

**Comment by emilio** [comment]
Given we're in control of the type, perhaps an annotation may be ok?

**Comment by fitzgen** [comment]
I could imagine a `bindgen::Builder::must_use` method and `--must-use <blah>` flag. Shouldn't be too difficult for anyone who has contributed to bindgen before.

**Comment by emilio** [comment]
Fixed by #2081

**Comment by KarelPeeters** [comment]
@emilio Any chance you could publish a version for this?
