### ISSUE TITLE
Unnecessarily strict dependency on cfg-if

### ISSUE THREAD

**Issue by JonSeverinsson** [rust-lang/rust-bindgen#740]
Rust-bindgen depends explicitly on cfg-if 0.1.0, but would work just as well with the recently released 0.1.1, so I would suggest relaxing the dependency to any 0.1 version:

```
diff --git a/Cargo.toml b/Cargo.toml
index 549de64..e6ce5f3 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -44,7 +44,7 @@ quasi_codegen = "0.32"
 
 [dependencies]
 cexpr = "0.2"
-cfg-if = "0.1.0"
+cfg-if = "0.1"
 clang-sys = { version = "0.18.0", features = ["runtime", "clang_3_9"] }
 lazy_static = "0.2.1"
 peeking_take_while = "0.1.2"
```

**Comment by fitzgen** [comment]
Sounds good! Would you like to make a PR?

**Comment by emilio** [comment]
Isn't it the same? AFAICT `0.1.0` effectively means `0.1.x`, but I could be wrong.

**Comment by kulp** [comment]
This has been overtaken by events; 84b5455f882e10e9ddaa001dc8207023d82cdd5f updated the version, but 30fb4eccb3cf3068e4132e68ba832ec148c2b786 removed the direct dependency entirely.

Consequently I am closing this issue.
