### ISSUE TITLE
Add an ability to trim prefixes/postfixes of enums

### ISSUE THREAD

**Issue by vaartis** [rust-lang/rust-bindgen#777]
C enums are not qualified, while rust's are, it's not very convinient to write things like `TestEnum::TestEnumFieldOne`, therefore i propose to add an ability to trim prefix/postfix of enum field, so it becomes `TestEnum::FieldOne`

Current behaviour (llvm exmaple):
```C
enum LLVMTypeKind {
    LLVMFunctionTypeKind
}
```
produces
```Rust
enum LLVMTypeKind {
    LLVMFunctionTypeKind = 0
}
```

what i mean is to make it like this:
```rust
enum LLVMTypeKind {
    Function = 0
}
```

removing LLVM as prefix and TypeKind as postfix

**Comment by emilio** [comment]
This isn't terribly hard to implement, but I think it's hard to add a (good) API to this to the CLI, so I guess this could be restricted to users of bindgen as-a-library.

We could add a hook to `ParseCallbacks` when parsing to be able to rename enums and variants (the variant function could take the enum name as an argument).

**Comment by vaartis** [comment]
I might try to implement this myself, although i need some time to at least read through bindgen's code

**Comment by vaartis** [comment]
I have done some [progress](https://github.com/vaartis/rust-bindgen/commit/9ff93da853dd92032938ea9ec3699b9ebceedceb), but there are some questions:
- Where are enum custom behaviors implemented, because i get `no method named enum_field_rename found for type ir::enum_ty::EnumVariantCustomBehavior in the current scope`?
- What should we do about rename string in the EnumCustomBehavior: String does not implement copy and &str requires adding explicit lifetimes everywhere?

**Comment by grovesNL** [comment]
I agree that this would be great to have. I'm considering simply using regular expressions to make the changes on the generated text for now, but it's obviously very hacky 😄

**Comment by Lokathor** [comment]
@emilio I would _really like_ this to make it into the CLI version as well. It seems like it should be just a pair of boolean flag you flip on?

```
--remove-detected-enum-prefixes
--remove-detected-enum-suffixes
```

And then if all variants have whatever prefix, it trims that out with the flag on

**Comment by emilio** [comment]
Do we want to restrict them to `enum`s? 

This is feasible to do today without the CLI via [`ParseCallbacks::item_name`](https://github.com/rust-lang/rust-bindgen/pull/1438).

We could possibly just add a simple set of item renames like `remove-prefix` / `remove-suffix` or such to the CLI?

**Comment by pvdrz** [comment]
This can be done by using [`ParseCallbacks::enum_variant_name`](https://docs.rs/bindgen/latest/bindgen/callbacks/trait.ParseCallbacks.html#method.enum_variant_name).
