### ISSUE TITLE
Improve LLVM bug 9069 workaround

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust-bindgen#804]
Due to [LLVM bug 9069](https://bugs.llvm.org//show_bug.cgi?id=9069), an extra token is included when tokenizing ranges. This is used to parse macros. This bug is fixed in LLVM 4.0.

Our [current workaround](https://github.com/servo/rust-bindgen/blob/9faf458562db820c83f74be580b741f6b7dfd913/src/ir/var.rs#L294-L309) just tries parsing the macro twice, removing the last token if it failed the first time. This is not very robust and can result in unwanted behavior:
* In LLVM 3.9 and before, if the extra token happens to make sense syntactically, it is erroneously included in the macro evaluation
* In LLVM 4.0 and after, if the original macro definition had a syntax error, the macro will now get reevaluated with the last token removed, which might unintentionally parse correctly.

In the `cexpr` tests, instead we check which behavior we get at runtime by checking the result of parsing a know macro: https://github.com/jethrogb/rust-cexpr/commit/0ea13677b2400ba64b29de88bd7bd7cee8040af7 . @emilio suggested the same could be implemented here with a CXUnsavedFile.

**Comment by emilio** [comment]
Actually, wouldn't detecting that and always removing the last token fail if the macro declaration is the last thing in the file?

I guess improving this only allows us to avoid trying without the token if we detect the bug is _not_ present.

**Comment by jethrogb** [comment]
Hmm, yes, you're right. Unconditionally removing the last token if you detect the bug is not sufficient. This is why instead of working around the bug at the token level, in cexpr I look at it at the range level. In the buggy case, the range does extend past the end of the file, but since there is no data there, no extra token is returned. Adjusting the range always fixes the bug. This also matches the bug fix of LLVM itself.

**Comment by kulp** [comment]
This bug would be closed by #1807.

**Comment by kulp** [comment]
In https://github.com/rust-lang/rust-bindgen/pull/2155/commits/99b147d6f335ddce2061d30bf2d9a8dde553b261 (part of #2155, fulfilling the intent of #1807), the workaround for bug 9069 was removed.

Consequently I am marking this issue closed.
