### ISSUE TITLE
`union` has alignment of 1, expected 0

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust-bindgen#810]
I was not able to isolate the problem yet, so I don't have a MVE I could post here. I've got a large `union` of several structs (which include other structs, which include bitfields) for which bindgen 0.26.3 generates the default

```rust
#[repr(C)]
#[derive(Copy)]
pub struct wtap_pseudo_header {
    pub bindgen_union_field: [u8; 0usize]
}
```

The alignment-test for this type expects `::std::mem::align_of::<wtap_pseudo_header>()` to be `0`, yet for some reason it is always `1`. The unit-test generated by bindgen therefor fails.

Isn't there something fishy about an alignment of `1` anyway? Aren't we required to align to byte boundary anyway?

**Comment by emilio** [comment]
Well, that `0` is presumably what clang thinks the alignment is... Is this C or C++? The rules for zero-sized types change between those.

**Comment by lukaslueg** [comment]
It's C

**Comment by lukaslueg** [comment]
The offending `wtap_pseudo_header` is defined in `wiretap/wtap.h`. If I feed to bindgen
```C
#include <config.h>
#include <wiretap/wtap.h>
```
then it works. If I feed
```C
#include <config.h>
#include <epan/packet.h>  // includes writetap/wtap.h
```
the unittest generated by bindgen complains about the alignment of `wtap_pseudo_header` being 1, where 0 was expected. If I feed
```C
#include <config.h>
#include <wiretap/wtap.h>
#include <epan/packet.h>  // includes wiretap/wtap.h
```
it works again and all unittests pass.

**Comment by fitzgen** [comment]
@lukaslueg the best way to help resolve this bug would be to create a reduced test case without any `#include` directives: https://github.com/servo/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases

**Comment by pvdrz** [comment]
I'm closing this as no reduced test case was provided. Feel free to open this issue back with a test case.
