### ISSUE TITLE
loops in the name graph

### ISSUE THREAD

**Issue by db48x** [rust-lang/rust-bindgen#839]
### Input C/C++ Header

I don't have a minimal test case, and the whole thing is multiple megabytes. Perhaps I can revisit this soon and minimize one.

### Bindgen Invocation

```Rust
    let bindings = bindgen::Builder::default()
        .generate_comments(true)
        .clang_arg("-I../../src")
        .clang_arg("-I../../lib")
        .header("wrapper.h")
        .hide_type("BOOL_VECTOR_BITS_PER_CHAR")
        .generate()
        .expect("Unable to generate bindings");
```

### Actual Results

```rust
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum gnutls_cipher_algorithm {
    GNUTLS_CIPHER_UNKNOWN = 0,
    GNUTLS_CIPHER_NULL = 1,
    // etc…
}
pub use self::gnutls_cipher_algorithm as gnutls_cipher_algorithm_t;
// … 2000 lines later …
pub use self::gnutls_cipher_algorithm_t as gnutls_cipher_algorithm;
```

### Expected Results

The first `pub use` is fine, because many of the nearby function declarations use `gnutls_cipher_algorithm_t`. The second one is just silly, so it should be pruned.

**Comment by fitzgen** [comment]
Thanks again! As I said in the other bug, the best way to help us fix this issue is by providing a reduced test case: https://github.com/servo/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases

**Comment by db48x** [comment]
Agreed, but I would rather file it without a testcase and forget to revisit the issue than not file it at all.

**Comment by emilio** [comment]
> Agreed, but I would rather file it without a testcase and forget to revisit the issue than not file it at all.

Yeah, that's fair :)

Also sometimes it just rings a bell and we immediately know what's wrong, like in #840.

Without a reduced test-case we usually can't afford the time to investigate it in depth, but it's good that we can track it somewhere anyway, so thanks for it!

**Comment by emilio** [comment]
AFAICT this is gnutls, which does:

```h
// gnutls.h
typedef enum gnutls_cipher_algorithm {
	GNUTLS_CIPHER_UNKNOWN = 0,
	// ...
} gnutls_cipher_algorithm_t;
```

And then:

```
// compat.h/* Stuff deprected in 2.x */
typedef gnutls_cipher_algorithm_t gnutls_cipher_algorithm
    _GNUTLS_GCC_ATTR_DEPRECATED;
```

**Comment by emilio** [comment]
And thus a reduced test-case could be:

```h
typedef enum foo {
  BAR,
  BAZ,
} foo_t;

typedef foo_t foo;
```

**Comment by emilio** [comment]
Which is quite annoying if you ask me.

**Comment by pvdrz** [comment]
If you run this test case with the current version of bindgen, you get:
```rust
pub const foo_BAR: foo = 0;
pub const foo_BAZ: foo = 1;
pub type foo = ::std::os::raw::c_uint;
pub use self::foo as foo_t;
```
if you mar `foo` as a `rustified_enum`:
```rust
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum foo {
    BAR = 0,
    BAZ = 1,
}
pub use self::foo as foo_t;
```
So I think we can close this.
