### ISSUE TITLE
Type alias option

### ISSUE THREAD

**Issue by pronebird** [rust-lang/rust-bindgen#903]
### Input C/C++ Header

```C++
struct pfioc_trans {
	int		 size;	/* number of elements */
	int		 esize; /* size of each element in bytes */
	struct pfioc_trans_e {
		int		rs_num;
		char		anchor[MAXPATHLEN];
		u_int32_t	ticket;
	} *array __attribute__((aligned(8)));
};
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("input.h")
    .generate()
    .unwrap()
```

### Actual Results

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct pfioc_trans {
    pub size: ::std::os::raw::c_int,
    pub esize: ::std::os::raw::c_int,
    pub array: *mut pfioc_trans_pfioc_trans_e,
}
#[repr(C)]
pub struct pfioc_trans_pfioc_trans_e {
    pub rs_num: ::std::os::raw::c_int,
    pub anchor: [::std::os::raw::c_char; 1024usize],
    pub ticket: u_int32_t,
}
```

### Expected Results

This is expected now that Bindgen generates `pfioc_trans_e` as `pfioc_trans_pfioc_trans_e`. 

However I find it quite ugly. I am thinking that it would be great to provide an option to builder to add type aliases. 

Currently it's possible to add type alias with:

`raw_line("pub type pfioc_trans_e = pfioc_trans_pfioc_trans_e;")`, 

but 

`type_alias(new, existing)` on Builder would be better.

**Comment by fitzgen** [comment]
I guess? Is this that much better than the `raw_line` or adding a type alias to the module that includes/uses the emitted bindings?

**Comment by pvdrz** [comment]
I'm closing this issue as it can be solved by defining a callback:

```rust
#[derive(Debug)]
struct Replace;

impl bindgen::callbacks::ParseCallbacks for Replace {
    fn item_name(&self, name: &str) -> Option<String> {
        (name == "pfioc_trans_pfioc_trans_e").then(|| "pfioc_trans_e".to_owned())
    }
}
```
and then changing `main` to do:
```rust
bindgen::Builder::default()
    .header("input.h")
    .parse_callbacks(Box::new(callback))
    .generate()
    .unwrap()
```
