### ISSUE TITLE
Allow specifying certain types we shouldn't derive/impl Default for

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/rust-bindgen#963]
Add `--no-default <regex>` and `Builder::no_default(String)` to supply regexes for matching against types that we should not derive or implement `Default` for.

Adding this feature involves:

* [ ] Adding a new `RegexSet` member to `bindgen::Builder` (similar to the `whitelisted_types` set).

* [ ] A `Builder` method to add strings to that `RegexSet`.

* [ ] Plumbing in `src/options.rs` to convert `--no-default <regex>` CLI flags into invocations of the builder method.

* [ ] Making the `MonotoneFramework::constrain` function in `src/ir/analysis/derive_default.rs` check if the given item is explicitly marked not to be `Default`, and if so, inserting it into the `self.cannot_derive_default` set via `return self.insert(id)`.

* [ ] Tests!

    * [ ] When the no-default type is transitively referenced by a whitelisted item

    * [ ] When the no-default type is explicitly whitelisted

    * [ ] When the no-default type is marked opaque

**Comment by GyrosOfWar** [comment]
Hi! I'd like to do this. 

@highfive: assign me

**Comment by fitzgen** [comment]
@GyrosOfWar let me know if you have any questions :)

This should be pretty similar to the `--no-partialeq` PR that just landed, so you can take a look at that for guidance: https://github.com/rust-lang-nursery/rust-bindgen/pull/996

**Comment by GyrosOfWar** [comment]
Yeah, I've found that one already. Should be pretty straightforward. I've joined the Gitter room, so I'll ask there if I need anything.

**Comment by pvdrz** [comment]
Already implemented
